/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@class MailboxContentViewCell, UIColor;

@interface _CellStaticView : UIView {

	unsigned long long _lastDrawingGenerationNumber;
	unsigned long long _lastLayoutGenerationNumber;
	unsigned _highlighted : 1;
	MailboxContentViewCell* _cell;
	UIColor* _originalBackgroundColor;

}

@property (assign,nonatomic) MailboxContentViewCell * cell;                      //@synthesize cell=_cell - In the implementation block
@property (nonatomic,retain) UIColor * originalBackgroundColor;                  //@synthesize originalBackgroundColor=_originalBackgroundColor - In the implementation block
@property (assign,getter=isHighlighted,nonatomic) BOOL highlighted; 
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setNeedsDisplay;
-(void)drawRect:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id)description;
-(void)setHighlighted:(BOOL)arg1 ;
-(BOOL)isHighlighted;
-(MailboxContentViewCell *)cell;
-(void)setCell:(MailboxContentViewCell *)arg1 ;
-(void)setOriginalBackgroundColor:(UIColor *)arg1 ;
-(UIColor *)originalBackgroundColor;
@end

