/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIFont;

@interface _MailboxContentViewCellLayoutValues : NSObject {

	UIFont* _addressFont;
	UIFont* _dateFont;
	UIFont* _subjectFont;
	UIFont* _summaryFont;
	UIFont* _mailboxFont;
	double _compactRowHeight;
	double _defaultRowHeight;
	double _topMargin;
	double _bottomMargin;
	double _topPadding;
	double _leading;
	double _addressCapHeight;
	double _dateCapHeight;
	double _subjectCapHeight;
	double _summaryCapHeight;
	double _bottomPadding;

}

@property (nonatomic,readonly) UIFont * addressFont; 
@property (nonatomic,readonly) UIFont * dateFont; 
@property (nonatomic,readonly) UIFont * subjectFont; 
@property (nonatomic,readonly) UIFont * summaryFont; 
@property (nonatomic,readonly) UIFont * mailboxFont; 
@property (nonatomic,readonly) double compactRowHeight; 
@property (nonatomic,readonly) double defaultRowHeight; 
@property (nonatomic,readonly) double leading; 
@property (nonatomic,readonly) double topPadding; 
@property (nonatomic,readonly) double addressCapHeight; 
@property (nonatomic,readonly) double dateCapHeight; 
@property (nonatomic,readonly) double subjectCapHeight; 
@property (nonatomic,readonly) double summaryCapHeight; 
@property (nonatomic,readonly) double bottomPadding; 
@property (assign,nonatomic) double topMargin;                       //@synthesize topMargin=_topMargin - In the implementation block
@property (assign,nonatomic) double bottomMargin;                    //@synthesize bottomMargin=_bottomMargin - In the implementation block
+(id)sharedInstance;
-(double)compactRowHeight;
-(UIFont *)dateFont;
-(UIFont *)mailboxFont;
-(double)addressCapHeight;
-(double)dateCapHeight;
-(UIFont *)addressFont;
-(UIFont *)subjectFont;
-(double)heightWithNumberOfSummaryLines:(int)arg1 ;
-(double)subjectCapHeight;
-(double)summaryCapHeight;
-(void)dealloc;
-(void)invalidate;
-(double)topMargin;
-(UIFont *)summaryFont;
-(double)leading;
-(double)topPadding;
-(double)bottomPadding;
-(double)bottomMargin;
-(void)setTopMargin:(double)arg1 ;
-(double)defaultRowHeight;
-(void)setBottomMargin:(double)arg1 ;
@end

