/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface _MBLCullOldMessagesJob : NSObject {

	NSMutableArray* _messages;
	id _mbl;

}

@property (nonatomic,copy) NSMutableArray * messages; 
-(id)initForMBLMailbox:(id)arg1 ;
-(void)dealloc;
-(void)run;
-(NSMutableArray *)messages;
-(void)setMessages:(NSMutableArray *)arg1 ;
@end

