/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MBLSingleMessageClient;
@interface _MBLLoadForClientJob : NSObject {

	id<MBLSingleMessageClient> _client;
	id _mbl;

}

@property (nonatomic,readonly) id<MBLSingleMessageClient> client;              //@synthesize client=_client - In the implementation block
-(id)initForClient:(id)arg1 forMBLMailbox:(id)arg2 ;
-(void)dealloc;
-(void)run;
-(id<MBLSingleMessageClient>)client;
@end

