/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@class UIView, _MFActorSnapshotView;

@interface _MFActorItemView : UIView {

	UIView* _dimmingView;
	UIView* _backgroundBorderView;
	_MFActorSnapshotView* _snapshotView;
	UIView* _viewControllerContentView;
	double _cornerRadius;

}

@property (nonatomic,readonly) UIView * backgroundBorderView;                  //@synthesize backgroundBorderView=_backgroundBorderView - In the implementation block
@property (nonatomic,readonly) UIView * dimmingView;                           //@synthesize dimmingView=_dimmingView - In the implementation block
@property (assign,nonatomic) double cornerRadius;                              //@synthesize cornerRadius=_cornerRadius - In the implementation block
@property (nonatomic,retain) _MFActorSnapshotView * snapshotView;              //@synthesize snapshotView=_snapshotView - In the implementation block
@property (nonatomic,retain) UIView * contentView;                             //@synthesize viewControllerContentView=_viewControllerContentView - In the implementation block
-(UIView *)backgroundBorderView;
-(void)_updateCornerRadii;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(_MFActorSnapshotView *)snapshotView;
-(void)setCornerRadius:(double)arg1 ;
-(UIView *)contentView;
-(void)setContentView:(UIView *)arg1 ;
-(double)cornerRadius;
-(UIView *)dimmingView;
-(void)setSnapshotView:(_MFActorSnapshotView *)arg1 ;
@end

