/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface _MFDelayedMessage : NSObject {

	unsigned _state;
	id _message;
	NSString* _identifier;
	double _submissionDate;
	id _context;

}

@property (nonatomic,retain) id message;                         //@synthesize message=_message - In the implementation block
@property (nonatomic,copy) NSString * identifier;                //@synthesize identifier=_identifier - In the implementation block
@property (assign,nonatomic) double submissionDate;              //@synthesize submissionDate=_submissionDate - In the implementation block
@property (nonatomic,retain) id context;                         //@synthesize context=_context - In the implementation block
-(id)initWithMessage:(id)arg1 identifier:(id)arg2 submissionDate:(double)arg3 context:(id)arg4 ;
-(void)dealloc;
-(id)init;
-(void)invalidate;
-(NSString *)identifier;
-(id)context;
-(void)setIdentifier:(NSString *)arg1 ;
-(id)message;
-(void)setMessage:(id)arg1 ;
-(void)setContext:(id)arg1 ;
-(void)setSubmissionDate:(double)arg1 ;
-(double)submissionDate;
-(BOOL)isInvalidated;
-(void)process;
-(BOOL)isProcessing;
@end

