/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Message/MFBufferedQueue.h>
#import <libobjc.A.dylib/MFSearchResultHandler.h>

@protocol OS_dispatch_queue, MSDSearchResultsProtocol, MFMessageIterationFilter;
@class NSObject, MFMessageResultsGenerator;

@interface _MFDSearchResultsQueue : MFBufferedQueue <MFSearchResultHandler> {

	NSObject*<OS_dispatch_queue> _queue;
	id<MSDSearchResultsProtocol> _resultsProxy;
	id<MFMessageIterationFilter> _filter;
	MFMessageResultsGenerator* _generator;

}
-(id)initWithKeys:(id)arg1 resultsProxy:(id)arg2 filter:(id)arg3 ;
-(void)handleMessage:(id)arg1 ;
-(void)dealloc;
-(BOOL)handleItems:(id)arg1 ;
-(void)beginResult:(unsigned)arg1 ;
-(void)setResultSubject:(char*)arg1 ;
-(void)setResultSender:(char*)arg1 ;
-(void)setResultDateRecieved:(double)arg1 ;
-(void)setResultUnread:(BOOL)arg1 ;
-(void)endResult;
-(id)filter;
@end

