/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MBLSingleMessageClient.h>

@class MFMessageBulletinsObserver, MFLibraryMessage, NSString;

@interface _MFMessageBulletinsObserverSummaryClient : NSObject <MBLSingleMessageClient> {

	MFMessageBulletinsObserver* _observer;
	MFLibraryMessage* _message;
	unsigned long long _attempts;
	unsigned long long _priority;
	double _ordering;

}

@property (nonatomic,retain) MFMessageBulletinsObserver * observer;              //@synthesize observer=_observer - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)wantsContentsOfType:(int)arg1 ;
-(void)notifyContentsAvailable:(id)arg1 forMessage:(id)arg2 ;
-(void)notifyContentsUnavailableForMessage:(id)arg1 error:(id)arg2 ;
-(id)initWithObserver:(id)arg1 message:(id)arg2 ;
-(unsigned long long)_calculatePriority;
-(unsigned long long)_calculateOrdering;
-(double)ordering;
-(void)dealloc;
-(NSString *)description;
-(unsigned long long)priority;
-(id)message;
-(MFMessageBulletinsObserver *)observer;
-(void)setObserver:(MFMessageBulletinsObserver *)arg1 ;
@end

