/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class MFSearchSuggestion, NSString, MFSearchSuggestionCategoryScope;

@interface _MFSearchSuggestionAtom : NSObject <NSSecureCoding> {

	MFSearchSuggestion* _suggestion;
	NSString* _editingString;
	long long _selectedScopeIndex;

}

@property (nonatomic,retain,readonly) MFSearchSuggestion * suggestion;                       //@synthesize suggestion=_suggestion - In the implementation block
@property (nonatomic,copy,readonly) NSString * editingString;                                //@synthesize editingString=_editingString - In the implementation block
@property (nonatomic,copy,readonly) NSString * displayName; 
@property (assign,nonatomic) long long selectedScopeIndex;                                   //@synthesize selectedScopeIndex=_selectedScopeIndex - In the implementation block
@property (nonatomic,readonly) MFSearchSuggestionCategoryScope * selectedScope; 
+(id)atomWithSuggestion:(id)arg1 editingString:(id)arg2 ;
+(BOOL)supportsSecureCoding;
-(void)setSelectedScopeIndex:(long long)arg1 ;
-(long long)selectedScopeIndex;
-(MFSearchSuggestion *)suggestion;
-(MFSearchSuggestionCategoryScope *)selectedScope;
-(NSString *)editingString;
-(id)initWithSuggestion:(id)arg1 editingString:(id)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)description;
-(NSString *)displayName;
-(id)criterion;
@end

