/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MBLSingleMessageClient.h>

@protocol OS_dispatch_semaphore;
@class MFMailMessageLibrary, MFMailMessage, NSObject, NSString;

@interface _MFSuggestionsMessageBodyLoaderClient : NSObject <MBLSingleMessageClient> {

	MFMailMessageLibrary* _library;
	MFMailMessage* _message;
	NSObject*<OS_dispatch_semaphore> _semaphore;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)wantsContentsOfType:(int)arg1 ;
-(void)notifyContentsAvailable:(id)arg1 forMessage:(id)arg2 ;
-(void)notifyContentsUnavailableForMessage:(id)arg1 error:(id)arg2 ;
-(void)notifyFullMessageContentsUnavailableForMessage:(id)arg1 error:(id)arg2 ;
-(id)initWithLibrary:(id)arg1 message:(id)arg2 semaphore:(id)arg3 ;
-(double)ordering;
-(void)dealloc;
-(unsigned long long)priority;
-(id)message;
@end

