/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary;

@interface _MFSimulatedUserActivity : NSObject {

	NSDictionary* _userInfo;

}

@property (nonatomic,copy) NSDictionary * userInfo;              //@synthesize userInfo=_userInfo - In the implementation block
-(void)noOp;
-(void)dealloc;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)becomeCurrent;
-(void)setUserInfo:(NSDictionary *)arg1 ;
-(NSDictionary *)userInfo;
-(void)forwardInvocation:(id)arg1 ;
-(id)initWithActivityType:(id)arg1 ;
@end

