/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIGestureRecognizer.h>

@interface _MFTouchDownTapRecognizer : UIGestureRecognizer {

	unsigned long long _numberOfTouches;
	id _touchdownTarget;
	SEL _touchdownAction;

}

@property (assign,nonatomic) id touchdownTarget;               //@synthesize touchdownTarget=_touchdownTarget - In the implementation block
@property (assign,nonatomic) SEL touchdownAction;              //@synthesize touchdownAction=_touchdownAction - In the implementation block
-(id)touchdownTarget;
-(void)setTouchdownTarget:(id)arg1 ;
-(SEL)touchdownAction;
-(void)setTouchdownAction:(SEL)arg1 ;
-(id)initWithTarget:(id)arg1 action:(SEL)arg2 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)reset;
-(unsigned long long)numberOfTouches;
@end

