/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@class UIView, _TabGradientView, _MFTiltedTabCloseButton;

@interface _MFTiltedTabItemView : UIView {

	BOOL _topBackdropScaled;
	BOOL _contentViewNeedsRemoval;
	BOOL _autoresizesContentView;
	BOOL _editing;
	BOOL _reordering;
	BOOL _closing;
	BOOL _finishedClosing;
	UIView* _headerView;
	UIView* _contentClipperView;
	UIView* _borrowedContentView;
	_TabGradientView* _contentShadowView;
	double _topBackdropHeight;
	_MFTiltedTabCloseButton* _closeButton;
	double _borrowedContentScale;
	unsigned long long _contentViewType;
	long long _capturedInterfaceOrientation;
	unsigned long long _indexForLayout;
	unsigned long long _countForLayout;
	double _verticalScrollAdjustment;
	CGRect _closeButtonHitRect;

}

@property (nonatomic,readonly) UIView * headerView;                                      //@synthesize headerView=_headerView - In the implementation block
@property (nonatomic,readonly) UIView * contentClipperView;                              //@synthesize contentClipperView=_contentClipperView - In the implementation block
@property (nonatomic,retain) UIView * borrowedContentView;                               //@synthesize borrowedContentView=_borrowedContentView - In the implementation block
@property (nonatomic,readonly) _TabGradientView * contentShadowView;                     //@synthesize contentShadowView=_contentShadowView - In the implementation block
@property (assign,nonatomic) BOOL topBackdropScaled;                                     //@synthesize topBackdropScaled=_topBackdropScaled - In the implementation block
@property (assign,nonatomic) double topBackdropHeight;                                   //@synthesize topBackdropHeight=_topBackdropHeight - In the implementation block
@property (assign,nonatomic) CGRect closeButtonHitRect;                                  //@synthesize closeButtonHitRect=_closeButtonHitRect - In the implementation block
@property (nonatomic,readonly) _MFTiltedTabCloseButton * closeButton;                    //@synthesize closeButton=_closeButton - In the implementation block
@property (assign,nonatomic) double borrowedContentScale;                                //@synthesize borrowedContentScale=_borrowedContentScale - In the implementation block
@property (assign,nonatomic) unsigned long long contentViewType;                         //@synthesize contentViewType=_contentViewType - In the implementation block
@property (assign,nonatomic) long long capturedInterfaceOrientation;                     //@synthesize capturedInterfaceOrientation=_capturedInterfaceOrientation - In the implementation block
@property (assign,nonatomic) CATransform3D contentTransform; 
@property (assign,nonatomic) BOOL contentViewNeedsRemoval;                               //@synthesize contentViewNeedsRemoval=_contentViewNeedsRemoval - In the implementation block
@property (assign,nonatomic) BOOL autoresizesContentView;                                //@synthesize autoresizesContentView=_autoresizesContentView - In the implementation block
@property (assign,getter=isEditing,nonatomic) BOOL editing;                              //@synthesize editing=_editing - In the implementation block
@property (assign,getter=isReordering,nonatomic) BOOL reordering;                        //@synthesize reordering=_reordering - In the implementation block
@property (assign,getter=isClosing,nonatomic) BOOL closing;                              //@synthesize closing=_closing - In the implementation block
@property (assign,getter=isFinishedClosing,nonatomic) BOOL finishedClosing;              //@synthesize finishedClosing=_finishedClosing - In the implementation block
@property (assign,nonatomic) unsigned long long indexForLayout;                          //@synthesize indexForLayout=_indexForLayout - In the implementation block
@property (assign,nonatomic) unsigned long long countForLayout;                          //@synthesize countForLayout=_countForLayout - In the implementation block
@property (assign,nonatomic) double verticalScrollAdjustment;                            //@synthesize verticalScrollAdjustment=_verticalScrollAdjustment - In the implementation block
+(id)_newContentShadowView;
-(void)layoutHeaderViewAnimated:(BOOL)arg1 closeButton:(BOOL)arg2 ;
-(CATransform3D)contentTransform;
-(void)setContentTransform:(CATransform3D)arg1 ;
-(void)setBorrowedContentScale:(double)arg1 ;
-(void)setBorrowedContentView:(UIView *)arg1 ;
-(UIView *)contentClipperView;
-(UIView *)borrowedContentView;
-(_TabGradientView *)contentShadowView;
-(BOOL)topBackdropScaled;
-(void)setTopBackdropScaled:(BOOL)arg1 ;
-(double)topBackdropHeight;
-(void)setTopBackdropHeight:(double)arg1 ;
-(CGRect)closeButtonHitRect;
-(void)setCloseButtonHitRect:(CGRect)arg1 ;
-(double)borrowedContentScale;
-(unsigned long long)contentViewType;
-(void)setContentViewType:(unsigned long long)arg1 ;
-(long long)capturedInterfaceOrientation;
-(void)setCapturedInterfaceOrientation:(long long)arg1 ;
-(BOOL)contentViewNeedsRemoval;
-(void)setContentViewNeedsRemoval:(BOOL)arg1 ;
-(BOOL)autoresizesContentView;
-(void)setAutoresizesContentView:(BOOL)arg1 ;
-(void)setReordering:(BOOL)arg1 ;
-(void)setClosing:(BOOL)arg1 ;
-(BOOL)isFinishedClosing;
-(void)setFinishedClosing:(BOOL)arg1 ;
-(unsigned long long)indexForLayout;
-(void)setIndexForLayout:(unsigned long long)arg1 ;
-(unsigned long long)countForLayout;
-(void)setCountForLayout:(unsigned long long)arg1 ;
-(double)verticalScrollAdjustment;
-(void)setVerticalScrollAdjustment:(double)arg1 ;
-(void)dealloc;
-(id)init;
-(void)layoutSubviews;
-(BOOL)_shouldAnimatePropertyWithKey:(id)arg1 ;
-(BOOL)isEditing;
-(void)setEditing:(BOOL)arg1 ;
-(UIView *)headerView;
-(_MFTiltedTabCloseButton *)closeButton;
-(BOOL)isClosing;
-(BOOL)isReordering;
@end

