/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ABPersonViewControllerPrivateDelegate <ABPersonViewControllerDelegate>
@optional
-(void*)personForVCardRepresentation;
-(BOOL)personViewController:(id)arg1 shouldPresentMessageCompositionWithVCard:(id)arg2 filename:(id)arg3;
-(void)personViewController:(id)arg1 willSetEditing:(BOOL)arg2 animated:(BOOL)arg3;
-(void)personViewController:(id)arg1 didLoadScrollView:(id)arg2;
-(BOOL)isPersonViewControllerInCustomPopover:(id)arg1;
-(void)personViewController:(id)arg1 scrollViewDidScroll:(id)arg2;
-(void)personViewController:(id)arg1 didReloadDataInScrollView:(id)arg2;

@end

