/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ABUnknownPersonViewControllerDelegate <NSObject>
@optional
-(BOOL)unknownPersonViewController:(id)arg1 shouldPerformDefaultActionForPerson:(const void*)arg2 property:(int)arg3 identifier:(int)arg4;

@required
-(void)unknownPersonViewController:(id)arg1 didResolveToPerson:(const void*)arg2;

@end

