/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UITableViewController.h>

@protocol AccountListControllerDelegate;
@class MailAccount, NSSet;

@interface AccountListController : UITableViewController {

	id<AccountListControllerDelegate> _accountListDelegate;
	MailAccount* _selectedAccount;
	NSSet* _disabledAccounts;

}

@property (assign,nonatomic) id<AccountListControllerDelegate> accountListDelegate;              //@synthesize accountListDelegate=_accountListDelegate - In the implementation block
@property (nonatomic,retain) MailAccount * selectedAccount;                                      //@synthesize selectedAccount=_selectedAccount - In the implementation block
@property (nonatomic,copy) NSSet * disabledAccounts;                                             //@synthesize disabledAccounts=_disabledAccounts - In the implementation block
-(BOOL)containsMultipleAccounts;
-(BOOL)_enableAccount:(id)arg1 ;
-(void)selectAccount:(id)arg1 mailbox:(id)arg2 ;
-(id<AccountListControllerDelegate>)accountListDelegate;
-(void)setAccountListDelegate:(id<AccountListControllerDelegate>)arg1 ;
-(MailAccount *)selectedAccount;
-(void)setSelectedAccount:(MailAccount *)arg1 ;
-(NSSet *)disabledAccounts;
-(void)setDisabledAccounts:(NSSet *)arg1 ;
-(void)dealloc;
-(id)init;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(BOOL)shouldAutorotate;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)_getRotationContentSettings:(SCD_Struct_Ma3*)arg1 ;
-(BOOL)canDismiss;
-(void)cancelButtonClicked;
-(id)accounts;
@end

