/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface AutoFetchHistoryEntry : NSObject {

	NSString* _mailboxPath;
	unsigned long long _frequency;
	double _lastFetchTime;
	double _lastFetchDuration;

}

@property (nonatomic,readonly) NSString * mailboxPath;                  //@synthesize mailboxPath=_mailboxPath - In the implementation block
@property (assign,nonatomic) unsigned long long frequency;              //@synthesize frequency=_frequency - In the implementation block
@property (assign,nonatomic) double lastFetchTime;                      //@synthesize lastFetchTime=_lastFetchTime - In the implementation block
@property (assign,nonatomic) double lastFetchDuration;                  //@synthesize lastFetchDuration=_lastFetchDuration - In the implementation block
-(double)lastFetchTime;
-(id)initWithMailboxPath:(id)arg1 ;
-(NSString *)mailboxPath;
-(void)setLastFetchTime:(double)arg1 ;
-(double)lastFetchDuration;
-(void)setLastFetchDuration:(double)arg1 ;
-(void)dealloc;
-(unsigned long long)frequency;
-(void)setFrequency:(unsigned long long)arg1 ;
@end

