/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/AFCVisibleMailboxFetch.h>

@class NSString, MFMailboxUid, MFMailMessageStore, MFError, MFActivityMonitor, MailAccount;

@interface AutoFetchRequestPrivate : NSObject <AFCVisibleMailboxFetch> {

	NSString* _remoteID;
	MFMailboxUid* _uid;
	MFMailMessageStore* _store;
	NSString* _key;
	double _responsiveness;
	unsigned long long _gotNewMessagesState;
	BOOL _wasPrimaryMailbox;
	MFError* _error;
	long long _result;
	BOOL _displayErrors;
	BOOL _compactMailbox;
	BOOL _isVisibleFetch;
	BOOL _isUserRequested;
	BOOL _isForegroundRequest;
	BOOL _shouldGrowFetchWindow;
	BOOL _isPush;
	BOOL _isScheduled;
	MFActivityMonitor* _monitor;

}

@property (nonatomic,copy) NSString * remoteIDToPreserve;                         //@synthesize remoteID=_remoteID - In the implementation block
@property (nonatomic,copy) NSString * key;                                        //@synthesize key=_key - In the implementation block
@property (assign,nonatomic) BOOL shouldCompact;                                  //@synthesize compactMailbox=_compactMailbox - In the implementation block
@property (assign,nonatomic) BOOL displayErrors;                                  //@synthesize displayErrors=_displayErrors - In the implementation block
@property (assign,nonatomic) unsigned long long gotNewMessagesState;              //@synthesize gotNewMessagesState=_gotNewMessagesState - In the implementation block
@property (assign,nonatomic) BOOL wasPrimaryMailbox;                              //@synthesize wasPrimaryMailbox=_wasPrimaryMailbox - In the implementation block
@property (assign,nonatomic) BOOL isVisibleFetch;                                 //@synthesize isVisibleFetch=_isVisibleFetch - In the implementation block
@property (assign,nonatomic) BOOL isUserRequested;                                //@synthesize isUserRequested=_isUserRequested - In the implementation block
@property (assign,nonatomic) BOOL isForegroundRequest;                            //@synthesize isForegroundRequest=_isForegroundRequest - In the implementation block
@property (assign,nonatomic) BOOL shouldGrowFetchWindow;                          //@synthesize shouldGrowFetchWindow=_shouldGrowFetchWindow - In the implementation block
@property (assign,nonatomic) BOOL isPush;                                         //@synthesize isPush=_isPush - In the implementation block
@property (assign,nonatomic) BOOL isScheduled;                                    //@synthesize isScheduled=_isScheduled - In the implementation block
@property (assign,nonatomic) double responsiveness;                               //@synthesize responsiveness=_responsiveness - In the implementation block
@property (nonatomic,retain) MFError * error;                                     //@synthesize error=_error - In the implementation block
@property (nonatomic,readonly) long long result;                                  //@synthesize result=_result - In the implementation block
@property (nonatomic,readonly) MFActivityMonitor * monitor;                       //@synthesize monitor=_monitor - In the implementation block
@property (nonatomic,readonly) MFMailboxUid * uid;                                //@synthesize uid=_uid - In the implementation block
@property (nonatomic,readonly) MailAccount * account; 
@property (nonatomic,readonly) BOOL shouldNotify; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setDisplayErrors:(BOOL)arg1 ;
-(void)setRemoteIDToPreserve:(NSString *)arg1 ;
-(void)setShouldCompact:(BOOL)arg1 ;
-(BOOL)willGrowFetchWindow;
-(id)initRequestForMailboxUid:(id)arg1 ;
-(void)setIsForegroundRequest:(BOOL)arg1 ;
-(void)setShouldGrowFetchWindow:(BOOL)arg1 ;
-(void)logSummary:(id)arg1 error:(id)arg2 ;
-(NSString *)remoteIDToPreserve;
-(BOOL)displayErrors;
-(BOOL)shouldCompact;
-(BOOL)wasPrimaryMailbox;
-(void)setWasPrimaryMailbox:(BOOL)arg1 ;
-(BOOL)isVisibleFetch;
-(void)setIsVisibleFetch:(BOOL)arg1 ;
-(double)responsiveness;
-(void)setResponsiveness:(double)arg1 ;
-(BOOL)isForegroundRequest;
-(BOOL)isPush;
-(void)setIsPush:(BOOL)arg1 ;
-(void)setIsScheduled:(BOOL)arg1 ;
-(BOOL)isScheduled;
-(void)dealloc;
-(NSString *)key;
-(void)run;
-(MFMailboxUid *)uid;
-(void)setKey:(NSString *)arg1 ;
-(long long)result;
-(MFActivityMonitor *)monitor;
-(BOOL)shouldGrowFetchWindow;
-(BOOL)isUserRequested;
-(void)setIsUserRequested:(BOOL)arg1 ;
-(void)setGotNewMessagesState:(unsigned long long)arg1 ;
-(unsigned long long)gotNewMessagesState;
-(id)mailbox;
-(BOOL)shouldNotify;
-(MailAccount *)account;
-(MFError *)error;
-(void)setError:(MFError *)arg1 ;
@end

