/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <libobjc.A.dylib/MFDiagnosticsGenerator.h>
#import <MobileMail/AutoFetchController.h>

@protocol AutoFetchController
@required
-(oneway void)fetchNow:(int)arg1;
-(oneway void)startAutoFetch;
-(oneway void)networkConfigurationChanged;
-(oneway void)stopAutoFetch;
-(oneway void)fetchNow:(int)arg1 withAccounts:(id)arg2;
-(oneway void)fetchNow:(int)arg1 withSources:(id)arg2;
-(oneway void)setDataSource:(id)arg1;
-(BOOL)isIdle;

@end

#import <libobjc.A.dylib/MFContentProtectionObserver.h>
#import <MobileMail/PCConnectionManagerDelegate.h>

@protocol AutoFetchControllerDataSource;
@class PCConnectionManager, NSMutableDictionary, NSMutableSet, NSArray, NSTimer, NSString;

@interface AutoFetchController : NSObject <MFDiagnosticsGenerator, AutoFetchController, MFContentProtectionObserver, PCConnectionManagerDelegate> {

	id<AutoFetchControllerDataSource> _dataSource;
	double _lastNonvisibleAutoFetchDate;
	PCConnectionManager* _manager;
	NSMutableDictionary* _accountResponsiveness;
	NSMutableSet* _uidsToFetchAfterFirstUnlock;
	unsigned long long _outstandingAccountChangeFetchRequests;
	int _notifyLockStateToken;
	unsigned long long _holdState;
	unsigned _pmNotifier;
	IONotificationPortRef _pmPort;
	CFRunLoopSourceRef _pmSource;
	int _autoFetchState;
	int _fetchType;
	int _pendingFetchType;
	BOOL _lastAutoFetchHadErrors;
	BOOL _lastAutoFetchHadSources;
	NSArray* _fetchAccounts;
	NSArray* _pendingFetchAccounts;
	NSArray* _visibleSources;
	NSArray* _visibleSourceJobInvocations;
	unsigned long long _outstandingAutoFetchRequests;
	NSTimer* _networkWakeupTimeout;
	unsigned _isReachable : 1;
	unsigned _monitoringReachability : 1;
	unsigned _tryFetchWhenReachable : 1;
	unsigned _PCTimerIsRunning : 1;
	unsigned _waitingForFirstUnlock : 1;

}

@property (assign,nonatomic) int autoFetchState; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedController;
-(oneway void)fetchNow:(int)arg1 ;
-(oneway void)startAutoFetch;
-(oneway void)_batterySaverModeDidChange;
-(oneway void)networkConfigurationChanged;
-(oneway void)stopAutoFetch;
-(oneway void)fetchNow:(int)arg1 withAccounts:(id)arg2 ;
-(oneway void)fetchNow:(int)arg1 withSources:(id)arg2 ;
-(BOOL)_tryFetch:(int)arg1 ;
-(void)restartPCTimer;
-(void)handlePollEvent;
-(void)_accountContentsDidChange:(id)arg1 ;
-(void)_registerLockUnlockStateNotification;
-(void)_cleanUpReachabilityTimer;
-(BOOL)_tryFetch:(int)arg1 withAccounts:(id)arg2 ;
-(int)autoFetchState;
-(void)_startAutoFetch:(int)arg1 withAccounts:(id)arg2 ;
-(void)lockStateFetch;
-(void)_fetchChangedUids:(id)arg1 forAccount:(id)arg2 options:(int)arg3 ;
-(void)_accountChangedFinished;
-(int)_autoFetchOverrideInterval;
-(id)_invocationWithTarget:(id)arg1 priority:(int)arg2 ;
-(void)_pushFetchCompleted:(id)arg1 ;
-(void)_checkForReachability;
-(void)_checkForWiFi;
-(void)_finishAutoFetch;
-(oneway void)_reportReachabilityTimeout:(id)arg1 ;
-(void)setAutoFetchState:(int)arg1 ;
-(BOOL)_shouldAutoFetchAccount:(id)arg1 whenVisible:(BOOL)arg2 ;
-(void)_createJobList;
-(void)_createJobListFinished:(id)arg1 ;
-(void)_gatherAllFetchJobs;
-(void)_reportSynchronousFetchCompletion:(id)arg1 ;
-(void)_fetchChangedUids:(id)arg1 forAccount:(id)arg2 ;
-(void)_hasWokenUp;
-(oneway void)setDataSource:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(id)copyDiagnosticInformation;
-(void)startup;
-(BOOL)isIdle;
-(void)_reportReachabilityChange:(id)arg1 ;
-(void)_lockStateChanged;
-(void)connectionManager:(id)arg1 handleEvent:(int)arg2 ;
-(void)contentProtectionStateChanged:(int)arg1 previousState:(int)arg2 ;
@end

