/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIBarButtonItem.h>

@interface BarLabelItem : UIBarButtonItem {

	int _itemStyle;

}
+(id)_boldAttributes;
+(id)_defaultAttributes;
-(id)initWithTitle:(id)arg1 width:(double)arg2 style:(int)arg3 ;
-(id)initWithWidth:(double)arg1 style:(int)arg2 ;
-(void)setTitle:(id)arg1 ;
-(id)initWithTitle:(id)arg1 style:(int)arg2 ;
@end

