/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class MFMailMessage;

@interface ConversationStackItem : NSObject <NSCopying> {

	MFMailMessage* _message;
	unsigned long long _index;
	unsigned long long _total;

}
-(id)initWithMessage:(id)arg1 index:(unsigned long long)arg2 total:(unsigned long long)arg3 ;
-(BOOL)isTopmost;
-(unsigned long long)total;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)message;
-(unsigned long long)index;
@end

