/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FavoriteItemSelectionTarget <NSObject>
@required
-(void)setSelectedSourceType:(unsigned long long)arg1;
-(void)selectCombinedMailboxWithType:(int)arg1 animated:(BOOL)arg2;
-(void)selectMailbox:(id)arg1 animated:(BOOL)arg2;
-(void)selectAccount:(id)arg1 animated:(BOOL)arg2;
-(void)selectCombinedInboxWithSourceType:(unsigned long long)arg1 animated:(BOOL)arg2;
-(void)selectMailbox:(id)arg1 andPopToMailboxController:(BOOL)arg2 animated:(BOOL)arg3;
-(void)showVIPSettingsAnimated:(BOOL)arg1;

@end

