/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/FavoriteItem.h>

@interface FavoriteItem_SharedMailbox : FavoriteItem {

	unsigned long long _sourceType;

}

@property (nonatomic,readonly) unsigned long long sourceType;              //@synthesize sourceType=_sourceType - In the implementation block
-(void)wasSelected:(id)arg1 accessoryTapped:(BOOL)arg2 ;
-(id)badgeCountString;
-(id)applicationShortcutIcon;
-(id)persistentIdForMigration;
-(id)defaultIcon;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithDictionary:(id)arg1 ;
-(BOOL)isVisible;
-(id)dictionaryRepresentation;
-(unsigned long long)sourceType;
-(id)displayName;
-(id)initWithSourceType:(unsigned long long)arg1 ;
-(void)configureCell:(id)arg1 ;
@end

