/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FavoriteItem : NSObject {

	unsigned long long _type;
	NSString* _syncKey;
	BOOL _selected;
	BOOL _shouldSync;

}

@property (nonatomic,readonly) unsigned long long type;              //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) BOOL shouldSync;                        //@synthesize shouldSync=_shouldSync - In the implementation block
+(id)itemForAccount:(id)arg1 ;
+(id)itemForUnifiedMailboxWithType:(int)arg1 selected:(BOOL)arg2 ;
+(id)itemForInboxWithAccount:(id)arg1 selected:(BOOL)arg2 ;
+(id)itemForSharedMailboxWithType:(unsigned long long)arg1 selected:(BOOL)arg2 ;
+(id)itemForMailbox:(id)arg1 selected:(BOOL)arg2 ;
+(id)itemFromDictionary:(id)arg1 ;
+(id)itemForOutbox;
+(id)itemForMailbox:(id)arg1 selected:(BOOL)arg2 shouldSync:(BOOL)arg3 ;
+(BOOL)_defaultShouldSync;
-(id)representingMailbox;
-(void)wasSelected:(id)arg1 accessoryTapped:(BOOL)arg2 ;
-(id)badgeCountString;
-(id)applicationShortcutIcon;
-(void)wasAddedToCollection:(id)arg1 ;
-(void)wasRemovedFromCollecion:(id)arg1 ;
-(id)persistentIdForMigration;
-(id)syncValue;
-(void)wasChangedExternally;
-(void)setShouldSync:(BOOL)arg1 ;
-(long long)_defaultCellAccessoryType;
-(id)defaultIcon;
-(id)representingMailboxes;
-(void)dealloc;
-(id)description;
-(id)initWithDictionary:(id)arg1 ;
-(unsigned long long)type;
-(id)initWithType:(unsigned long long)arg1 ;
-(BOOL)isSelected;
-(void)setSelected:(BOOL)arg1 ;
-(BOOL)isVisible;
-(id)dictionaryRepresentation;
-(id)displayName;
-(id)syncKey;
-(BOOL)isDeletable;
-(BOOL)shouldSync;
-(id)account;
-(BOOL)isMovable;
-(void)configureCell:(id)arg1 ;
@end

