/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class CRRecentContactsLibrary;

@interface MailboxFrecencyController : NSObject {

	CRRecentContactsLibrary* _library;

}
+(id)sharedInstance;
-(void)recordEventWithMailboxURLString:(id)arg1 ;
-(id)_rankedMailboxURLs;
-(id)orderedMailboxUidsForAccount:(id)arg1 ;
-(id)orderedArrayOfSources:(id)arg1 ;
-(void)dealloc;
-(id)initWithLibrary:(id)arg1 ;
-(BOOL)shouldHideNotesForAccount:(id)arg1 ;
@end

