/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UITableViewController.h>
#import <UIKit/UINavigationControllerDelegate.h>
#import <MobileMail/MailboxParentPickerSelectionTarget.h>
#import <UIKit/UITextFieldDelegate.h>

@protocol MailboxEditingControllerDelegate;
@class MFMailboxUid, MailAccount, UITableViewCell, MailMailboxGroupedPickerTableCell, NSString;

@interface MailboxEditingController : UITableViewController <UINavigationControllerDelegate, MailboxParentPickerSelectionTarget, UITextFieldDelegate> {

	MFMailboxUid* _mailbox;
	MFMailboxUid* _oldParentMailbox;
	MFMailboxUid* _parentMailbox;
	MailAccount* _account;
	UITableViewCell* _mailboxNameCell;
	UITableViewCell* _deleteMailboxCell;
	MailMailboxGroupedPickerTableCell* _parentMailboxCell;
	id<MailboxEditingControllerDelegate> _delegate;
	BOOL _isDeletingMailbox;
	BOOL _showDeleteButton;

}

@property (nonatomic,retain) MFMailboxUid * mailbox;                                     //@synthesize mailbox=_mailbox - In the implementation block
@property (nonatomic,retain) MFMailboxUid * parentMailbox;                               //@synthesize parentMailbox=_parentMailbox - In the implementation block
@property (nonatomic,retain) MailAccount * account;                                      //@synthesize account=_account - In the implementation block
@property (assign,nonatomic) id<MailboxEditingControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithMailbox:(id)arg1 account:(id)arg2 ;
-(void)keyboardWillChangeFrame:(id)arg1 ;
-(void)_saveButtonClicked:(id)arg1 ;
-(void)_applyChangesAndDismissView;
-(void)_updateParentMailbox;
-(id)_deleteMailboxButtonTableViewCell;
-(void)_confirmDelete:(id)arg1 ;
-(id)deleteMailboxOperation;
-(void)_queueMailboxOperation:(id)arg1 ;
-(id)createMailboxOperation;
-(id)renameMailboxOperation;
-(id)moveMailboxOperation;
-(void)mailboxParentPickerDidSelectMailbox:(id)arg1 ;
-(void)setDelegate:(id<MailboxEditingControllerDelegate>)arg1 ;
-(void)dealloc;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2 ;
-(double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(id<MailboxEditingControllerDelegate>)delegate;
-(BOOL)shouldAutorotate;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)textChanged:(id)arg1 ;
-(void)setMailbox:(MFMailboxUid *)arg1 ;
-(MFMailboxUid *)mailbox;
-(void)_cancelButtonClicked:(id)arg1 ;
-(void)setAccount:(MailAccount *)arg1 ;
-(MailAccount *)account;
-(void)keyboardWillShow:(id)arg1 ;
-(void)keyboardWillHide:(id)arg1 ;
-(void)setParentMailbox:(MFMailboxUid *)arg1 ;
-(MFMailboxUid *)parentMailbox;
@end

