/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UISplitViewController.h>
#import <UIKit/UISplitViewControllerDelegate.h>
#import <UIKit/UISplitViewControllerDelegatePrivate.h>
#import <MobileMail/TransferMailboxPickerDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <MobileMail/MFApplicationSceneActor.h>

@class UIPanGestureRecognizer, UITapGestureRecognizer, UIView, MailNavigationController, MailDetailNavigationController, TransferNavigationController, NSString;

@interface MailSplitViewController : UISplitViewController <UISplitViewControllerDelegate, UISplitViewControllerDelegatePrivate, TransferMailboxPickerDelegate, UIGestureRecognizerDelegate, MFApplicationSceneActor> {

	UIPanGestureRecognizer* _overlaySwipeRecognizer;
	UITapGestureRecognizer* _overlayTapRecognizer;
	unsigned long long _lastGestureRecognized;
	double _panHysteresisHorizontalLocation;
	UIView* _detailDimmingView;
	BOOL _detailDimmed;
	BOOL _primaryHasFocus;
	BOOL _isInEditMode;
	BOOL _overlayGesturesEnabled;
	MailNavigationController* _messageListNavController;
	MailDetailNavigationController* _messageDetailNavController;
	TransferNavigationController* _transferNavigationController;

}

@property (nonatomic,readonly) MailNavigationController * messageListNavController;                      //@synthesize messageListNavController=_messageListNavController - In the implementation block
@property (nonatomic,readonly) MailDetailNavigationController * messageDetailNavController;              //@synthesize messageDetailNavController=_messageDetailNavController - In the implementation block
@property (assign,nonatomic) BOOL overlayGesturesEnabled;                                                //@synthesize overlayGesturesEnabled=_overlayGesturesEnabled - In the implementation block
@property (nonatomic,retain) TransferNavigationController * transferNavigationController;                //@synthesize transferNavigationController=_transferNavigationController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_shouldForwardViewWillTransitionToSize;
-(id)initWithMasterController:(id)arg1 detailController:(id)arg2 ;
-(MailNavigationController *)messageListNavController;
-(MailDetailNavigationController *)messageDetailNavController;
-(BOOL)usePadTransferStyle;
-(void)prepareTransferOfMessages:(id)arg1 options:(int)arg2 animated:(BOOL)arg3 ;
-(void)setPrimaryVisible:(BOOL)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)overlayGesturesEnabled;
-(void)setFocusedViewController:(id)arg1 ;
-(void)cancelTransferOfMessagesAnimated:(BOOL)arg1 ;
-(void)transferMailboxPickerController:(id)arg1 didSelectMailbox:(id)arg2 withMessages:(id)arg3 ;
-(void)transferMailboxPickerControllerDidFinish:(id)arg1 animated:(BOOL)arg2 ;
-(void)transferMailboxPickerController:(id)arg1 animateMessageToPoint:(CGPoint)arg2 inView:(id)arg3 didFinishDelegate:(id)arg4 selector:(SEL)arg5 context:(id)arg6 ;
-(BOOL)isDetailVisible;
-(void)applicationSceneController:(id)arg1 willTransitionToTraitCollection:(id)arg2 withTransitionCoordinator:(id)arg3 ;
-(void)setOverlayGesturesEnabled:(BOOL)arg1 ;
-(void)focusViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)unfocusViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)didBecomeActiveSceneActor;
-(void)_createAndAttachOverlayGestures;
-(void)_swipedBack:(id)arg1 ;
-(void)_tappedDimmingView:(id)arg1 ;
-(void)_slideInOrNavigateBack:(BOOL)arg1 ;
-(BOOL)_swipeRecognizerShouldBegin:(id)arg1 ;
-(BOOL)_tapRecognizerShouldBegin:(id)arg1 ;
-(void)setTransferNavigationController:(id)arg1 animated:(BOOL)arg2 ;
-(void)setTransferNavigationController:(TransferNavigationController *)arg1 ;
-(TransferNavigationController *)transferNavigationController;
-(void)setDetailDimmed:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)dealloc;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(BOOL)_gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2 ;
-(void)applicationWillSuspend;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(BOOL)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3 ;
-(id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2 ;
-(BOOL)_splitViewControllerIsPrimaryVisible:(id)arg1 ;
-(BOOL)_splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3 forRestorationOfCollapsedWhileSuspendedWithPrimaryVisible:(BOOL)arg4 ;
-(void)splitViewController:(id)arg1 willChangeToDisplayMode:(long long)arg2 ;
-(BOOL)isCollapsed;
-(BOOL)_isPortrait;
@end

