/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MCSChange.h>

@protocol MCSAllMessagesOperation;
@class MFMailMessageStore, MCSMessageOperation;

@interface MailAllMessagesChangeSet : MCSChange {

	MFMailMessageStore* _store;
	MCSMessageOperation*<MCSAllMessagesOperation> _operation;

}

@property (nonatomic,readonly) MCSMessageOperation*<MCSAllMessagesOperation> operation;              //@synthesize operation=_operation - In the implementation block
-(id)applyPendingChangeToObjects:(id)arg1 ;
-(id)localizedErrorDescription;
-(id)localizedErrorTitle;
-(id)localizedChangeDescription;
-(long long)localizedChangeDescriptionPriority;
-(BOOL)isRevertible;
-(id)copyChangeSetForFullPath:(id)arg1 ;
-(unsigned long long)adjustUnreadCount:(unsigned long long)arg1 withCriterion:(id)arg2 ;
-(id)initWithMessageStore:(id)arg1 operation:(id)arg2 ;
-(id)stores;
-(void)dealloc;
-(id)description;
-(MCSMessageOperation*<MCSAllMessagesOperation>)operation;
-(BOOL)commit;
-(BOOL)revert;
-(id)accounts;
-(id)URLStrings;
@end

