/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UITableViewCell.h>
#import <MobileMail/MBLSingleMessageClient.h>
#import <MobileMail/MailboxContentTableEntry.h>
#import <MobileMail/MFReclaimable.h>

@class MFMailMessage, UIDateLabel, _MailboxContentViewCellLayoutValues, NSArray, NSString, NSAttributedString, NSMutableArray, _CellStaticView, MessageListStatusIndicatorManager, UILabel, MFSimpleLabel, UIImageView, UIColor, UIView;

@interface MailboxContentViewCell : UITableViewCell <MBLSingleMessageClient, MailboxContentTableEntry, MFReclaimable> {

	MFMailMessage* _message;
	UIDateLabel* _dateLabel;
	_MailboxContentViewCellLayoutValues* _layoutValues;
	NSArray* _highlightedTerms;
	NSString* _address;
	NSString* _subject;
	NSString* _summary;
	NSString* _mailboxName;
	NSAttributedString* _attributedAddress;
	NSAttributedString* _attributedSubject;
	NSAttributedString* _attributedSummary;
	NSRange _firstAddressRange;
	NSRange _firstSubjectRange;
	NSRange _firstSummaryRange;
	double _interval;
	unsigned long long _generationNumber;
	NSString* _bestRecipientString;
	NSArray* _recipientRangeMatches;
	long long _bestMatchLabelType;
	long long _recipientLabelType;
	long long _chevronType;
	NSMutableArray* _viewsToLayoutDuringTransition;
	_CellStaticView* _staticView;
	MessageListStatusIndicatorManager* _statusIndicatorLayoutManager;
	UILabel* _mailboxNameLabel;
	MFSimpleLabel* _addressLabel;
	MFSimpleLabel* _subjectLabel;
	MFSimpleLabel* _summaryLabel;
	UIImageView* _recipientLabelImageView;
	UIImageView* _bestMatchLabelImageView;
	UIImageView* _chevron;
	UIColor* _originalBackgroundColor;
	unsigned _isFlagged : 1;
	unsigned _isUnread : 1;
	unsigned _isReplied : 1;
	unsigned _isForwarded : 1;
	unsigned _isVIP : 1;
	unsigned _isNotify : 1;
	unsigned _isMute : 1;
	unsigned _hasAttachments : 1;
	unsigned _threaded : 1;
	unsigned _removeFromMBL : 1;
	unsigned _needsSummary : 1;
	unsigned _shouldHighlightDate : 1;
	unsigned _preferToOverFrom : 1;
	unsigned _showsBestMatchedAddress : 1;
	BOOL _summaryIsHidden;
	BOOL _subjectIsPresent;
	BOOL _addressIsPresent;
	BOOL _shouldAnnotateReplyOrForward;
	UIView* _contentWrapperView;
	unsigned long long _annotatedRelationshipType;

}

@property (getter=isThreaded,nonatomic,readonly) BOOL threaded; 
@property (assign,nonatomic) BOOL summaryIsHidden;                                      //@synthesize summaryIsHidden=_summaryIsHidden - In the implementation block
@property (assign,nonatomic) BOOL subjectIsPresent;                                     //@synthesize subjectIsPresent=_subjectIsPresent - In the implementation block
@property (assign,nonatomic) BOOL addressIsPresent;                                     //@synthesize addressIsPresent=_addressIsPresent - In the implementation block
@property (assign,nonatomic) BOOL shouldAnnotateReplyOrForward;                         //@synthesize shouldAnnotateReplyOrForward=_shouldAnnotateReplyOrForward - In the implementation block
@property (assign,nonatomic) unsigned long long annotatedRelationshipType;              //@synthesize annotatedRelationshipType=_annotatedRelationshipType - In the implementation block
@property (nonatomic,retain) UIView * contentWrapperView;                               //@synthesize contentWrapperView=_contentWrapperView - In the implementation block
@property (nonatomic,retain) UIColor * originalBackgroundColor;                         //@synthesize originalBackgroundColor=_originalBackgroundColor - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)emptyCaches;
+(double)compactRowHeight;
+(void)invalidateCachedLayoutInformation;
+(double)defaultRowHeight;
-(void)purgeForMemoryReclamation;
-(void)forceSummaryUpdate;
-(void)setHighlightedTerms:(id)arg1 ;
-(void)setShowsBestMatchedAddress:(BOOL)arg1 ;
-(void)setPrefersToOverFrom:(BOOL)arg1 ;
-(void)setShowsAccessory:(BOOL)arg1 svcIsShowingDetail:(BOOL)arg2 ;
-(void)setSummaryIsHidden:(BOOL)arg1 ;
-(void)updateRecipientToCc:(BOOL)arg1 ;
-(void)setShouldHighlightDate:(BOOL)arg1 ;
-(void)setDisplayUnreadDot:(BOOL)arg1 ;
-(void)setDisplayVIP:(BOOL)arg1 ;
-(void)setAddressIsPresent:(BOOL)arg1 ;
-(BOOL)isThreaded;
-(void)previewNewIndicatorAfterSwipeAction:(unsigned long long)arg1 ;
-(id)_dateLabel;
-(void)setMessage:(id)arg1 threaded:(BOOL)arg2 ;
-(void)setHasUnreadMessages:(BOOL)arg1 hasAttachments:(BOOL)arg2 hasFlagged:(BOOL)arg3 hasVIP:(BOOL)arg4 hasNotify:(BOOL)arg5 hasMute:(BOOL)arg6 receivedInterval:(double)arg7 ;
-(void)updateFlagsFromMessage:(id)arg1 ;
-(BOOL)_wantsTallLayout;
-(void)_layoutValuesDidChange;
-(void)_setUpContentWrapperView;
-(void)_animateIndicator:(unsigned long long)arg1 toState:(BOOL)arg2 ;
-(id)_statusIndicatorLayoutManager;
-(void)_animateIndicator:(id)arg1 keyPath:(id)arg2 fromValue:(id)arg3 toValue:(id)arg4 withDuration:(double)arg5 damping:(double)arg6 ;
-(void)layoutStatusIndicatorViews;
-(void)staticViewNeedsDisplay;
-(id)_dateLabelTextColor;
-(void)staticViewNeedsLayout;
-(void)_recalculateAttributedStrings;
-(id)_mailboxNameLabel;
-(id)_addressLabel;
-(id)_subjectLabel;
-(id)_summaryLabel;
-(id)_recipientLabelImageView;
-(id)_bestMatchLabelImageView;
-(id)_chevron;
-(CGRect)rectForDateWithBounds:(CGRect)arg1 ;
-(CGRect)rectForMailboxNameWithBounds:(CGRect)arg1 dateRect:(CGRect)arg2 ;
-(CGRect)rectForAddressWithBounds:(CGRect)arg1 dateRect:(CGRect)arg2 ;
-(CGRect)rectForSubjectWithBounds:(CGRect)arg1 mailboxRect:(CGRect)arg2 ;
-(CGRect)rectForSummaryWithBounds:(CGRect)arg1 ;
-(CGRect)rectForRecipientLabelWithBounds:(CGRect)arg1 ;
-(CGRect)rectForBestMatchLabelWithBounds:(CGRect)arg1 ;
-(CGRect)rectForChevronWithBounds:(CGRect)arg1 ;
-(CGRect)rectForStatusIndicatorViewsWithPrimaryStatusIndicatorImage:(id)arg1 ;
-(double)contentLeftInsetEditing:(BOOL)arg1 ;
-(void)_cancelMessageBodyLoad;
-(void)_updateSummary;
-(void)_requestMessageBodyLoadForMessage:(id)arg1 ;
-(id)_copyAttributedStringWithString:(id)arg1 attributes:(id)arg2 matchRanges:(id)arg3 matchAttributes:(id)arg4 ;
-(NSRange)_focusableRangeWithString:(id)arg1 ranges:(id)arg2 ;
-(id)_addressAttributesWithColor:(id)arg1 ;
-(id)bestRecipientStringWithMatchedRanges:(id*)arg1 labelType:(long long*)arg2 ;
-(BOOL)addressIsPresent;
-(id)_subjectAttributesWithColor:(id)arg1 ;
-(id)_copyAttributedStringWithString:(id)arg1 attributes:(id)arg2 searchTerms:(id)arg3 matchAttributes:(id)arg4 firstHighlightedRange:(NSRange*)arg5 ;
-(BOOL)subjectIsPresent;
-(id)_bodyAttributesWithColor:(id)arg1 ;
-(BOOL)wantsContentsOfType:(int)arg1 ;
-(void)notifyContentsAvailable:(id)arg1 forMessage:(id)arg2 ;
-(void)notifyContentsUnavailableForMessage:(id)arg1 error:(id)arg2 ;
-(void)notifyFullMessageContentsUnavailableForMessage:(id)arg1 error:(id)arg2 ;
-(void)setShowsAccessory:(BOOL)arg1 ;
-(BOOL)isFlagged;
-(BOOL)isUnread;
-(BOOL)isReplied;
-(BOOL)isNotify;
-(void)drawInStaticView:(id)arg1 highlighted:(BOOL)arg2 ;
-(unsigned long long)generationNumberForStaticView:(id)arg1 ;
-(BOOL)isSelectedForStaticView:(id)arg1 ;
-(BOOL)summaryIsHidden;
-(void)setSubjectIsPresent:(BOOL)arg1 ;
-(UIView *)contentWrapperView;
-(void)setContentWrapperView:(UIView *)arg1 ;
-(BOOL)shouldAnnotateReplyOrForward;
-(void)setShouldAnnotateReplyOrForward:(BOOL)arg1 ;
-(unsigned long long)annotatedRelationshipType;
-(void)setAnnotatedRelationshipType:(unsigned long long)arg1 ;
-(double)ordering;
-(void)_significantTimeChange;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(NSString *)description;
-(UIEdgeInsets)edgeInsets;
-(unsigned long long)priority;
-(UIEdgeInsets)layoutMargins;
-(void)layoutMarginsDidChange;
-(id)_scriptingInfo;
-(void)prepareForReuse;
-(void)willTransitionToState:(unsigned long long)arg1 ;
-(void)didTransitionToState:(unsigned long long)arg1 ;
-(id)message;
-(void)setTimeInterval:(double)arg1 ;
-(id)_multiselectBackgroundColor;
-(void)setAddress:(id)arg1 ;
-(void)reconstruct;
-(BOOL)isVIP;
-(void)setOriginalBackgroundColor:(UIColor *)arg1 ;
-(UIColor *)originalBackgroundColor;
-(double)_leftInset;
-(double)_rightInset;
-(void)_invalidateCachedValues;
-(BOOL)isMute;
-(BOOL)isForwarded;
-(void)setMailboxName:(id)arg1 ;
@end

