/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UINavigationController.h>
#import <UIKit/UINavigationControllerDelegate.h>
#import <UIKit/UIImagePickerControllerDelegate.h>

@class NSArray, UITapGestureRecognizer, NSString;

@interface MailNavigationController : UINavigationController <UINavigationControllerDelegate, UIImagePickerControllerDelegate> {

	NSArray* _previousViewControllers;
	BOOL _poppingFromLeft;
	BOOL _transferNavigationControllerShown;
	UITapGestureRecognizer* _navbarDoubleTapRecognizer;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)mf_statusBarSubtitleString;
-(void)removeViewController:(id)arg1 ;
-(BOOL)isPopping;
-(unsigned long long)mf_unreadCountForDisplay;
-(void)resignPreparedForTransferOfMessages:(BOOL)arg1 ;
-(void)showTransferNavigationController:(id)arg1 animated:(BOOL)arg2 ;
-(void)hideTransferNavigationControllerAnimated:(BOOL)arg1 ;
-(void)doubleTappedNavbar:(id)arg1 ;
-(void)pushViewControllersFromLeft:(id)arg1 animated:(BOOL)arg2 ;
-(id)popViewControllersPushedFromLeftAnimated:(BOOL)arg1 ;
-(void)_didPopFromLeft;
-(void)dealloc;
-(id)popViewControllerAnimated:(BOOL)arg1 ;
-(BOOL)shouldAutorotate;
-(void)viewWillAppear:(BOOL)arg1 ;
-(BOOL)_viewControllerUnderlapsStatusBar;
-(void)removeChildViewController:(id)arg1 notifyDidMove:(BOOL)arg2 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)removeChildViewController:(id)arg1 ;
-(id)popToViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)didShowViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2 ;
@end

