/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MailServices/MSEmailModel.h>
#import <libobjc.A.dylib/MFComposeTypeFactoryDelegate.h>

@class NSString, MFComposeBodyField, MFMailAccountProxyGenerator, MFMessageHeaders;

@interface MailServicesComposeDelegate : MSEmailModel <MFComposeTypeFactoryDelegate> {

	NSString* _sendingEmailAddress;
	MFComposeBodyField* _bodyField;
	MFMailAccountProxyGenerator* _accountProxyGenerator;
	MFMessageHeaders* _savedHeaders;

}

@property (nonatomic,retain) MFMessageHeaders * savedHeaders;              //@synthesize savedHeaders=_savedHeaders - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)addInlinedElementToStore:(id)arg1 onlyIfNecessary:(BOOL)arg2 ;
-(void)dealloc;
-(id)attachments;
-(id)sendingEmailAddress;
-(id)sendingAccountProxy;
-(id)bodyField;
-(id)toRecipients;
-(id)ccRecipients;
-(MFMessageHeaders *)savedHeaders;
-(void)setCcRecipients:(id)arg1 ;
-(void)setBccRecipients:(id)arg1 ;
-(void)setSendingEmailAddress:(id)arg1 addIfNotPresent:(BOOL)arg2 ;
-(BOOL)shouldCreateRichTextRepresentation;
-(id)bccRecipients;
-(id)accountProxyGenerator;
-(void)setSavedHeaders:(MFMessageHeaders *)arg1 ;
-(BOOL)hasAnyHiddenTrailingEmptyQuote;
-(void)setToRecipients:(id)arg1 ;
@end

