/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UINavigationController.h>
#import <UIKit/UINavigationControllerDelegate.h>

@class _UIContentUnavailableView, UIView, UIWindow, MailDetailViewController, MessageViewController, NSString;

@interface MailDetailNavigationController : UINavigationController <UINavigationControllerDelegate> {

	_UIContentUnavailableView* _noMessageSelectedView;
	UIView* _frozenContentSnapshotView;
	UIWindow* _snapshotWindow;
	BOOL _inEditMode;
	MailDetailViewController* _stackEditingViewController;

}

@property (nonatomic,readonly) MessageViewController * messageViewController; 
@property (nonatomic,readonly) MailDetailViewController * stackEditingViewController;              //@synthesize stackEditingViewController=_stackEditingViewController - In the implementation block
@property (getter=isInEditMode,nonatomic,readonly) BOOL inEditMode;                                //@synthesize inEditMode=_inEditMode - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(MailDetailViewController *)stackEditingViewController;
-(void)prepareTransferOfMessages:(id)arg1 options:(int)arg2 animated:(BOOL)arg3 ;
-(MessageViewController *)messageViewController;
-(void)resignPreparedForTransferOfMessages:(BOOL)arg1 ;
-(void)freezeContent;
-(void)unfreezeContent;
-(void)bringFrozenViewToFront;
-(void)setBarHidingGesturesEnabled:(BOOL)arg1 ;
-(BOOL)_shouldHideBarsInCurrentLayout;
-(void)setInEditMode:(BOOL)arg1 ;
-(void)dealloc;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)viewWillLayoutSubviews;
-(void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3 ;
-(void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3 ;
-(id)initWithRootViewController:(id)arg1 ;
-(BOOL)isInEditMode;
@end

