/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@protocol MailStatusBarViewDelegate;
@class UIProgressView, MailStatusProgressBarView, MailStatusUpdateView, MailStatusIndeterminateView;

@interface MailStatusBarView : UIView {

	id<MailStatusBarViewDelegate> _delegate;
	UIProgressView* _progressView;
	MailStatusProgressBarView* _progressStatusView;
	MailStatusUpdateView* _updateView;
	MailStatusIndeterminateView* _indeterminateView;
	BOOL _showProgressView;
	unsigned long long _state;

}

@property (assign,nonatomic) unsigned long long state; 
-(void)_addOrRemoveProgressViewIfNecessary;
-(void)_updateFrameForSuperview;
-(void)switchSubviewToView:(id)arg1 showProgress:(BOOL)arg2 ;
-(void)showIndeterminateStatus;
-(void)showProgressBar;
-(void)showUpdateStatus;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setNeedsDisplay;
-(void)setDelegate:(id)arg1 ;
-(void)dealloc;
-(unsigned long long)state;
-(void)setState:(unsigned long long)arg1 ;
-(void)didMoveToSuperview;
-(void)updateForMiniBarState:(BOOL)arg1 ;
@end

