/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UITableViewController.h>
#import <MobileMail/MailboxListViewControllerMailDelegate.h>
#import <MobileMail/EditFavoritesControllerDelegate.h>
#import <MobileMail/FavoriteItemSelectionTarget.h>
#import <MobileMail/MailboxEditingControllerDelegate.h>

@class MailboxListViewControllerMail, FavoriteItem, NSMutableDictionary, NSArray, UIBarButtonItem, NSString;

@interface MailboxPickerController : UITableViewController <MailboxListViewControllerMailDelegate, EditFavoritesControllerDelegate, FavoriteItemSelectionTarget, MailboxEditingControllerDelegate> {

	MailboxListViewControllerMail* _mailboxListViewController;
	FavoriteItem* _lastSelectedItem;
	CGPoint _savedContentOffset;
	NSMutableDictionary* _headerViews;
	NSArray* _watchedMailboxes;
	NSArray* _defaultToolbarItems;
	NSArray* _editingToolbarItems;
	UIBarButtonItem* _composeButton;
	BOOL _viewIsVisible;
	BOOL _isRefreshing;
	BOOL _showingVIPSettings;
	BOOL _showingFavoritesEditor;
	BOOL _showingAddButton;
	unsigned long long _selectedSourceType;

}

@property (assign,nonatomic) unsigned long long selectedSourceType;              //@synthesize selectedSourceType=_selectedSourceType - In the implementation block
@property (assign,nonatomic) BOOL showingVIPSettings;                            //@synthesize showingVIPSettings=_showingVIPSettings - In the implementation block
@property (assign,nonatomic) BOOL showingFavoritesEditor;                        //@synthesize showingFavoritesEditor=_showingFavoritesEditor - In the implementation block
@property (assign,nonatomic) BOOL showingAddButton;                              //@synthesize showingAddButton=_showingAddButton - In the implementation block
@property (assign,nonatomic) BOOL isRefreshing; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setSelectedSourceType:(unsigned long long)arg1 ;
-(void)selectCombinedMailboxWithType:(int)arg1 animated:(BOOL)arg2 ;
-(void)selectMailbox:(id)arg1 animated:(BOOL)arg2 ;
-(void)selectAccount:(id)arg1 animated:(BOOL)arg2 ;
-(id)mailboxListViewController;
-(id)mailboxContentViewController;
-(int)propagateChangeDownwards:(id)arg1 ;
-(void)dismissAndUnfocus;
-(unsigned long long)selectedSourceType;
-(BOOL)containsMultipleAccounts;
-(void)selectCombinedInboxWithSourceType:(unsigned long long)arg1 animated:(BOOL)arg2 ;
-(void)selectMailbox:(id)arg1 andPopToMailboxController:(BOOL)arg2 animated:(BOOL)arg3 ;
-(void)prepareToContinueDisplayingMessage;
-(id)selectedAccounts;
-(void)selectFavoriteItemAtIndexPath:(id)arg1 ;
-(void)pulledToRefresh:(id)arg1 ;
-(void)updateIsRefreshing;
-(void)statusBarProgressDidChange:(id)arg1 ;
-(void)showMailboxEditingControllerWithMailbox:(id)arg1 ;
-(void)newMailboxClicked:(id)arg1 ;
-(void)mailboxEditingControllerDidFinish:(id)arg1 ;
-(void)_flagStyleDidChange:(id)arg1 ;
-(void)_accountsDidChange:(id)arg1 ;
-(void)_vipSendersDidChange:(id)arg1 ;
-(void)_favoritesDidChange:(id)arg1 ;
-(void)_sharedMailboxControllerBadgeCountDidChange:(id)arg1 ;
-(void)_detailViewControllerConfigurationChanged:(id)arg1 ;
-(void)_watchedMailboxesDidChange:(id)arg1 ;
-(BOOL)showingFavoritesEditor;
-(void)_updateSharedMailboxesExposure:(int)arg1 ;
-(void)_setLastSelectedItem:(id)arg1 ;
-(BOOL)showingVIPSettings;
-(void)_updatedSelectedState:(id)arg1 ;
-(void)setShowingVIPSettings:(BOOL)arg1 ;
-(void)setShowingFavoritesEditor:(BOOL)arg1 ;
-(void)_popToMailboxPickerController:(BOOL)arg1 andPushMailboxContentViewControllerIfNecessaryAnimated:(BOOL)arg2 ;
-(BOOL)showingAddButton;
-(void)setShowingAddButton:(BOOL)arg1 ;
-(id)watchedMailboxes;
-(void)_updateCellForSourceType:(id)arg1 ;
-(void)_setBackButtonTitle:(id)arg1 ;
-(void)_updateCheckmarkColor:(id)arg1 ;
-(BOOL)_isAddButton:(id)arg1 indexPath:(id)arg2 ;
-(BOOL)isCellSelectable:(id)arg1 atIndexPath:(id)arg2 ;
-(void)_detailsDisclosureButtonTapped:(id)arg1 ;
-(void)_addFavoriteButtonClicked;
-(void)editFavoritesControllerDidFinish:(id)arg1 ;
-(void)showVIPSettingsAnimated:(BOOL)arg1 ;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 ;
-(void)dealloc;
-(id)init;
-(double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2 ;
-(void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 willDeselectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(void)applicationWillSuspend;
-(BOOL)shouldAutorotate;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)_getRotationContentSettings:(SCD_Struct_Ma3*)arg1 ;
-(BOOL)isRefreshing;
-(void)_significantTimeChange:(id)arg1 ;
-(void)_updateToolbarItems:(BOOL)arg1 ;
-(void)_contentSizeCategoryChanged:(id)arg1 ;
-(void)setIsRefreshing:(BOOL)arg1 ;
@end

