/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIViewController.h>
#import <MobileMail/LoadRequestManagerDelegate.h>
#import <MobileMail/StackDataSource.h>
#import <MobileMail/StackDelegate.h>
#import <MobileMail/MFMessageViewingContextDelegate.h>

@class UIView, UIBarButtonItem, StackController, LoadRequestManager, NSMutableDictionary, MessageViewController, NSString;

@interface MailDetailViewController : UIViewController <LoadRequestManagerDelegate, StackDataSource, StackDelegate, MFMessageViewingContextDelegate> {

	UIView* _currentMessageSnapshotView;
	UIBarButtonItem* _toolbarTransferCancelButton;
	unsigned long long _editingState;
	StackController* _stackController;
	LoadRequestManager* _loadRequestManager;
	NSMutableDictionary* _messageViews;
	BOOL _shouldScrollCurrentMessageToTop;
	BOOL _shouldResnapshotMessageForStack;
	BOOL _useStackViewForTransfer;
	MessageViewController* _messageViewController;

}

@property (nonatomic,retain) MessageViewController * messageViewController;              //@synthesize messageViewController=_messageViewController - In the implementation block
@property (assign,nonatomic) unsigned long long editingState;                            //@synthesize editingState=_editingState - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setMessageViewController:(MessageViewController *)arg1 ;
-(id)mailDetailViewController;
-(void)animateMessageToPoint:(CGPoint)arg1 inView:(id)arg2 didFinishDelegate:(id)arg3 selector:(SEL)arg4 context:(id)arg5 ;
-(void)prepareTransferOfMessages:(id)arg1 options:(int)arg2 animated:(BOOL)arg3 ;
-(MessageViewController *)messageViewController;
-(void)resignPreparedForTransferOfMessages:(BOOL)arg1 ;
-(void)transferCancelButtonClicked:(id)arg1 ;
-(void)removeStackedViews:(BOOL)arg1 ;
-(void)setEditingState:(unsigned long long)arg1 animated:(BOOL)arg2 ;
-(id)titleForCurrentTransferState;
-(id)_toolbarTransferCancelButton;
-(id)_barFixedSpaceWithWidth:(double)arg1 ;
-(id)snapshotOfCurrentMessageWithType:(int)arg1 ;
-(UIEdgeInsets)edgeInsetsForNavbar;
-(unsigned long long)editingState;
-(void)displayStackedViewsForMessages:(id)arg1 options:(int)arg2 animated:(BOOL)arg3 ;
-(id)stackControllerCreateIfNeeded:(BOOL)arg1 ;
-(id)_itemsToStackFromMessages:(id)arg1 options:(int)arg2 withStackController:(id)arg3 ;
-(id)keyForItem:(id)arg1 ;
-(id)loadRequestManager;
-(void)takeSnapshotOfCurrentMessage;
-(void)removeSnapshotOfCurrentMessage;
-(id)defaultViewForStackController:(id)arg1 ;
-(void)updateSnapshotOfCurrentMessage;
-(void)loadRequestManager:(id)arg1 loadItem:(id)arg2 userInfo:(id)arg3 ;
-(id)stackContainerViewForStackController:(id)arg1 ;
-(UIEdgeInsets)stackContainerViewEdgeInsetsForStackController:(id)arg1 ;
-(id)defaultItemForStackController:(id)arg1 ;
-(id)stackController:(id)arg1 viewForItem:(id)arg2 ;
-(BOOL)stackController:(id)arg1 isDataLoadedForItem:(id)arg2 inView:(id)arg3 ;
-(void)stackController:(id)arg1 loadDataForItem:(id)arg2 inView:(id)arg3 ;
-(void)stackControllerWillStartStackingViews:(id)arg1 ;
-(void)stackControllerDidStopStackingViews:(id)arg1 ;
-(void)stackController:(id)arg1 dataLoadTimedOutInView:(id)arg2 forItem:(id)arg3 ;
-(void)stackController:(id)arg1 willStackView:(id)arg2 forItem:(id)arg3 ;
-(void)stackController:(id)arg1 willDisplayView:(id)arg2 forItem:(id)arg3 ;
-(void)stackController:(id)arg1 willRemoveViewForItem:(id)arg2 ;
-(void)setEditingState:(unsigned long long)arg1 ;
-(BOOL)hasSelectedMessages;
-(void)displayStackedViewsForMessages:(id)arg1 animated:(BOOL)arg2 ;
-(void)bufferedMessageViewDidCreateImage:(id)arg1 ;
-(void)suspendLoadManager;
-(void)rescheduleLoadManager;
-(id)_toolbarPopupButton;
-(void)dealloc;
-(id)init;
-(BOOL)shouldAutorotate;
-(void)messageViewingContextContentLoadCompleted:(id)arg1 ;
@end

