/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewDataSource.h>

@protocol MailboxParentPickerSelectionTarget;
@class MFMailboxUid, MailAccount, NSArray, NSString;

@interface MailboxParentPickerTableController : NSObject <UITableViewDataSource> {

	MFMailboxUid* _mailbox;
	MFMailboxUid* _parentMailbox;
	MailAccount* _account;
	NSArray* _sortedMailboxes;
	id<MailboxParentPickerSelectionTarget> _mailboxSelectionTarget;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithMailboxUid:(id)arg1 parentMailbox:(id)arg2 account:(id)arg3 ;
-(void)setMailboxSelectionTarget:(id)arg1 ;
-(long long)indexOfParentMailbox;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 tableViewPath:(id)arg3 ;
-(void)dealloc;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)mailboxForIndexPath:(id)arg1 ;
-(id)indexPathForMailbox:(id)arg1 ;
@end

