/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <MobileMail/MailboxContentViewController.h>
#import <MobileMail/MessageMiniMallObserver.h>
#import <MobileMail/MFSearchSuggestionsControllerDelegate.h>
#import <MobileMail/MFSearchSuggestionsManagerDelegate.h>
#import <MobileMail/MFAtomSearchBarDelegate.h>
#import <MobileMail/MFSearchResultsUpdating.h>

@class MFSearchSuggestionsManager, MFSearchSuggestionsController, MFSpotlightSuggester, NSSet, NSString, SearchScopeControl;

@interface MailboxContentSearchViewController : MailboxContentViewController <MessageMiniMallObserver, MFSearchSuggestionsControllerDelegate, MFSearchSuggestionsManagerDelegate, MFAtomSearchBarDelegate, MFSearchResultsUpdating> {

	MFSearchSuggestionsManager* _suggestionsManager;
	MFSearchSuggestionsController* _suggestionsController;
	MFSpotlightSuggester* _spotlightSuggester;
	NSSet* _alwaysVisibleCategories;
	NSSet* _basicCategories;
	id _suggestionsIdentifier;
	NSString* _lastPhrase;
	SearchScopeControl* _searchGlobalScopeControl;
	NSSet* _mailboxes;
	struct {
		unsigned globalScopeControlDisabled : 1;
		unsigned localMailboxSearchOnly : 1;
		unsigned dismissedSuggestions : 1;
	}  _flags;
	NSSet* _presentingSources;

}

@property (nonatomic,copy) NSSet * presentingSources;                                                      //@synthesize presentingSources=_presentingSources - In the implementation block
@property (assign,getter=isSearchSuggestionsVisible,nonatomic) BOOL searchSuggestionsVisible; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)atomSearchBar;
-(BOOL)_shouldUpdateBarButtons;
-(void)_setInEditMode:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setMailboxes:(id)arg1 ;
-(void)setPresentingSources:(NSSet *)arg1 ;
-(NSSet *)presentingSources;
-(id)selectionModel:(id)arg1 sourcesForMessageInfos:(id)arg2 ;
-(void)miniMallDidFinishSearch:(id)arg1 ;
-(void)globalSearchScopeChanged:(id)arg1 ;
-(void)_updateTableHeaderView;
-(void)_generateSuggestionsForPhrase:(id)arg1 ;
-(id)allExcludedMailboxes;
-(id)excludedMailboxes;
-(id)exclusionPredicate;
-(id)baseSpotlightSuggesterPredicate;
-(BOOL)isSearchSuggestionsVisible;
-(BOOL)_shouldSearchCurrentMailboxOnly;
-(id)localMailboxCriterion;
-(id)basicCategories;
-(BOOL)atomSearchBar:(id)arg1 hasAtomFromCategory:(id)arg2 ;
-(id)basicSearchText;
-(void)setSearchSuggestionsVisible:(BOOL)arg1 ;
-(id)alwaysVisibleCategories;
-(void)getDefaultPersonScopeIdentifier:(id*)arg1 alternativeScopeIdentifier:(id*)arg2 ;
-(BOOL)atomSearchBar:(id)arg1 hasAtomWithSelectedScopeIdentifier:(id)arg2 ;
-(void)noteCriterionUpdated;
-(BOOL)searchSuggestionsController:(id)arg1 shouldShowSuggestionsForCategory:(id)arg2 ;
-(void)searchSuggestionsController:(id)arg1 didSelectSuggestion:(id)arg2 ;
-(void)suggestionsManager:(id)arg1 hasSuggestions:(id)arg2 categories:(id)arg3 forIdentifier:(id)arg4 ;
-(void)suggestionsManager:(id)arg1 finishedWithIdentifier:(id)arg2 ;
-(id)atomSearchBar:(id)arg1 atomViewForRepresentedObject:(id)arg2 ;
-(id)atomSearchBar:(id)arg1 scopeButtonTitlesForRepresentedObject:(id)arg2 ;
-(long long)atomSearchBar:(id)arg1 selectedScopeButtonIndexForRepresentedObject:(id)arg2 ;
-(void)atomSearchBar:(id)arg1 selectedScopeButtonIndexDidChange:(long long)arg2 forRepresentedObject:(id)arg3 ;
-(void)searchButtonTappedForAtomSearchBar:(id)arg1 ;
-(id)supportedPasteboardTypesForAtomSearchBar:(id)arg1 ;
-(id)atomSearchBar:(id)arg1 representedObjectsFromPasteboard:(id)arg2 ;
-(BOOL)atomSearchBar:(id)arg1 storeRepresentedObjects:(id)arg2 onPasteboard:(id)arg3 ;
-(void)dealloc;
-(void)loadView;
-(id)navigationController;
-(id)splitViewController;
-(void)willMoveToParentViewController:(id)arg1 ;
-(id)targetViewControllerForAction:(SEL)arg1 sender:(id)arg2 ;
-(void)setToolbarItems:(id)arg1 animated:(BOOL)arg2 ;
-(id)toolbarItems;
-(void)searchBar:(id)arg1 textDidChange:(id)arg2 ;
-(void)updateSearchResultsForSearchController:(id)arg1 ;
-(id)criterion;
-(id)mailboxes;
-(BOOL)isSearching;
@end

