/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MCSFinalizedObject.h>

@class NSInvocation, NSSet, NSString;

@interface MCSChange : NSObject <MCSFinalizedObject> {

	NSInvocation* _invocation;
	unsigned long long _committedNumber;
	unsigned long long _managerNumber;
	unsigned _isFinalized : 1;
	BOOL _isReverseOperation;

}

@property (assign,nonatomic) BOOL isReverseOperation;               //@synthesize isReverseOperation=_isReverseOperation - In the implementation block
@property (nonatomic,readonly) NSSet * messagesSet; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)isFinalized;
-(id)applyPendingChangeToObjects:(id)arg1 ;
-(id)localizedErrorDescription;
-(id)localizedErrorTitle;
-(id)localizedChangeDescription;
-(long long)localizedChangeDescriptionPriority;
-(NSSet *)messagesSet;
-(BOOL)isRevertible;
-(id)copyChangeSetForFullPath:(id)arg1 ;
-(unsigned long long)adjustUnreadCount:(unsigned long long)arg1 withCriterion:(id)arg2 ;
-(unsigned long long)committedNumber;
-(id)mailboxToRemove;
-(id)modifiedMailboxName;
-(id)mailboxToMoveOrRename;
-(id)mailboxParentForMove;
-(void)setManagerNumber:(unsigned long long)arg1 ;
-(BOOL)isReverseOperation;
-(void)setIsReverseOperation:(BOOL)arg1 ;
-(id)stores;
-(void)dealloc;
-(BOOL)commit;
-(void)setInvocation:(id)arg1 ;
-(id)invocation;
-(BOOL)revert;
-(id)accounts;
-(id)URLStrings;
@end

