/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MCSMailboxOperation.h>

@class NSString, MFMailboxUid;

@interface MCSCreateMailboxOperation : MCSMailboxOperation {

	NSString* _pendingName;
	MFMailboxUid* _parentMailbox;
	NSString* _reasonForFailure;

}

@property (nonatomic,copy) NSString * reasonForFailure;              //@synthesize reasonForFailure=_reasonForFailure - In the implementation block
-(id)localizedErrorDescription;
-(id)localizedErrorTitle;
-(id)accountForErrorHandling;
-(void)setReasonForFailure:(NSString *)arg1 ;
-(id)initWithName:(id)arg1 parentMailbox:(id)arg2 ;
-(NSString *)reasonForFailure;
-(void)dealloc;
-(BOOL)commit;
-(BOOL)revert;
@end

