/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MCSMailboxOperation.h>

@class MFMailboxUid;

@interface MCSDeleteMailboxOperation : MCSMailboxOperation {

	MFMailboxUid* _mailboxToDelete;

}
-(id)localizedErrorDescription;
-(id)localizedErrorTitle;
-(id)mailboxToRemove;
-(id)accountForErrorHandling;
-(void)dealloc;
-(BOOL)commit;
-(BOOL)revert;
-(id)initWithMailboxToDelete:(id)arg1 ;
@end

