/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UITableViewController.h>
#import <libobjc.A.dylib/CNContactViewControllerDelegate.h>
#import <libobjc.A.dylib/EKEventEditViewDelegate.h>
#import <libobjc.A.dylib/EKEventViewDelegate.h>
#import <MobileMail/MFSuggestionHandlingDelegate.h>

@class NSMutableArray, MessageSuggestionSession, MessageCallToAction, NSArray, NSString;

@interface MessageCallsToActionController : UITableViewController <CNContactViewControllerDelegate, EKEventEditViewDelegate, EKEventViewDelegate, MFSuggestionHandlingDelegate> {

	NSMutableArray* _groupTitles;
	NSMutableArray* _groupedCallsToAction;
	MessageSuggestionSession* _suggestionSession;
	MessageCallToAction* _inProgressAction;
	NSArray* _callsToAction;

}

@property (nonatomic,retain) MessageCallToAction * inProgressAction;              //@synthesize inProgressAction=_inProgressAction - In the implementation block
@property (nonatomic,copy) NSArray * callsToAction;                               //@synthesize callsToAction=_callsToAction - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)confirmedAction:(id)arg1 sender:(id)arg2 ;
-(void)ignoredAction:(id)arg1 sender:(id)arg2 ;
-(void)displayMultipleCallsToAction:(id)arg1 sender:(id)arg2 ;
-(NSArray *)callsToAction;
-(id)initWithCallsToAction:(id)arg1 suggestionSession:(id)arg2 ;
-(void)setCallsToAction:(NSArray *)arg1 ;
-(id)_titleForCategory:(long long)arg1 ;
-(void)recalculateCellGroups;
-(void)presentContactViewControllerForAction:(id)arg1 ;
-(void)setInProgressAction:(MessageCallToAction *)arg1 ;
-(void)presentEventViewForAction:(id)arg1 ;
-(void)presentEventEditViewForAction:(id)arg1 ;
-(void)showActionSheetForCanceledEventAction:(id)arg1 ;
-(void)displayEventSuggestion:(id)arg1 ;
-(void)displayContactSuggestion:(id)arg1 ;
-(id)indexPathForAction:(id)arg1 containingGroup:(id*)arg2 ;
-(MessageCallToAction *)inProgressAction;
-(id)initWithCoder:(id)arg1 ;
-(void)dealloc;
-(BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(id)initWithStyle:(long long)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(CGSize)preferredContentSize;
-(void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2 ;
-(BOOL)contactViewController:(id)arg1 shouldPerformDefaultActionForContactProperty:(id)arg2 ;
-(void)eventEditViewController:(id)arg1 didCompleteWithAction:(long long)arg2 ;
-(void)eventViewController:(id)arg1 didCompleteWithAction:(long long)arg2 ;
@end

