/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/MessageConsumer.h>
#import <libobjc.A.dylib/NSProgressReporting.h>

@class SearchOperation, NSProgress, NSMutableArray, NSString;

@interface MessageSearchResultsConsumer : NSObject <MessageConsumer, NSProgressReporting> {

	SearchOperation* _operation;
	NSProgress* _progress;
	unsigned long long _sentBatchCount;
	unsigned long long _nextBatchSize;
	NSMutableArray* _pendingMessages;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (readonly) NSProgress * progress; 
-(void)_sendForcibly:(BOOL)arg1 ;
-(void)dealloc;
-(void)done;
-(NSProgress *)progress;
-(void)newMessagesAvailable:(id)arg1 ;
-(BOOL)shouldCancel;
-(id)initWithOperation:(id)arg1 ;
@end

