/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <MobileMail/MessageStatusIndicatorManager.h>

@class NSMutableArray, NSArray;

@interface MessageListStatusIndicatorManager : MessageStatusIndicatorManager {

	NSMutableArray* _statusIndicatorViews;

}

@property (nonatomic,readonly) NSArray * statusIndicatorViews; 
-(NSArray *)statusIndicatorViews;
-(unsigned long long)tierForIndicator:(unsigned long long)arg1 ;
-(id)primaryStatusIndicatorImage;
-(void)layoutStatusIndicatorViewsInRect:(CGRect)arg1 ;
-(void)_setUpIndicatorViews;
-(void)dealloc;
@end

