/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MessageCallToActionFormatter.h>

@class NSString, NSArray;

@interface MessageCallToActionMixedFormatter : MessageCallToActionFormatter {

	NSString* _title;
	NSString* _subtitle;
	NSArray* _callsToAction;

}

@property (nonatomic,copy) NSArray * callsToAction;              //@synthesize callsToAction=_callsToAction - In the implementation block
-(NSArray *)callsToAction;
-(id)initWithCallsToAction:(id)arg1 ;
-(void)setCallsToAction:(NSArray *)arg1 ;
-(void)_format;
-(id)_titleForCategory:(long long)arg1 ;
-(id)_ordinalForCategory:(long long)arg1 count:(long long)arg2 ;
-(void)dealloc;
-(id)title;
-(long long)accessoryType;
-(id)subtitle;
-(id)actionTitle;
@end

