/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MessageSuggestionBannerViewDelegate <NSObject>
@required
-(id)callsToAction;
-(void)messageSuggestionBanner:(id)arg1 sender:(id)arg2 confirmedAction:(id)arg3;
-(void)messageSuggestionBanner:(id)arg1 sender:(id)arg2 ignoredAction:(id)arg3;
-(void)didSelectMessageSuggestionBanner:(id)arg1 sender:(id)arg2;

@end

