/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>
#import <MobileMail/MFAddressBookClient.h>
#import <MobileMail/MessageSuggestionBannerViewDelegate.h>
#import <libobjc.A.dylib/CNAvatarViewDelegate.h>

@protocol MFMessageContentDisplayDelegate, MFSuggestionHandlingDelegate;
@class MFMessageViewingContext, MailAccount, NSArray, NSSet, NSMutableSet, NSMutableArray, NSMutableDictionary, UIButton, MessageHeaderHeader, MFModernLabelledAtomList, SeparatorLayer, MFMailDropBannerView, MFCaptionLabel, CNContactStore, CNAvatarView, UIView, MessageViewStatusIndicatorManager, MessageSuggestionBannerView, MFMessageDisplayMetrics, NSString;

@interface MessageHeaderLayer : UIView <MFAddressBookClient, MessageSuggestionBannerViewDelegate, CNAvatarViewDelegate> {

	MFMessageViewingContext* _context;
	MailAccount* _account;
	CGSize _oldSize;
	NSArray* _cachedToRecipients;
	NSArray* _cachedCcRecipients;
	NSArray* _cachedBccRecipients;
	NSArray* _cachedSenders;
	NSSet* _cachedReceivingEmailAddresses;
	NSMutableSet* _callsToAction;
	NSMutableArray* _layersToRemoveWhenSmall;
	NSMutableDictionary* _atomListDictionary;
	UIButton* _infoButton;
	MessageHeaderHeader* _header;
	MFModernLabelledAtomList* _primaryField;
	SeparatorLayer* _bannerSeparator;
	MFMailDropBannerView* _mailDropBanner;
	int _displayStyle;
	MFCaptionLabel* _captionLabel;
	CNContactStore* _contactStore;
	CNAvatarView* _avatarView;
	UIView* _avatarTouchPaddingView;
	MessageViewStatusIndicatorManager* _statusIndicatorManager;
	unsigned _showDetails : 1;
	unsigned _enabled : 1;
	unsigned _selected : 1;
	unsigned _isOutgoing : 1;
	unsigned _suggestionBannerVisible : 1;
	BOOL _markedAsUnread;
	BOOL _markedAsFlagged;
	BOOL _senderIsVIP;
	BOOL _isNotifyThread;
	BOOL _isMuteThread;
	BOOL _preventLayout;
	MessageSuggestionBannerView* _suggestionBanner;
	id<MFMessageContentDisplayDelegate> _displayDelegate;
	id<MFSuggestionHandlingDelegate> _suggestionDelegate;
	MFMessageDisplayMetrics* _displayMetrics;

}

@property (nonatomic,retain) MFMessageViewingContext * viewingContext;                                                                      //@synthesize context=_context - In the implementation block
@property (assign,nonatomic) id<MFMessageContentDisplayDelegate> displayDelegate;                                                           //@synthesize displayDelegate=_displayDelegate - In the implementation block
@property (assign,nonatomic) id<MFSuggestionHandlingDelegate> suggestionDelegate;                                                           //@synthesize suggestionDelegate=_suggestionDelegate - In the implementation block
@property (nonatomic,retain) MFMailDropBannerView * mailDropBanner;                                                                         //@synthesize mailDropBanner=_mailDropBanner - In the implementation block
@property (assign,nonatomic) BOOL bottomSeparatorDrawsFlushWithLeadingEdge; 
@property (nonatomic,retain) MailAccount * account;                                                                                         //@synthesize account=_account - In the implementation block
@property (assign,nonatomic) BOOL enabled; 
@property (assign,nonatomic) BOOL preventLayout;                                                                                            //@synthesize preventLayout=_preventLayout - In the implementation block
@property (assign,setter=_setSuggestionBannerVisible:,getter=_suggestionBannerVisible,nonatomic) BOOL suggestionBannerVisible; 
@property (nonatomic,retain) MessageSuggestionBannerView * suggestionBanner;                                                                //@synthesize suggestionBanner=_suggestionBanner - In the implementation block
@property (nonatomic,retain) MFMessageDisplayMetrics * displayMetrics;                                                                      //@synthesize displayMetrics=_displayMetrics - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
-(void)setShowsHeaderDetails:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)clearMessage;
-(void)displayMessage:(id)arg1 withStyle:(int)arg2 ;
-(void)updateForRedisplay;
-(void)viewingContextFinishedLoading:(id)arg1 ;
-(id<MFMessageContentDisplayDelegate>)displayDelegate;
-(void)setDisplayDelegate:(id<MFMessageContentDisplayDelegate>)arg1 ;
-(MFMailDropBannerView *)mailDropBanner;
-(id)initWithFrame:(CGRect)arg1 displayStyle:(int)arg2 ;
-(void)setBottomSeparatorDrawsFlushWithLeadingEdge:(BOOL)arg1 ;
-(void)updateMailDropBannerVisibleAnimated:(BOOL)arg1 ;
-(CGRect)subjectFrame;
-(void)infoButtonClicked:(id)arg1 ;
-(void)_flagStyleDidChange:(id)arg1 ;
-(void)_trustDidChange:(id)arg1 ;
-(void)_accountsDidChange:(id)arg1 ;
-(void)_vipSendersDidChange:(id)arg1 ;
-(void)_invalidateDisplayMetrics;
-(void)setDisplayMetrics:(MFMessageDisplayMetrics *)arg1 ;
-(MFMessageDisplayMetrics *)displayMetrics;
-(void)_updatePrimaryFieldCaption;
-(void)_updateContactPhoto;
-(void)_invalidateAtomsAndContactPhoto;
-(void)_removeDetailLayers;
-(void)_clearStatusIndicators;
-(void)clearSuggestionsBanner;
-(void)_setMailDropBannerVisible:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setMessageFlags:(unsigned long long)arg1 conversationFlags:(unsigned long long)arg2 ;
-(id)_arrangedRecipients:(id)arg1 withReceivingEmailAddresses:(id)arg2 ;
-(void)recipientAtomPressed:(id)arg1 ;
-(void)senderAtomPressed:(id)arg1 ;
-(void)_updatePrimaryFieldUI;
-(void)createInfoButtonWithTitle:(id)arg1 ;
-(void)_setShowDetails:(BOOL)arg1 animate:(BOOL)arg2 force:(BOOL)arg3 ;
-(void)updateInfoButton;
-(void)_updateAtomStyles;
-(void)addSuggestionsBannerForCallsToAction:(id)arg1 animated:(BOOL)arg2 ;
-(void)_setSuggestionBannerVisible:(BOOL)arg1 ;
-(double)atomListLineSpacing;
-(void)_updateVIPStatus;
-(void)allowUnreadStateToBeShown;
-(BOOL)preventLayout;
-(BOOL)_suggestionBannerVisible;
-(MessageSuggestionBannerView *)suggestionBanner;
-(void)_updateContactPhotoViewAlpha;
-(BOOL)_captionLabelIsVisible;
-(CGRect)_layoutStatusIndicators;
-(BOOL)canShowMarkButton;
-(void)updateForRedisplayWithStatusIndicatorsVisible:(BOOL)arg1 ;
-(void)updateDateAndTime;
-(void)_addDetailLayers;
-(void)_sendAction:(SEL)arg1 forAddressAtom:(id)arg2 ;
-(BOOL)bottomSeparatorDrawsFlushWithLeadingEdge;
-(void)setPreventLayout:(BOOL)arg1 ;
-(void)_headerAnimationDidStop;
-(void)_headerHeightDidChangeAfterAnimation:(BOOL)arg1 ;
-(id)_addAddressListWithAddresses:(id)arg1 label:(id)arg2 title:(id)arg3 maxWidth:(double)arg4 action:(SEL)arg5 ;
-(void)_setSuggestionBannerVisible:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)_setSuggestionBannerVisible:(BOOL)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)setSuggestionBanner:(MessageSuggestionBannerView *)arg1 ;
-(void)clearSuggestionsBanner:(BOOL)arg1 ;
-(BOOL)_atomContainsVIPSender:(id)arg1 ;
-(id)callsToAction;
-(void)messageSuggestionBanner:(id)arg1 sender:(id)arg2 confirmedAction:(id)arg3 ;
-(void)messageSuggestionBanner:(id)arg1 sender:(id)arg2 ignoredAction:(id)arg3 ;
-(void)didSelectMessageSuggestionBanner:(id)arg1 sender:(id)arg2 ;
-(id)htmlRepresentationLeavingSpaceForPhoto:(BOOL)arg1 ;
-(id)displayedContact;
-(void)reloadSuggestionsBanner;
-(void)setMailDropBanner:(MFMailDropBannerView *)arg1 ;
-(BOOL)enabled;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)setEnabled:(BOOL)arg1 ;
-(void)layoutMarginsDidChange;
-(void)tintColorDidChange;
-(void)_fontSizeDidChange:(id)arg1 ;
-(MFMessageViewingContext *)viewingContext;
-(void)addressBookManager:(id)arg1 addressBookDidChange:(void*)arg2 ;
-(void)addressBookPreferencesChangedForAddressBookManager:(id)arg1 ;
-(void)setAccount:(MailAccount *)arg1 ;
-(MailAccount *)account;
-(id)bottomSeparator;
-(id)presentingViewControllerForAvatarView:(id)arg1 ;
-(id)avatarView;
-(void)setViewingContext:(MFMessageViewingContext *)arg1 ;
-(void)setSuggestionDelegate:(id<MFSuggestionHandlingDelegate>)arg1 ;
-(id<MFSuggestionHandlingDelegate>)suggestionDelegate;
@end

