/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:43:59 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MessageMiniMallObserver
@required
-(void)miniMallMessageCountWillChange:(id)arg1;
-(void)miniMallMessageCountDidChange:(id)arg1;
-(void)miniMallMessagesAtIndexPathsChanged:(id)arg1;
-(void)miniMallStartFetch:(id)arg1;
-(void)miniMallFinishedFetch:(id)arg1;
-(void)miniMallCurrentMessageRemoved:(id)arg1;
-(void)miniMallDidLoadMessages:(id)arg1;
-(void)miniMallGrowingMailboxesChanged:(id)arg1;
-(void)miniMallDidFinishSearch:(id)arg1;

@end

