/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MessageCallToActionFormatter.h>

@class MessageCallToActionRealtimeContact;

@interface MessageCallToActionRealtimeContactFormatter : MessageCallToActionFormatter {

	MessageCallToActionRealtimeContact* _callToAction;

}

@property (nonatomic,retain) MessageCallToActionRealtimeContact * callToAction;              //@synthesize callToAction=_callToAction - In the implementation block
-(id)initWithCallsToAction:(id)arg1 ;
-(id)_realtimeContact;
-(MessageCallToActionRealtimeContact *)callToAction;
-(void)setCallToAction:(MessageCallToActionRealtimeContact *)arg1 ;
-(void)dealloc;
-(id)title;
-(id)subtitle;
-(id)actionTitle;
@end

