/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/MFDiagnosticsGenerator.h>
#import <MobileMail/MessageBodyLoader.h>

@protocol MessageBodyLoader
@required
-(oneway void)beginAddingNewMessagesForStore:(id)arg1;
-(oneway void)disableNetworkFetching;
-(oneway void)enableNetworkFetching;
-(oneway void)addSingleMessageClient:(id)arg1;
-(oneway void)removeSingleMessageClient:(id)arg1;
-(oneway void)stopAddingNewMessagesForStore:(id)arg1;
-(oneway void)userViewingMessages:(id)arg1;
-(oneway void)userStoppedViewingMessages;
-(oneway void)resume;
-(oneway void)pause;
-(oneway void)addMessage:(id)arg1;
-(oneway void)addMessages:(id)arg1;

@end

#import <MobileMail/MFPowerObserver.h>

@protocol OS_dispatch_queue, OS_dispatch_semaphore;
@class NSMutableArray, NSMutableSet, NSCountedSet, MFActivityMonitor, NSObject, NSDate, NSMutableDictionary, NSString;

@interface MessageBodyLoader : NSObject <MFDiagnosticsGenerator, MessageBodyLoader, MFPowerObserver> {

	NSMutableArray* _clients;
	NSMutableArray* _newMessages;
	NSMutableSet* _newMessageSet;
	NSCountedSet* _newMessageMailboxQuota;
	NSMutableArray* _userViewingMessages;
	MFActivityMonitor* _currentMonitor;
	NSCountedSet* _watchedUids;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	NSObject*<OS_dispatch_semaphore> _waitReply;
	int _noNetworkFetching;
	int _isPaused;
	NSDate* _resumeTime;
	unsigned _isRunning : 1;
	unsigned _isWaitingForTask : 1;
	unsigned _shouldProcessQueues : 1;
	unsigned _holdingPowerAssertion : 1;
	NSMutableDictionary* _bytesPerAccount;

}

@property (readonly) BOOL isPaused; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)_setSharedLoaderForTesting:(id)arg1 ;
+(id)copySummaryForMessage:(id)arg1 downloadIfNecessary:(BOOL)arg2 ;
+(void)applicationWillSuspend;
+(id)sharedLoader;
+(void)applicationWillResume;
+(void)startup;
-(oneway void)beginAddingNewMessagesForStore:(id)arg1 ;
-(void)_messagesAdded:(id)arg1 ;
-(void)_messageFlagsChanged:(id)arg1 ;
-(oneway void)disableNetworkFetching;
-(oneway void)enableNetworkFetching;
-(oneway void)addSingleMessageClient:(id)arg1 ;
-(oneway void)removeSingleMessageClient:(id)arg1 ;
-(void)_messagesWillBeCompacted:(id)arg1 ;
-(void)_setIsRunning:(BOOL)arg1 ;
-(void)_finishedCullingMessageList:(id)arg1 ;
-(void)_getNextClientOrMessage;
-(void)_getNextClientOrMessageFinished:(id)arg1 ;
-(void)_recordStats:(id)arg1 ;
-(void)_tryProcessingQueues;
-(void)_clientLoadFinished:(id)arg1 ;
-(void)_messageLoadFinished:(id)arg1 ;
-(oneway void)addMessages_nts:(id)arg1 ;
-(void)_removeNewMessages_nts:(id)arg1 ;
-(void)_nts_insertClient:(id)arg1 ;
-(void)_nts_removeClient:(id)arg1 ;
-(void)_blockingMessage;
-(void)_retainPowerAssertion;
-(void)_logStats:(BOOL)arg1 ;
-(void)_cancelSleepIfNeeded;
-(void)_clearResumeTime;
-(oneway void)stopAddingNewMessagesForStore:(id)arg1 ;
-(oneway void)userViewingMessages:(id)arg1 ;
-(oneway void)userStoppedViewingMessages;
-(BOOL)networkFetchingAllowed;
-(void)_removeNewMessages:(id)arg1 ;
-(void)_removeViewingMessages:(id)arg1 ;
-(void)_waitUntilNotRunning;
-(void)_releasePowerAssertion;
-(void)dealloc;
-(id)init;
-(void)applicationWillSuspend;
-(void)_start;
-(oneway void)resume;
-(BOOL)_isRunning;
-(oneway void)pause;
-(oneway void)addMessage:(id)arg1 ;
-(id)copyDiagnosticInformation;
-(void)applicationWillResume;
-(void)assertionDidExpire;
-(oneway void)startup;
-(BOOL)isPaused;
-(void)systemWillSleep;
-(void)systemDidWake;
-(oneway void)addMessages:(id)arg1 ;
@end

