/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MessageSuggestionUtilities : NSObject
+(void)requestEventEditingControllerForRealtimeEvent:(id)arg1 inEventStore:(id)arg2 completion:(/*^block*/id)arg3 ;
+(id)confirmationForCanceledEvent:(id)arg1 handler:(/*^block*/id)arg2 ;
+(void)ignoreAction:(id)arg1 ;
+(id)iconStackImageForCallsToAction:(id)arg1 ;
+(void)requestEventEditingControllerForRealtimeEvent:(id)arg1 completion:(/*^block*/id)arg2 ;
@end

