/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MessageSelectionDataSource <NSObject>
@required
-(unsigned long long)flattenedIndexOfMessage:(id)arg1;
-(unsigned long long)localMessageCount;
-(id)messageForMessageInfo:(id)arg1;
-(BOOL)allSourcesThreadMessages;
-(id)messageToSelectFromMessage:(id)arg1 withDirection:(int)arg2;
-(/*^block*/id)comparatorForMallContainingMessage:(id)arg1;
-(int)lastChangeDirection;
-(unsigned long long)flattenedIndexOfWhereMessageShouldGo:(id)arg1;
-(id)messageAtFlattenedIndex:(unsigned long long)arg1;
-(id)conversationContainingMessage:(id)arg1;
-(/*^block*/id)comparator;

@end

