/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MessageFoldViewDelegate <NSObject>
@optional
-(void)messageFoldView:(id)arg1 didUpdateFoldWithProgress:(double)arg2 fadeInAlpha:(double)arg3;

@end

