/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <libobjc.A.dylib/MFDiagnosticsGenerator.h>
#import <MobileMail/MessageSelectionDataSource.h>
#import <MobileMail/MiniMallSourceBulkOperationsDelegate.h>

@protocol OS_dispatch_queue;
@class NSObject, NSMutableSet, MFMessageInfoOrderedSet, NSCache, MFActivityMonitor, NSDictionary, MessageSelectionStrategy, MFMailMessage, SourceSearchContext, NSString;

@interface MessageMiniMall : NSObject <MFDiagnosticsGenerator, MessageSelectionDataSource, MiniMallSourceBulkOperationsDelegate> {

	int _suspendCount;
	NSObject*<OS_dispatch_queue> _queue;
	NSMutableSet* _sources;
	NSMutableSet* _emptiedSources;
	CFDictionaryRef _conversations;
	MFMessageInfoOrderedSet* _messageInfoSet;
	NSCache* _sendersByConversation;
	unsigned long long _threadedMessageCount;
	MFActivityMonitor* _fetchActivity;
	BOOL _userRefresh;
	NSDictionary* _maximumIndexPathsBySource;
	CFDictionaryRef _sourceShouldGrowCache;
	CFDictionaryRef _growingMailboxesByActivity;
	MessageSelectionStrategy* _selectionStrategy;
	MFMailMessage* _currentMessage;
	int _lastChangeDirection;
	SourceSearchContext* _searchContext;
	/*^block*/id _comparator;
	id _context;

}

@property (nonatomic,copy) id comparator;                                    //@synthesize comparator=_comparator - In the implementation block
@property (nonatomic,retain) MFMailMessage * currentMessage; 
@property (nonatomic,retain) MFMailMessage * lastViewedMessage; 
@property (assign,nonatomic) int lastChangeDirection; 
@property (copy) SourceSearchContext * searchContext; 
@property (nonatomic,retain) id context;                                     //@synthesize context=_context - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(/*^block*/id)messageInfosTransformForConversationID:(long long)arg1 ;
-(unsigned long long)threadedCount;
-(id)fetchActivity;
-(void)removeAllSources;
-(id)bulletinsContexts;
-(unsigned long long)messageCountForConversationWithMessage:(id)arg1 ;
-(unsigned long long)unreadCountForDisplay;
-(void)loadMoreMessagesWithMaxVisibleIndexPath:(id)arg1 ;
-(id)tableIndexPathOfConversationContainingMessage:(id)arg1 ;
-(id)tableIndexPathOfConversationWithID:(long long)arg1 ;
-(unsigned long long)flattenedIndexOfMessage:(id)arg1 ;
-(BOOL)shouldPopOnZeroMessages;
-(id)tableIndexPathOfMessage:(id)arg1 ;
-(void)setLastViewedMessage:(MFMailMessage *)arg1 ;
-(id)tableIndexPathOfMessageOrConversation:(id)arg1 ;
-(BOOL)archivesByDefault;
-(BOOL)deleteMovesToTrash;
-(id)sourceForMailbox:(id)arg1 ;
-(void)markAllMessagesAsDeletedOrArchived:(unsigned long long)arg1 ;
-(id)messageToSelectAfterDeletedMessage:(id)arg1 ;
-(void)markMessages:(id)arg1 asDeletedOrArchived:(unsigned long long)arg2 ;
-(id)copyAllMessages;
-(void)markAllMessagesAsViewed;
-(void)markAllMessagesAsNotViewed;
-(void)markMessagesAsViewed:(id)arg1 ;
-(void)markMessagesAsNotViewed:(id)arg1 ;
-(void)markAllMessagesAsFlagged;
-(void)markAllMessagesAsNotFlagged;
-(void)markMessagesAsFlagged:(id)arg1 ;
-(void)markMessagesAsNotFlagged:(id)arg1 ;
-(void)markMessagesAsJunk:(id)arg1 ;
-(void)markMessagesAsNotJunk:(id)arg1 ;
-(void)moveAllMessagesToMailbox:(id)arg1 ;
-(void)transferMessages:(id)arg1 toMailbox:(id)arg2 ;
-(id)messageToSelectAfterDeletedMessages:(id)arg1 ;
-(id)sourcesForMessagesAtTableIndexPath:(id)arg1 ;
-(id)messageAtTableIndexPath:(id)arg1 ;
-(id)titleWithUnreadCount:(unsigned long long)arg1 options:(unsigned long long)arg2 ;
-(BOOL)shouldShowUnreadCount;
-(id)currentRemoteIDForMailbox:(id)arg1 ;
-(void)trackFetchVisibleMailbox:(id)arg1 activity:(id)arg2 options:(unsigned long long)arg3 ;
-(id)messagesAtTableIndexPath:(id)arg1 ;
-(unsigned long long)localMessageCount;
-(BOOL)shouldShowEmptyMailboxString;
-(id)emptyMailboxString;
-(unsigned long long)messageCountInSection:(long long)arg1 ;
-(void)updateEntry:(id)arg1 atTableIndexPath:(id)arg2 addressList:(id*)arg3 options:(unsigned long long)arg4 ;
-(id)messagesForConversationWithID:(long long)arg1 ;
-(MFMailMessage *)lastViewedMessage;
-(id)messageForMessageID:(id)arg1 ;
-(id)defaultMessageIncludingUnread:(BOOL)arg1 ;
-(id)tableIndexPathOfConversationContainingMessageInfo:(id)arg1 ;
-(id)messageForMessageInfo:(id)arg1 ;
-(id)messageInfosAtTableIndexPath:(id)arg1 ;
-(BOOL)deleteMovesToTrashForTableIndexPath:(id)arg1 ;
-(BOOL)supportsArchivingForTableIndexPath:(id)arg1 ;
-(BOOL)shouldArchiveByDefaultForTableIndexPath:(id)arg1 ;
-(void)getConversationStateAtTableIndexPath:(id)arg1 hasUnread:(BOOL*)arg2 hasUnflagged:(BOOL*)arg3 ;
-(void)getSourceStateHasUnread:(BOOL*)arg1 hasUnflagged:(BOOL*)arg2 ;
-(unsigned long long)messageCountAtTableIndexPath:(id)arg1 ;
-(void)_messagesAdded:(id)arg1 ;
-(void)_cancelGrowingMailboxes;
-(void)_protectedDataWillBecomeUnavailable:(id)arg1 ;
-(void)_protectedDataWasReconciled:(id)arg1 ;
-(void)_messageFlagsChanged:(id)arg1 ;
-(void)_messagesCompacted:(id)arg1 ;
-(void)_checkServerCount:(id)arg1 ;
-(void)_conversationHasMerged:(id)arg1 ;
-(void)_sourceDidReload:(id)arg1 ;
-(void)_sourceDidFinishSearch:(id)arg1 ;
-(void)_invalidateMaximumIndexPathsBySource;
-(void)_purgeCachedMessageInfosWithReason:(id)arg1 ;
-(void)_fetchCompleted:(id)arg1 ;
-(void)_notifyGrowingMailboxesChanged;
-(void)_clearFetchActivity;
-(void)_checkForNewMailAndNotifyOnFailure:(BOOL)arg1 ;
-(void)_checkForNewMailAndNotifyOnFailureBackground:(BOOL)arg1 userRefresh:(BOOL)arg2 foregroundRequest:(BOOL)arg3 sourcesToCheck:(id)arg4 remoteID:(id)arg5 ;
-(BOOL)_nts_isGrowingFetchWindowForAnySource;
-(id)_nts_growingMailboxActivityMonitorForSource:(id)arg1 ;
-(id)tableIndexPathOfOldestMessageInSource:(id)arg1 ;
-(BOOL)shouldGrowFetchWindowForSource:(id)arg1 ;
-(BOOL)isGrowingFetchWindowForSource:(id)arg1 ;
-(void)loadOlderMessages;
-(void)growFetchWindowForSources:(id)arg1 ;
-(id)maximumIndexPathsBySource;
-(void)_loadMoreMessagesWithMaxVisibleIndexPath:(id)arg1 maximumIndexPathsBySource:(id)arg2 ;
-(void)_scheduleEnsureWeHaveLoadedMessages;
-(unsigned long long)_messageInfoIndexForIndexPath:(id)arg1 ;
-(BOOL)ensureWeHaveLoadedMessages;
-(BOOL)allSourcesThreadMessages;
-(id)_conversationWithID:(long long)arg1 ;
-(id)_messageForMessageInfo:(id)arg1 cache:(BOOL)arg2 ;
-(CFDictionaryRef)copySendersByLibraryIDForConversation:(long long)arg1 ;
-(id)_messageInfoAtIndexPath:(id)arg1 ;
-(void)_nts_getConversationStateFromNewestMessageInfo:(id)arg1 shouldThread:(BOOL)arg2 hasUnread:(BOOL*)arg3 hasUnflagged:(BOOL*)arg4 ;
-(id)_sourceForMessageInfo:(id)arg1 ;
-(id)tableIndexPathOfMessageInfo:(id)arg1 ;
-(id)_indexPathForMessageInfoIndex:(unsigned long long)arg1 ;
-(id)_copySources;
-(id)messageInfosForConversationID:(long long)arg1 ;
-(id)messageInfosIncludingDuplicateForMessageInfos:(id)arg1 ;
-(id)_tableIndexPathOfMessageOrConversationForInfo:(id)arg1 conversationMustContainMessage:(BOOL)arg2 ;
-(id)messageToSelectFromMessage:(id)arg1 withDirection:(int)arg2 ;
-(void)getLastViewedMessage:(id*)arg1 date:(id*)arg2 ;
-(BOOL)isInCombinedMailboxOfType:(int)arg1 ;
-(BOOL)areAnySourcesSearching;
-(id)messagesIncludingDuplicateForMessages:(id)arg1 ;
-(id)junkMailboxMessagesInMessages:(id)arg1 ;
-(void)_addChangeSetToManager:(id)arg1 ;
-(id)_removeMessages:(id)arg1 ;
-(void)_filterTaskCompletedWithContext:(id)arg1 ;
-(id)_indexPathsFromIndexes:(id)arg1 ;
-(void)_applyOperation:(id)arg1 onMessages:(id)arg2 ;
-(void)_synchronouslyFilterMessages:(id)arg1 fromSource:(id)arg2 operation:(unsigned long long)arg3 ;
-(void)enqueueWork:(/*^block*/id)arg1 ;
-(id)_copyAllMessageInfos;
-(id)_cachedMessageForMessageInfo:(id)arg1 ;
-(id)_conversationWithID:(long long)arg1 createIfNeeded:(BOOL)arg2 ;
-(BOOL)_loadMessages;
-(void)_loadThreadedMessages:(id)arg1 ;
-(void)_loadNonThreadedMessages:(id)arg1 ;
-(id)_addMessages:(id)arg1 ;
-(void)_currentMessageRemovedWithMessageToSelect:(id)arg1 ;
-(CFDictionaryRef)_copyMessageInfosBySourceForTableIndexPath:(id)arg1 ;
-(BOOL)_hasOnlyThreadedSources;
-(/*^block*/id)comparatorForMallContainingMessage:(id)arg1 ;
-(int)lastChangeDirection;
-(unsigned long long)flattenedIndexOfWhereMessageShouldGo:(id)arg1 ;
-(id)messageAtFlattenedIndex:(unsigned long long)arg1 ;
-(id)conversationContainingMessage:(id)arg1 ;
-(void)didDeleteAllMessagesInSource:(id)arg1 ;
-(void)checkForNewMailAndNotifyOnFailure:(BOOL)arg1 userRefresh:(BOOL)arg2 ;
-(BOOL)isGrowingFetchWindowForAnySource;
-(void)getIndex:(unsigned long long*)arg1 andCount:(unsigned long long*)arg2 ofMessageInConversation:(id)arg3 ;
-(void)setLastChangeDirection:(int)arg1 ;
-(id)startSearchWithContext:(id)arg1 ;
-(BOOL)deleteMovesToTrashForMessage:(id)arg1 ;
-(BOOL)supportsArchivingForMessage:(id)arg1 ;
-(BOOL)archiveByDefaultForMessage:(id)arg1 ;
-(BOOL)isInCombinedInbox;
-(id)comparator;
-(void)dealloc;
-(id)init;
-(unsigned long long)numberOfSections;
-(void)applicationWillSuspend;
-(void)addObserver:(id)arg1 ;
-(void)applicationDidResume;
-(void)suspend;
-(void)removeObserver:(id)arg1 ;
-(id)context;
-(void)resume;
-(void)setContext:(id)arg1 ;
-(unsigned long long)sourceType;
-(unsigned long long)messageCount;
-(id)sources;
-(void)addSource:(id)arg1 ;
-(SourceSearchContext *)searchContext;
-(void)setSearchContext:(SourceSearchContext *)arg1 ;
-(MFMailMessage *)currentMessage;
-(unsigned long long)serverMessageCount;
-(BOOL)supportsArchiving;
-(id)copyDiagnosticInformation;
-(void)setCurrentMessage:(MFMailMessage *)arg1 ;
-(void)flushCaches;
-(id)initWithObserver:(id)arg1 ;
-(void)setComparator:(id)arg1 ;
@end

