/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MessageStatusIndicatorManager : NSObject {

	unsigned long long _indicatorOptions;
	unsigned long long _disabledIndicatorOptions;

}

@property (assign,nonatomic) BOOL hidesUnreadIndicator; 
@property (assign,nonatomic) BOOL hidesVIPIndicator; 
@property (assign,nonatomic) BOOL hidesAttachmentIndicator; 
@property (assign,nonatomic) unsigned long long indicatorOptions;                         //@synthesize indicatorOptions=_indicatorOptions - In the implementation block
@property (nonatomic,readonly) unsigned long long effectiveIndicatorOptions; 
+(id)flagShapeImage;
+(id)dotIndicatorImage;
+(id)unreadFlaggedImageWithUnreadColor:(id)arg1 flaggedColor:(id)arg2 ;
+(void)initialize;
-(unsigned long long)effectiveIndicatorOptions;
-(id)statusIndicatorImageWithOptionsMask:(unsigned long long)arg1 ;
-(void)setHidesUnreadIndicator:(BOOL)arg1 ;
-(void)setIndicatorOptions:(unsigned long long)arg1 ;
-(BOOL)hidesUnreadIndicator;
-(void)_setIndicatorOptions:(unsigned long long)arg1 disabled:(BOOL)arg2 ;
-(BOOL)_indicatorOptionsAreDisabled:(unsigned long long)arg1 ;
-(unsigned long long)indicatorOptions;
-(void)setHidesAttachmentIndicator:(BOOL)arg1 ;
-(BOOL)hidesAttachmentIndicator;
-(id)statusIndicatorImageWithOptions:(unsigned long long)arg1 ;
-(BOOL)hidesVIPIndicator;
-(void)setHidesVIPIndicator:(BOOL)arg1 ;
@end

