/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:43:59 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MessageStatusIndicatorManager.h>

@class NSMutableArray, NSArray;

@interface MessageViewStatusIndicatorManager : MessageStatusIndicatorManager {

	NSMutableArray* _statusIndicatorImageViews;
	unsigned long long _statusIndicatorImageViewsSize;

}

@property (nonatomic,readonly) NSArray * statusIndicatorImageViews; 
-(void)updateImageViews;
-(NSArray *)statusIndicatorImageViews;
-(void)dealloc;
@end

