/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MFMailService.h>

@class NSString;

@interface MFAccountsRemovalService : NSObject <MFMailService>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)requiredEntitlement;
+(BOOL)handleMessage:(id)arg1 connectionState:(id)arg2 replyObject:(id*)arg3 error:(id*)arg4 ;
+(void)_deleteAccount:(id)arg1 ;
+(id)serviceName;
@end

