/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, MFActorItemSnapshotCacheDelegate;
@class NSMutableDictionary, NSObject, NSOrderedSet;

@interface MFActorItemSnapshotCache : NSObject {

	NSMutableDictionary* _snapshotItems;
	NSObject*<OS_dispatch_queue> _snapshotUpdateQueue;
	NSOrderedSet* _identifiersToCache;
	long long _capacity;
	id<MFActorItemSnapshotCacheDelegate> _delegate;

}

@property (nonatomic,copy) NSOrderedSet * identifiersToCache;                            //@synthesize identifiersToCache=_identifiersToCache - In the implementation block
@property (assign,nonatomic) long long capacity;                                         //@synthesize capacity=_capacity - In the implementation block
@property (assign,nonatomic) id<MFActorItemSnapshotCacheDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(unsigned long long)maximumSnapshotCacheCapacity;
+(void)removeSavedSnapshotsKeepingSnapshotsWithIdentifiers:(id)arg1 ;
-(void)evictSnapshotItemsIfNecessary;
-(void)invalidateSnapshotItemNow:(BOOL)arg1 withIdentifier:(id)arg2 ;
-(void)setIdentifiersToCache:(NSOrderedSet *)arg1 ;
-(void)requestSnapshotItemWithIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(BOOL)ensureSnapshotIsValidForItemWithIdentifier:(id)arg1 ;
-(void)_asynchronouslyDetermineInitialStateForIdentifier:(id)arg1 ;
-(id)_fetchSavedSnapshotImageFromDiskWithIdentifier:(id)arg1 ;
-(long long)_remainingCapacity;
-(id)_fetchUpdatedSnapshotForItemWithIdentifier:(id)arg1 ;
-(void)_saveSnapshotForIdentifier:(id)arg1 ;
-(NSOrderedSet *)identifiersToCache;
-(void)setCapacity:(long long)arg1 ;
-(void)setDelegate:(id<MFActorItemSnapshotCacheDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<MFActorItemSnapshotCacheDelegate>)delegate;
-(void)_didReceiveMemoryWarning:(id)arg1 ;
-(long long)capacity;
@end

