/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MFApplicationShortcutProvider : NSObject
-(void)_favoritesDidChange:(id)arg1 ;
-(void)_updateApplicationShortcuts;
-(void)_unreadCountDidChange:(id)arg1 ;
-(id)fixedShortcutItems;
-(id)_applicationShortcutForFavoriteItem:(id)arg1 ;
-(void)dealloc;
-(id)init;
@end

