/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MFAttachmentHandlingDelegate <NSObject>
@required
-(void)showSelectedAttachment:(id)arg1;
-(void)showMenuForSelectedAttachment:(id)arg1;
-(BOOL)canSaveAllAttachmentsInContext:(int)arg1;
-(id)localizedTitleForSaveAllAttachmentsAction;
-(void)saveAllAttachments;
-(void)launchMarkupReplyWithAttachment:(id)arg1;
-(BOOL)isAllowedToSaveAttachments;
-(void)exportDocument;
-(void)markupDocument;
-(void)launchMarkupReply;

@end

