/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UISearchBar.h>
#import <MobileMail/MFAtomTextViewDelegate.h>

@protocol MFKVOObservation;
@class _MFAtomSearchBarFieldEditorBackgroundView, _MFSearchAtomTextView, UIProgressView, UIFont, UIView, UIImageView, MFGradientView, MFAtomScopeControl, NSProgress, NSArray, NSString;

@interface MFAtomSearchBar : UISearchBar <MFAtomTextViewDelegate> {

	_MFAtomSearchBarFieldEditorBackgroundView* _background;
	_MFSearchAtomTextView* _atomTextView;
	UIProgressView* _progressView;
	UIFont* _font;
	UIView* _scopeBarContainer;
	UIImageView* _scopeBarBackground;
	UIView* _scopeBarBottomDivider;
	MFGradientView* _scopeBarShadow;
	MFAtomScopeControl* _atomScopeControl;
	struct {
		unsigned delegateScopeButtonTitlesForRepresentedObject : 1;
		unsigned delegateSelectedScopeButtonIndexForRepresentedObject : 1;
		unsigned delegateSelectedScopeButtonIndexDidChangeForRepresentedObject : 1;
		unsigned delegateSearchButtonTapped : 1;
		unsigned delegateSupportedPasteboardTypes : 1;
		unsigned delegateRepresentedObjectsFromPasteboard : 1;
		unsigned delegateStoreRepresentedObjectsOnPasteboard : 1;
		unsigned observingProgressChanges : 1;
		unsigned showsScopeBar : 1;
		unsigned showsProgress : 1;
		unsigned needsProgressUpdate : 1;
	}  _flags;
	NSProgress* _progress;
	id<MFKVOObservation> _progressObservation;

}

@property (assign,nonatomic) id<MFAtomSearchBarDelegate> delegate; 
@property (nonatomic,copy) UIFont * font; 
@property (nonatomic,retain) NSProgress * progress;                                       //@synthesize progress=_progress - In the implementation block
@property (assign,nonatomic) BOOL showsProgress; 
@property (nonatomic,copy) NSArray * representedObjects; 
@property (nonatomic,copy,readonly) NSArray * selectedRepresentedObjects; 
@property (nonatomic,copy,readonly) NSString * currentEditingString; 
@property (nonatomic,retain,readonly) _MFSearchAtomTextView * atomTextView; 
@property (nonatomic,retain,readonly) MFAtomScopeControl * atomScopeControl; 
@property (nonatomic,retain,readonly) UIProgressView * progressView; 
@property (nonatomic,retain) id<MFKVOObservation> progressObservation;                    //@synthesize progressObservation=_progressObservation - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)defaultFont;
-(void)setRepresentedObjects:(NSArray *)arg1 ;
-(NSArray *)representedObjects;
-(NSString *)currentEditingString;
-(void)replaceCurrentEditingStringWithRepresentedObject:(id)arg1 ;
-(_MFSearchAtomTextView *)atomTextView;
-(BOOL)_hasRepresentedObjects;
-(NSArray *)selectedRepresentedObjects;
-(void)_setupProgressView;
-(void)_noteProgressNeedsUpdate;
-(void)_atomTextViewBeginEditing;
-(void)_atomTextViewEditingChanged;
-(void)_atomTextViewEndEditing;
-(void)_atomTextViewReturnPressed;
-(void)_setupAtomTextView;
-(void)_atomScopeChanged:(id)arg1 ;
-(void)_setupAtomScopeControl;
-(MFAtomScopeControl *)atomScopeControl;
-(void)_layoutSubviewsWithoutScopes;
-(id)atomTextView:(id)arg1 atomViewForRepresentedObject:(id)arg2 ;
-(void)atomTextViewDidChangeSelection:(id)arg1 ;
-(id)supportedPasteboardTypesForAtomTextView:(id)arg1 ;
-(id)atomTextView:(id)arg1 representedObjectsFromPasteboard:(id)arg2 ;
-(BOOL)atomTextView:(id)arg1 storeRepresentedObjects:(id)arg2 onPasteboard:(id)arg3 ;
-(id<MFKVOObservation>)progressObservation;
-(void)setProgressObservation:(id<MFKVOObservation>)arg1 ;
-(void)setDelegate:(id<MFAtomSearchBarDelegate>)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(BOOL)resignFirstResponder;
-(BOOL)isFirstResponder;
-(BOOL)becomeFirstResponder;
-(void)setFont:(UIFont *)arg1 ;
-(id)text;
-(BOOL)canBecomeFirstResponder;
-(void)setProgress:(NSProgress *)arg1 ;
-(UIFont *)font;
-(void)setPlaceholder:(id)arg1 ;
-(void)reloadInputViews;
-(BOOL)canResignFirstResponder;
-(UIProgressView *)progressView;
-(void)setScopeButtonTitles:(id)arg1 ;
-(void)_setupSearchField;
-(id)scopeButtonTitles;
-(id)placeholder;
-(id)_searchBarTextField;
-(void)_updateScopeBarBackground;
-(void)_updateMagnifyingGlassView;
-(void)_allowCursorToAppear:(BOOL)arg1 ;
-(BOOL)_scopeBarIsVisible;
-(void)_setShowsScopeBar:(BOOL)arg1 animateOpacity:(BOOL)arg2 ;
-(id)_glyphAndTextColor:(BOOL)arg1 ;
-(void)setSelectedScopeButtonIndex:(long long)arg1 ;
-(long long)selectedScopeButtonIndex;
-(void)setShowsScopeBar:(BOOL)arg1 ;
-(BOOL)showsScopeBar;
-(void)_setEnabled:(BOOL)arg1 animated:(BOOL)arg2 ;
-(NSProgress *)progress;
-(void)_updateProgress;
-(void)setShowsProgress:(BOOL)arg1 ;
-(BOOL)showsProgress;
@end

