/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MFAtomTextViewAtomLayout <NSObject>
@property (assign,getter=isEnabled,nonatomic) BOOL enabled; 
@property (assign,getter=isSelected,nonatomic) BOOL selected; 
@property (nonatomic,readonly) CGRect selectionBounds; 
@required
-(CGRect)selectionBounds;
-(void)setEnabled:(BOOL)arg1;
-(BOOL)isEnabled;
-(BOOL)isSelected;
-(void)setSelected:(BOOL)arg1;
-(void)setEnabled:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 style:(long long)arg3;

@end

