/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:43:59 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIControl.h>

@class UIFont, NSArray;

@interface MFAtomScopeControl : UIControl {

	UIFont* _font;
	NSArray* _buttons;
	NSArray* _titles;
	long long _selectedScopeIndex;

}

@property (nonatomic,retain) UIFont * font; 
@property (nonatomic,copy) NSArray * titles;                            //@synthesize titles=_titles - In the implementation block
@property (assign,nonatomic) long long selectedScopeIndex;              //@synthesize selectedScopeIndex=_selectedScopeIndex - In the implementation block
+(id)defaultFont;
-(void)_invalidateButtons;
-(void)setSelectedScopeIndex:(long long)arg1 notify:(BOOL)arg2 ;
-(void)setSelectedScopeIndex:(long long)arg1 ;
-(long long)selectedScopeIndex;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setEnabled:(BOOL)arg1 ;
-(void)setFont:(UIFont *)arg1 ;
-(UIFont *)font;
-(void)setTitles:(NSArray *)arg1 ;
-(NSArray *)titles;
-(id)buttons;
-(void)_buttonTapped:(id)arg1 ;
@end

