/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MFDelayedMessagesPresenterDelegate <NSObject>
@required
-(id)delayedMessagesPresenter:(id)arg1 bulletinRequestForMessage:(id)arg2 context:(id)arg3;
-(void)delayedMessagesPresenter:(id)arg1 handleBulletinRequest:(id)arg2 message:(id)arg3 context:(id)arg4;

@end

