/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/MFDiagnosticsGenerator.h>
#import <MobileMail/MFDeliveryDelegate.h>
#import <libobjc.A.dylib/MFContentProtectionObserver.h>

@protocol OS_dispatch_queue;
@class NSObject, MFInvocationQueue, NSMutableDictionary, NSString;

@interface MFDeliveryQueue : NSObject <MFDiagnosticsGenerator, MFDeliveryDelegate, MFContentProtectionObserver> {

	NSObject*<OS_dispatch_queue> _stateQueue;
	MFInvocationQueue* _jobQueue;
	int _state;
	unsigned long long _messagesFromActiveAccounts;
	unsigned long long _messageWithUIFocus;
	NSMutableDictionary* _lastErrorForMessage;
	unsigned _resetDeliveryQueueWhenDoneWithCurrentMessage : 1;
	unsigned _suspendRequested : 1;
	unsigned _isReachable : 1;
	unsigned _deviceUnlockedAfterBoot : 1;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedDeliveryQueue;
+(id)newDeliveryObjectFactoryForMessage:(id)arg1 ;
-(void)processQueue;
-(unsigned long long)numberOfPendingMessages;
-(void)processQueueAndPlaySoundOnSuccess:(BOOL)arg1 forceAll:(BOOL)arg2 isUserRequested:(BOOL)arg3 ;
-(void)_messagesAdded:(id)arg1 ;
-(void)processQueueAndPlaySoundOnSuccess:(BOOL)arg1 forceAll:(BOOL)arg2 ;
-(id)_sortedMessages;
-(id)lastErrorForMessage:(id)arg1 ;
-(long long)deliverSynchronously:(id)arg1 ;
-(id)_outboxStore;
-(id)_messagesInProgress;
-(void)_mailAccountsChanged:(id)arg1 ;
-(void)_focusedMessageDidChange:(id)arg1 ;
-(void)_queueProcessingDidFinish:(id)arg1 ;
-(void)_updateCounts;
-(void)_processQueueWithOptions:(id)arg1 ;
-(id)_append:(id)arg1 flags:(id)arg2 ;
-(void)_logDeliveryResult:(id)arg1 forMessage:(id)arg2 account:(id)arg3 ;
-(void)_setDeliveryFlag:(id)arg1 state:(BOOL)arg2 ;
-(void)_updateDeliveryInfoFromResult:(id)arg1 forMessage:(id)arg2 ;
-(void)_setErrorForMessageLibraryID:(id)arg1 error:(id)arg2 ;
-(void)_updateStateFile:(BOOL)arg1 ;
-(void)_sendProcessingStartedNotification;
-(BOOL)_shouldSend:(id)arg1 options:(id)arg2 ;
-(void)_setErrorForMessage:(id)arg1 error:(id)arg2 ;
-(void)_sendProcessingFinishedNotificationWithSentMessages:(id)arg1 failedMessages:(id)arg2 playSound:(BOOL)arg3 ;
-(BOOL)isReady;
-(BOOL)isSuspended;
-(void)dealloc;
-(id)init;
-(void)suspend;
-(void)resume;
-(void)_reachabilityChanged:(id)arg1 ;
-(id)copyDiagnosticInformation;
-(id)append:(id)arg1 ;
-(void)setPercentDone:(double)arg1 ;
-(BOOL)isProcessing;
-(void)contentProtectionStateChanged:(int)arg1 previousState:(int)arg2 ;
-(void)_flagsChanged:(id)arg1 ;
@end

