/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MailServices/MSSearch.h>
#import <libobjc.A.dylib/QueryProgressMonitor.h>
#import <libobjc.A.dylib/MSDSearchProtocol.h>

@protocol MFMessageIterationFilter;
@class MFMailMessageLibrary, MFXPCClient, MFActivityMonitor, MFMessageCriterion, NSArray, NSString;

@interface MFDSearch : MSSearch <QueryProgressMonitor, MSDSearchProtocol> {

	MFMailMessageLibrary* _library;
	MFXPCClient* _client;
	MFActivityMonitor* _monitor;
	MFMessageCriterion* _criteria;
	id<MFMessageIterationFilter> _filter;
	unsigned long long _options;
	NSArray* _keys;

}

@property (nonatomic,retain) MFMessageCriterion * criteria;                    //@synthesize criteria=_criteria - In the implementation block
@property (nonatomic,retain) id<MFMessageIterationFilter> filter;              //@synthesize filter=_filter - In the implementation block
@property (assign,nonatomic) unsigned long long options;                       //@synthesize options=_options - In the implementation block
@property (nonatomic,copy) NSArray * keys;                                     //@synthesize keys=_keys - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)endpointInfo;
-(void)_libraryWillBecomeUnavailable:(id)arg1 ;
-(BOOL)_hasSearchableMailAccount;
-(void)_registerForAutoFetchFinishedNotification;
-(id)_searchResultsProxy;
-(void)_autoFetchDone:(id)arg1 ;
-(void)_backgroundSearch;
-(unsigned)_libraryOptions;
-(void)dealloc;
-(id)init;
-(void)stop;
-(void)setFilter:(id<MFMessageIterationFilter>)arg1 ;
-(void)start;
-(id)remoteObjectProxyWithErrorHandler:(/*^block*/id)arg1 ;
-(void)setOptions:(unsigned long long)arg1 ;
-(unsigned long long)options;
-(NSArray *)keys;
-(void)setKeys:(NSArray *)arg1 ;
-(void)findMessageData:(id)arg1 matchingCriterion:(id)arg2 options:(unsigned long long)arg3 ;
-(id)initWithRemoteObjectInterface:(id)arg1 ;
-(id)newConnectionForInterface:(id)arg1 ;
-(MFMessageCriterion *)criteria;
-(void)setCriteria:(MFMessageCriterion *)arg1 ;
-(BOOL)shouldCancel;
-(id<MFMessageIterationFilter>)filter;
-(id)initWithClient:(id)arg1 ;
@end

