/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSLocale, NSString, NSArray;

@interface MFFuzzyStringComparisonResult : NSObject {

	NSLocale* _locale;
	NSString* _string1;
	NSString* _string2;
	NSArray* _allScoreCombinations;
	NSArray* _alignment;
	NSArray* _tailAlignment;
	NSArray* _perfectAlignment;
	double _alignmentLogScore;
	unsigned _exactMatch : 1;
	unsigned _hasEmptySentence : 1;
	unsigned _hasLogScore : 1;

}

@property (getter=isExactMatch,nonatomic,readonly) BOOL exactMatch; 
@property (nonatomic,readonly) unsigned long long bestGlobalScore; 
@property (nonatomic,readonly) unsigned long long worstGlobalScore; 
@property (nonatomic,readonly) unsigned long long averageGlobalScore; 
@property (nonatomic,readonly) unsigned long long lastWordScore; 
@property (nonatomic,readonly) NSArray * alignment; 
@property (nonatomic,readonly) NSArray * perfectAlignment; 
@property (nonatomic,readonly) NSArray * tailAlignment; 
@property (nonatomic,readonly) double alignmentLogScore; 
@property (nonatomic,readonly) unsigned long long perfectAlignmentScore; 
@property (nonatomic,readonly) NSArray * allScoreCombinations; 
+(id)matcherForSearchString:(id)arg1 locale:(id)arg2 options:(unsigned long long)arg3 ;
-(BOOL)isExactMatch;
-(unsigned long long)averageGlobalScore;
-(double)alignmentLogScore;
-(unsigned long long)perfectAlignmentScore;
-(unsigned long long)lastWordScore;
-(id)alignedWordsWithFuzzyThreshold:(double)arg1 ;
-(unsigned long long)bestGlobalScore;
-(unsigned long long)worstGlobalScore;
-(NSArray *)allScoreCombinations;
-(id)_globalScores;
-(id)_globalScoreWithPredicate:(id)arg1 ;
-(id)_alignmentForThreshold:(int)arg1 ;
-(NSArray *)perfectAlignment;
-(NSArray *)tailAlignment;
-(id)initWithString:(id)arg1 string2:(id)arg2 options:(unsigned long long)arg3 locale:(id)arg4 ;
-(void)dealloc;
-(id)init;
-(id)description;
-(id)debugDescription;
-(NSArray *)alignment;
@end

