/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSConditionLock;

@interface MFFutureMini : NSObject {

	NSConditionLock* _lock;
	id _result;

}
+(id)future;
-(void)dealloc;
-(id)init;
-(void)finishWithResult:(id)arg1 ;
-(id)result:(id*)arg1 ;
@end

