/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface MFMailDataProviderAutoFetchData : NSObject {

	BOOL _bulletinExpectedFromFetch;
	NSString* _currentAccountIDOfSoundToPlay;
	unsigned long long _loudestState;
	unsigned long long _fetchStart;

}

@property (nonatomic,retain) NSString * currentAccountIDOfSoundToPlay;              //@synthesize currentAccountIDOfSoundToPlay=_currentAccountIDOfSoundToPlay - In the implementation block
@property (assign,nonatomic) unsigned long long loudestState;                       //@synthesize loudestState=_loudestState - In the implementation block
@property (assign,nonatomic) BOOL bulletinExpectedFromFetch;                        //@synthesize bulletinExpectedFromFetch=_bulletinExpectedFromFetch - In the implementation block
@property (assign,nonatomic) unsigned long long fetchStart;                         //@synthesize fetchStart=_fetchStart - In the implementation block
-(NSString *)currentAccountIDOfSoundToPlay;
-(void)setCurrentAccountIDOfSoundToPlay:(NSString *)arg1 ;
-(unsigned long long)loudestState;
-(void)setLoudestState:(unsigned long long)arg1 ;
-(BOOL)bulletinExpectedFromFetch;
-(void)setBulletinExpectedFromFetch:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setFetchStart:(unsigned long long)arg1 ;
-(unsigned long long)fetchStart;
@end

