/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@protocol MFMailDropBannerDelegate;
@class UILabel, UIView, UIButton, MFProgressView, SeparatorLayer, NSLayoutConstraint, NSMutableArray, MFMailDropMetadata, MFMessageDisplayMetrics, NSProgress;

@interface MFMailDropBannerView : UIView {

	BOOL _hasLoaded;
	UILabel* _expirationLabel;
	UILabel* _downloadLabel;
	UIView* _iconWrapper;
	UIButton* _downloadIcon;
	MFProgressView* _progressView;
	SeparatorLayer* _topSeparatorBar;
	SeparatorLayer* _bottomSeparatorBar;
	NSLayoutConstraint* _iconWrapperWidth;
	NSLayoutConstraint* _labelFirstBaseline;
	NSLayoutConstraint* _expirationFirstBaseline;
	NSLayoutConstraint* _expirationBottom;
	NSLayoutConstraint* _topSeparatorTrailing;
	NSLayoutConstraint* _bottomSeparatorTrailing;
	NSMutableArray* _childProgresses;
	BOOL _hasDataLocally;
	MFMailDropMetadata* _metaData;
	MFMessageDisplayMetrics* _displayMetrics;
	NSProgress* _downloadProgress;
	unsigned long long _bannerState;
	unsigned long long _totalAttachmentSize;
	id<MFMailDropBannerDelegate> _delegate;

}

@property (nonatomic,retain) MFMailDropMetadata * metaData;                         //@synthesize metaData=_metaData - In the implementation block
@property (nonatomic,retain) MFMessageDisplayMetrics * displayMetrics;              //@synthesize displayMetrics=_displayMetrics - In the implementation block
@property (nonatomic,retain) NSProgress * downloadProgress;                         //@synthesize downloadProgress=_downloadProgress - In the implementation block
@property (assign,nonatomic) unsigned long long bannerState;                        //@synthesize bannerState=_bannerState - In the implementation block
@property (assign,nonatomic) BOOL hasDataLocally;                                   //@synthesize hasDataLocally=_hasDataLocally - In the implementation block
@property (assign,nonatomic) unsigned long long totalAttachmentSize;                //@synthesize totalAttachmentSize=_totalAttachmentSize - In the implementation block
@property (assign,nonatomic) id<MFMailDropBannerDelegate> delegate;                 //@synthesize delegate=_delegate - In the implementation block
-(void)setMetaData:(MFMailDropMetadata *)arg1 ;
-(void)setHasDataLocally:(BOOL)arg1 ;
-(void)setTotalAttachmentSize:(unsigned long long)arg1 ;
-(void)associateAttachment:(id)arg1 ;
-(void)setDisplayMetrics:(MFMessageDisplayMetrics *)arg1 ;
-(MFMessageDisplayMetrics *)displayMetrics;
-(CGSize)bannerSizeForHeaderViewSize:(CGSize)arg1 ;
-(BOOL)shouldPresent;
-(void)_setupDownloadLabel;
-(void)_setupExpirationLabel;
-(void)_setupDownloadIcon;
-(void)_updateBannerToState:(unsigned long long)arg1 ;
-(BOOL)_shouldDisplayProgress;
-(unsigned long long)bannerState;
-(void)setBannerState:(unsigned long long)arg1 ;
-(BOOL)hasDataLocally;
-(unsigned long long)totalAttachmentSize;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<MFMailDropBannerDelegate>)arg1 ;
-(void)dealloc;
-(id<MFMailDropBannerDelegate>)delegate;
-(void)reset;
-(void)updateConstraints;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)startDownload:(id)arg1 ;
-(MFMailDropMetadata *)metaData;
-(NSProgress *)downloadProgress;
-(void)setDownloadProgress:(NSProgress *)arg1 ;
-(void)contentSizeCategoryDidChangeNotification:(id)arg1 ;
@end

