/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MFMessageDisplayMetrics.h>

@interface MFMessageDisplayMetricsRegular : MFMessageDisplayMetrics {

	double _avatarBottomToFirstSeparator;
	double _topToSenderBaseline;
	double _senderBaselineToRecipientBaseline;
	double _recipientBaselineToFirstSeparator;
	double _firstSeparatorToSubjectBaseline;
	double _subjectBaselineToTimestampBaseline;
	double _headerBottomPadding;
	double _statusIndicatorVerticalSpacing;

}
-(double)avatarDiameter;
-(double)avatarBottomToFirstSeparator;
-(double)topToSenderBaseline;
-(double)senderBaselineToRecipientBaseline;
-(double)recipientBaselineToFirstSeparator;
-(double)statusIndicatorVerticalSpacing;
-(double)firstSeparatorToSubjectBaseline;
-(double)subjectBaselineToTimestampBaseline;
-(double)headerBottomPadding;
@end

