/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MFAddressBookClient.h>

@protocol OS_dispatch_queue, MFMessageBulletinsObserverDelegate;
@class NSObject, MFMessageResultsGenerator, NSMutableSet, NSMutableDictionary, NSLock, MFWeakDictionary, NSString;

@interface MFMessageBulletinsObserver : NSObject <MFAddressBookClient> {

	NSObject*<OS_dispatch_queue> _queue;
	MFMessageResultsGenerator* _queueResultsGenerator;
	BOOL _hasVIPs;
	BOOL _hasThreads;
	NSMutableSet* _observedAccountIDs;
	NSMutableDictionary* _observedStoresByAccountID;
	NSLock* _observedStoresByAccountIDLock;
	MFWeakDictionary* _summaryClientsByReference;
	id<MFMessageBulletinsObserverDelegate> _delegate;

}

@property (assign,nonatomic) id<MFMessageBulletinsObserverDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)activeBulletinsAccounts:(id*)arg1 ;
-(id)messagesForAccountIDs:(id)arg1 count:(unsigned long long)arg2 clearedInfo:(id)arg3 sinceDate:(id)arg4 ;
-(BOOL)isObservingMailboxID:(id)arg1 inAccountID:(id)arg2 ;
-(void)_invalidateClient:(id)arg1 ;
-(void)_nts_startObservingAccounts:(id)arg1 ;
-(void)_handleAccountsChanged:(id)arg1 ;
-(void)_handleVIPsChanged:(id)arg1 ;
-(void)_protectedDataBecameAvailable:(id)arg1 ;
-(void)_handlePreferencesChanged:(id)arg1 ;
-(void)_handleThreadsChanged:(id)arg1 ;
-(void)_nts_stopObservingAccountWithIDs:(id)arg1 ;
-(void)_handleMessagesAdded:(id)arg1 ;
-(void)_handleFlagsChanged:(id)arg1 ;
-(void)_handleMessagesCompacted:(id)arg1 ;
-(void)_startObservingStore:(id)arg1 ;
-(void)_handlePushedFoldersChanged:(id)arg1 ;
-(void)_handleFavoriteMailboxesChanged:(id)arg1 ;
-(void)_stopObservingStore:(id)arg1 ;
-(void)cancelSummaryRequestsForAccountWithID:(id)arg1 ;
-(void)requestSummaryWithClient:(id)arg1 ;
-(void)notifyMessagesAdded:(id)arg1 afterDate:(id)arg2 isSummaryDownload:(BOOL)arg3 ;
-(id)_nts_resultsGenerator;
-(void)requestSummaryForMessage:(id)arg1 ;
-(BOOL)_nts_updateObservationWithAccounts:(id)arg1 ;
-(void)_notifyAccountsChanged:(id)arg1 hasVIPs:(BOOL)arg2 hasThreads:(BOOL)arg3 error:(id)arg4 ;
-(void)_handleFoldersChanged:(id)arg1 ;
-(void)cancelSummaryRequestForMessageWithExternalReference:(id)arg1 ;
-(void)updateMessage:(id)arg1 withSummary:(id)arg2 ;
-(void)setDelegate:(id<MFMessageBulletinsObserverDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<MFMessageBulletinsObserverDelegate>)delegate;
-(void)stop;
-(void)start;
-(void)setTargetQueue:(id)arg1 ;
-(void)addressBookManager:(id)arg1 addressBookDidChange:(void*)arg2 ;
-(void)addressBookPreferencesChangedForAddressBookManager:(id)arg1 ;
-(void)_handleAddressBookChanged;
@end

