/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MFMessageWebLayerDelegate <NSObject>
@optional
-(double)canvasWidthForWebLayer:(id)arg1;
-(UIEdgeInsets*)basePaddingForWebLayer:(id)arg1;
-(void)messageWebLayer:(id)arg1 didFindBottomReplyRange:(id)arg2 lastQuoteLevel:(unsigned long long)arg3;
-(void)messageWebLayer:(id)arg1 didEncounterMailDropNodes:(id)arg2 whileParsingDocument:(id)arg3;

@required
-(BOOL)messageWebLayerShouldUsePadDisplayStyle:(id)arg1;
-(BOOL)messageWebLayerShouldHaveCozyMargins:(id)arg1;
-(void)messageWebLayer:(id)arg1 openURL:(id)arg2;
-(id)messageWebLayer:(id)arg1 attachmentsWithURLs:(id)arg2;
-(void)messageWebLayer:(id)arg1 sizeDidChange:(CGSize)arg2;
-(CGRect*)messageWebLayer:(id)arg1 newFrameForRect:(CGRect)arg2;
-(void)messageWebLayerDidFinishLoading:(id)arg1;
-(void)messageWebLayerDidFinishTweaking:(id)arg1;
-(void)messageWebLayer:(id)arg1 didDrawTileAtBounds:(CGRect)arg2;
-(void)messageWebLayerDidFirstVisuallyNonEmptyLayout:(id)arg1;
-(void)messageWebLayer:(id)arg1 didFailToPaintAttachmentURL:(id)arg2;

@end

