/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MFMessageViewingContextDelegate.h>

@protocol OS_dispatch_queue, OS_dispatch_semaphore;
@class NSObject, NSMutableSet, NSMutableDictionary, NSString;

@interface MFNanoServerMessageSender : NSObject <MFMessageViewingContextDelegate> {

	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_dispatch_semaphore> _messageContentLoadedSemaphore;
	BOOL _messageContentLoadedSuccess;
	NSObject*<OS_dispatch_semaphore> _messagesDeliveredSemaphore;
	NSMutableSet* _pendingMessageReferences;
	NSMutableDictionary* _sentMessageReferences;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_didReceiveMessageDeliveryNotification:(id)arg1 ;
-(id)_libraryMessageForMessageId:(id)arg1 ;
-(id)_messageToSendWithCompositionContext:(id)arg1 ;
-(id)_sendComposedMessage:(id)arg1 ;
-(void)sendMessage:(id)arg1 progressHandler:(/*^block*/id)arg2 ;
-(void)dealloc;
-(id)init;
-(void)messageViewingContextContentLoadCompleted:(id)arg1 ;
-(void)messageViewingContextFullMessageLoadFailed:(id)arg1 ;
@end

