/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject;

@interface MFNanoServerMessageUpdater : NSObject {

	NSObject*<OS_dispatch_queue> _queue;

}
-(id)_libraryMessageForMessageId:(id)arg1 ;
-(void)updateMessages:(id)arg1 ;
-(BOOL)_status:(unsigned long long)arg1 containsState:(unsigned long long)arg2 ;
-(void)_addOperation:(id)arg1 withMessages:(id)arg2 toChangeManager:(id)arg3 ;
-(void)dealloc;
-(id)init;
@end

