/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>

@protocol MFSearchSuggestionsControllerDelegate;
@class _MFSearchSuggestionsTableViewModel, NSMutableSet;

@interface MFSearchSuggestionsController : UITableViewController {

	_MFSearchSuggestionsTableViewModel* _tableViewModel;
	NSMutableSet* _touchedCategories;
	id<MFSearchSuggestionsControllerDelegate> _delegate;

}

@property (assign,nonatomic) id<MFSearchSuggestionsControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) BOOL hasSuggestions; 
+(/*^block*/id)categoryComparator;
-(void)beginUpdatingSuggestions;
-(void)clearSuggestions;
-(void)updateSuggestions:(id)arg1 categories:(id)arg2 ;
-(BOOL)hasSuggestions;
-(void)endUpdatingSuggestions;
-(void)setTableViewModel:(id)arg1 animated:(BOOL)arg2 ;
-(BOOL)_delegateAllowsCategory:(id)arg1 cachedValues:(id)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setDelegate:(id<MFSearchSuggestionsControllerDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(id<MFSearchSuggestionsControllerDelegate>)delegate;
-(id)initWithStyle:(long long)arg1 ;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(id)initWithDelegate:(id)arg1 ;
@end

