/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MFSearchSuggestionsControllerDelegate <NSObject>
@required
-(BOOL)searchSuggestionsController:(id)arg1 shouldShowSuggestionsForCategory:(id)arg2;
-(void)searchSuggestionsController:(id)arg1 didSelectSuggestion:(id)arg2;

@end

