/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <MobileMail/MFSearchSuggestion.h>

@class MFSearchSuggestionCategory, NSString, NSArray;

@interface MFSearchSpotlightSuggestion : MFSearchSuggestion {

	MFSearchSuggestionCategory* _category;
	NSString* _title;
	NSString* _contactIdentifier;
	NSArray* _attributeNames;
	struct {
		unsigned hasCalculatedVIPState : 1;
		unsigned isVIP : 1;
	}  _flags;
	double _alignmentScore;
	unsigned long long _perfectAlignmentScore;
	NSArray* _attributeValues;

}

@property (nonatomic,readonly) double alignmentScore;                                 //@synthesize alignmentScore=_alignmentScore - In the implementation block
@property (nonatomic,readonly) unsigned long long perfectAlignmentScore;              //@synthesize perfectAlignmentScore=_perfectAlignmentScore - In the implementation block
@property (nonatomic,copy,readonly) NSArray * attributeValues;                        //@synthesize attributeValues=_attributeValues - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)atomImage;
-(double)alignmentScore;
-(unsigned long long)perfectAlignmentScore;
-(id)initWithTitle:(id)arg1 category:(id)arg2 attributeNames:(id)arg3 values:(id)arg4 contact:(id)arg5 alignmentScore:(double)arg6 perfectAlignmentScore:(unsigned long long)arg7 ;
-(id)initWithTitle:(id)arg1 category:(id)arg2 attributeNames:(id)arg3 values:(id)arg4 contactIdentifier:(id)arg5 alignmentScore:(double)arg6 perfectAlignmentScore:(unsigned long long)arg7 ;
-(BOOL)isPersonSuggestion;
-(NSArray *)attributeValues;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(id)category;
-(id)title;
-(id)image;
-(id)subtitle;
-(BOOL)isVIP;
-(id)contactIdentifier;
@end

