/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>
#import <MobileMail/MFAtomTextViewAtomLayout.h>

@class MFSearchSuggestion, _MFSearchAtomBackgroundView, UIImageView, UILabel, NSArray, NSString;

@interface MFSearchAtomView : UIView <MFAtomTextViewAtomLayout> {

	struct {
		unsigned enabled : 1;
		unsigned selected : 1;
	}  _flags;
	MFSearchSuggestion* _suggestion;
	_MFSearchAtomBackgroundView* _backgroundView;
	UIImageView* _leadingImage;
	UILabel* _textLabel;
	NSArray* _defaultConstraints;
	NSArray* _withImageConstraints;
	NSArray* _withoutImageConstraints;

}

@property (nonatomic,retain) MFSearchSuggestion * suggestion;                           //@synthesize suggestion=_suggestion - In the implementation block
@property (nonatomic,retain) _MFSearchAtomBackgroundView * backgroundView;              //@synthesize backgroundView=_backgroundView - In the implementation block
@property (nonatomic,retain) UIImageView * leadingImage;                                //@synthesize leadingImage=_leadingImage - In the implementation block
@property (nonatomic,retain) UILabel * textLabel;                                       //@synthesize textLabel=_textLabel - In the implementation block
@property (nonatomic,copy) NSArray * defaultConstraints;                                //@synthesize defaultConstraints=_defaultConstraints - In the implementation block
@property (nonatomic,copy) NSArray * withImageConstraints;                              //@synthesize withImageConstraints=_withImageConstraints - In the implementation block
@property (nonatomic,copy) NSArray * withoutImageConstraints;                           //@synthesize withoutImageConstraints=_withoutImageConstraints - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,getter=isEnabled,nonatomic) BOOL enabled; 
@property (assign,getter=isSelected,nonatomic) BOOL selected; 
@property (nonatomic,readonly) CGRect selectionBounds; 
+(BOOL)requiresConstraintBasedLayout;
-(MFSearchSuggestion *)suggestion;
-(void)setSuggestion:(MFSearchSuggestion *)arg1 ;
-(double)_bottomMargin;
-(void)setDefaultConstraints:(NSArray *)arg1 ;
-(NSArray *)defaultConstraints;
-(CGRect)selectionBounds;
-(void)_updateImageColor;
-(double)_topToBaselineDelta;
-(void)setWithImageConstraints:(NSArray *)arg1 ;
-(void)setWithoutImageConstraints:(NSArray *)arg1 ;
-(UIImageView *)leadingImage;
-(void)setLeadingImage:(UIImageView *)arg1 ;
-(NSArray *)withImageConstraints;
-(NSArray *)withoutImageConstraints;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setEnabled:(BOOL)arg1 ;
-(BOOL)isEnabled;
-(id)_font;
-(BOOL)isSelected;
-(void)setBackgroundView:(_MFSearchAtomBackgroundView *)arg1 ;
-(void)setSelected:(BOOL)arg1 ;
-(UILabel *)textLabel;
-(_MFSearchAtomBackgroundView *)backgroundView;
-(void)updateConstraints;
-(id)viewForLastBaselineLayout;
-(void)setEnabled:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setTextLabel:(UILabel *)arg1 ;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 style:(long long)arg3 ;
-(void)_updateTextColor;
@end

