/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, MFSearchSuggestion, NSArray, NSLayoutConstraint;

@interface MFSearchSuggestionsTableViewCell : UITableViewCell {

	UIImageView* _glyph;
	UILabel* _title;
	UILabel* _subtitle;
	MFSearchSuggestion* _suggestion;
	NSArray* _defaultConstraints;
	NSArray* _titleOnlyConstraints;
	NSArray* _subtitleConstraints;
	NSLayoutConstraint* _singleLineTitleBaselineConstraint;
	NSLayoutConstraint* _singleLineBottomBaselineConstraint;
	NSLayoutConstraint* _titleBaselineConstraint;
	NSLayoutConstraint* _interLabelBaselineConstraint;
	NSLayoutConstraint* _subtitleBaselineConstraint;

}

@property (nonatomic,retain) MFSearchSuggestion * suggestion;                                      //@synthesize suggestion=_suggestion - In the implementation block
@property (nonatomic,copy) NSArray * defaultConstraints;                                           //@synthesize defaultConstraints=_defaultConstraints - In the implementation block
@property (nonatomic,copy) NSArray * titleOnlyConstraints;                                         //@synthesize titleOnlyConstraints=_titleOnlyConstraints - In the implementation block
@property (nonatomic,copy) NSArray * subtitleConstraints;                                          //@synthesize subtitleConstraints=_subtitleConstraints - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * singleLineTitleBaselineConstraint;               //@synthesize singleLineTitleBaselineConstraint=_singleLineTitleBaselineConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * singleLineBottomBaselineConstraint;              //@synthesize singleLineBottomBaselineConstraint=_singleLineBottomBaselineConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * titleBaselineConstraint;                         //@synthesize titleBaselineConstraint=_titleBaselineConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * interLabelBaselineConstraint;                    //@synthesize interLabelBaselineConstraint=_interLabelBaselineConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * subtitleBaselineConstraint;                      //@synthesize subtitleBaselineConstraint=_subtitleBaselineConstraint - In the implementation block
+(BOOL)requiresConstraintBasedLayout;
-(MFSearchSuggestion *)suggestion;
-(void)setSuggestion:(MFSearchSuggestion *)arg1 ;
-(void)setDefaultConstraints:(NSArray *)arg1 ;
-(double)_singleLineTitleBaselineConstant;
-(void)setSingleLineTitleBaselineConstraint:(NSLayoutConstraint *)arg1 ;
-(double)_singleLineBottomBaselineConstant;
-(void)setSingleLineBottomBaselineConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)singleLineTitleBaselineConstraint;
-(NSLayoutConstraint *)singleLineBottomBaselineConstraint;
-(void)setTitleOnlyConstraints:(NSArray *)arg1 ;
-(double)_titleBaselineConstant;
-(void)setTitleBaselineConstraint:(NSLayoutConstraint *)arg1 ;
-(double)_interLabelBaselineConstant;
-(void)setInterLabelBaselineConstraint:(NSLayoutConstraint *)arg1 ;
-(double)_subtitleBottomBaselineConstant;
-(NSLayoutConstraint *)titleBaselineConstraint;
-(NSLayoutConstraint *)interLabelBaselineConstraint;
-(void)setSubtitleConstraints:(NSArray *)arg1 ;
-(NSArray *)defaultConstraints;
-(NSArray *)titleOnlyConstraints;
-(NSArray *)subtitleConstraints;
-(void)dealloc;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(void)updateConstraints;
-(id)_titleFont;
-(void)_preferredContentSizeCategoryDidChange:(id)arg1 ;
-(id)_subtitleFont;
-(NSLayoutConstraint *)subtitleBaselineConstraint;
-(void)setSubtitleBaselineConstraint:(NSLayoutConstraint *)arg1 ;
@end

