/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:43:59 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MFSearchSuggestion.h>

@class NSString, MFMessageCriterion, NSArray;

@interface MFSearchMessageStatusSuggestion : MFSearchSuggestion {

	NSString* _title;
	NSString* _atomTitle;
	MFMessageCriterion* _criterion;
	NSArray* _words;

}
+(id)suggestion;
+(id)suggestionWithTitle:(id)arg1 atomTitle:(id)arg2 words:(id)arg3 criterion:(id)arg4 ;
+(BOOL)supportsSecureCoding;
-(BOOL)matchesPhrase:(id)arg1 ;
-(id)initWithTitle:(id)arg1 atomTitle:(id)arg2 words:(id)arg3 criterion:(id)arg4 ;
-(id)atomTitle;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(id)category;
-(id)title;
-(id)subtitle;
-(id)criterion;
-(id)contactIdentifier;
@end

