/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MFSearchSuggester.h>
#import <MobileMail/MailboxUtilsClient.h>

@class NSArray;

@interface MFSearchMailboxSuggester : MFSearchSuggester <MailboxUtilsClient> {

	NSArray* _mailboxList;

}
-(id)generateSuggestionsForPhrase:(id)arg1 handler:(/*^block*/id)arg2 ;
-(id)mailboxList;
-(void)dealloc;
-(id)categories;
-(void)shouldReloadMailboxesWithOutbox:(id)arg1 ;
-(BOOL)shouldHideInbox;
-(BOOL)shouldHideNotesForAccount:(id)arg1 ;
@end

