/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <MobileMail/MFSearchSuggester.h>

@class NSArray, NSPredicate;

@interface MFSpotlightSuggester : MFSearchSuggester {

	NSArray* _attributeNames;
	NSPredicate* _basePredicate;

}

@property (nonatomic,copy) NSArray * attributeNames;                 //@synthesize attributeNames=_attributeNames - In the implementation block
@property (nonatomic,copy) NSPredicate * basePredicate;              //@synthesize basePredicate=_basePredicate - In the implementation block
+(id)defaultAttributeNames;
-(id)generateSuggestionsForPhrase:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)setBasePredicate:(NSPredicate *)arg1 ;
-(id)accountRawEmailAddresses;
-(id)accountEmailAddressesByReplacingName:(id)arg1 ;
-(id)_queryStringForPhrase:(id)arg1 attributes:(id)arg2 baseQuery:(id)arg3 ;
-(id)_matchedFieldsQueryStringsForPhrase:(id)arg1 attributes:(id)arg2 ;
-(id)queryRecentsForPhrase:(id)arg1 ;
-(id)myAddressesForPhrase:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)categories;
-(NSPredicate *)basePredicate;
-(NSArray *)attributeNames;
-(void)setAttributeNames:(NSArray *)arg1 ;
@end

