/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, NSString, CNContact, NSArray;

@interface MFSpotlightContact : NSObject {

	NSMutableArray* _values;
	NSString* _displayName;
	CNContact* _contact;

}

@property (nonatomic,readonly) NSString * displayName;              //@synthesize displayName=_displayName - In the implementation block
@property (nonatomic,readonly) NSArray * values; 
@property (nonatomic,readonly) CNContact * contact;                 //@synthesize contact=_contact - In the implementation block
-(id)initWithDisplayName:(id)arg1 values:(id)arg2 ;
-(BOOL)hasValue:(id)arg1 ;
-(void)dealloc;
-(NSArray *)values;
-(NSString *)displayName;
-(void)addValue:(id)arg1 ;
-(CNContact *)contact;
-(id)initWithContact:(id)arg1 ;
@end

