/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <QuartzCore/CASpringAnimation.h>

@class MFSpringAnimationDelegate;

@interface MFSpringAnimation : CASpringAnimation

@property (nonatomic,retain) MFSpringAnimationDelegate * delegate; 
+(id)springAnimationWithKeyPath:(id)arg1 toLayer:(id)arg2 fromValue:(id)arg3 toValue:(id)arg4 ;
+(double)defaultAnimationDuration;
-(id)init;
-(void)addCompletionBlock:(/*^block*/id)arg1 ;
@end

