/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class MFWeakReferenceHolder, NSXPCConnection;

@interface MFXPCClient : NSObject {

	MFWeakReferenceHolder* _connectionHolder;
	/*^block*/id _invalidationHandler;
	/*^block*/id _interruptionHandler;

}

@property (nonatomic,__weak,readonly) NSXPCConnection * connection; 
@property (nonatomic,copy) id invalidationHandler;                               //@synthesize invalidationHandler=_invalidationHandler - In the implementation block
@property (nonatomic,copy) id interruptionHandler;                               //@synthesize interruptionHandler=_interruptionHandler - In the implementation block
-(void)dealloc;
-(id)description;
-(NSXPCConnection *)connection;
-(id)interruptionHandler;
-(void)setInterruptionHandler:(id)arg1 ;
-(id)invalidationHandler;
-(void)setInvalidationHandler:(id)arg1 ;
-(BOOL)hasEntitlement:(id)arg1 ;
-(id)initWithConnection:(id)arg1 ;
@end

