/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSLock, MFXPCEndpointListener, NSXPCInterface;

@interface MFXPCEndpointInfo : NSObject {

	NSLock* _lock;
	MFXPCEndpointListener* _listener;
	NSXPCInterface* _exportedInterface;
	NSXPCInterface* _remoteObjectInterface;
	/*^block*/id _shouldAcceptClient;
	/*^block*/id _exportedObjectForClient;

}

@property (nonatomic,retain,readonly) NSXPCInterface * exportedInterface;                  //@synthesize exportedInterface=_exportedInterface - In the implementation block
@property (nonatomic,retain,readonly) NSXPCInterface * remoteObjectInterface;              //@synthesize remoteObjectInterface=_remoteObjectInterface - In the implementation block
@property (nonatomic,copy,readonly) id shouldAcceptClient;                                 //@synthesize shouldAcceptClient=_shouldAcceptClient - In the implementation block
@property (nonatomic,copy,readonly) id exportedObjectForClient;                            //@synthesize exportedObjectForClient=_exportedObjectForClient - In the implementation block
+(id)endpointInfoWithExportedInterface:(id)arg1 remoteObjectInterface:(id)arg2 shouldAcceptClient:(/*^block*/id)arg3 exportedObjectForClient:(/*^block*/id)arg4 ;
-(id)existingListener:(BOOL)arg1 ;
-(id)shouldAcceptClient;
-(id)exportedObjectForClient;
-(NSXPCInterface *)remoteObjectInterface;
-(void)dealloc;
-(id)init;
-(NSXPCInterface *)exportedInterface;
-(id)listener;
@end

