/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreFoundation/NSDictionary.h>

@class NSIndexSet;

@interface MMGrowingFetchContext : NSDictionary {

	NSIndexSet* _growingFetchSections;

}

@property (nonatomic,retain) NSIndexSet * growingFetchSections;              //@synthesize growingFetchSections=_growingFetchSections - In the implementation block
-(NSIndexSet *)growingFetchSections;
-(void)setGrowingFetchSections:(NSIndexSet *)arg1 ;
-(void)dealloc;
-(id)description;
@end

