/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSObject, EKICSPreviewController, UIDocumentInteractionController, ABUnknownPersonViewController;

typedef struct opaque_pthread_mutex_t {
	long long __sig;
	char __opaque[56];
} opaque_pthread_mutex_t;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct CGPoint {
	double x;
	double y;
} CGPoint;

typedef struct {
	BOOL field1;
	BOOL field2;
	BOOL field3;
	BOOL field4;
	BOOL field5;
	double field6;
	int field7;
} SCD_Struct_Ma3;

typedef struct _NSZone* NSZoneRef;

typedef struct CGSize {
	double width;
	double height;
} CGSize;

typedef struct __DDResult* DDResultRef;

typedef struct __DDScanQuery* DDScanQueryRef;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct NSRange {
	unsigned long long location;
	unsigned long long length;
} NSRange;

typedef struct IONotificationPort* IONotificationPortRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef union {
	NSObject* _controller;
	EKICSPreviewController* _icsPreviewController;
	UIDocumentInteractionController* _uidic;
	ABUnknownPersonViewController* _vcardController;
} SCD_Union_Me12;

typedef struct UIEdgeInsets {
	double top;
	double left;
	double bottom;
	double right;
} UIEdgeInsets;

typedef struct __CFSet* CFSetRef;

typedef struct __CFCharacterSet* CFCharacterSetRef;

typedef struct __DDScanner* DDScannerRef;

typedef struct MessageFoldPinch {
	double centroidY;
	double distanceY;
} MessageFoldPinch;

typedef struct CGGradient* CGGradientRef;

typedef struct __CFArray* CFArrayRef;

typedef struct CGContext* CGContextRef;

