/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/CriterionSource.h>

@interface NotifyThreadsCriterionSource : CriterionSource
-(void)reloadPreferences;
-(id)bulletinsContext;
-(id)noMessagesLabelText;
-(BOOL)shouldIncludeWholeThreads;
-(unsigned long long)type;
-(id)mailboxName;
-(id)initWithSource:(id)arg1 ;
@end

