/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SearchManagerDelegate <NSObject>
@required
-(void)searchManager:(id)arg1 foundMessages:(id)arg2 keepExistingMessages:(BOOL)arg3 forSearchWithIdentifier:(id)arg4 shouldWait:(BOOL)arg5;
-(void)searchManager:(id)arg1 finishedSearchWithIdentifier:(id)arg2;

@end

