/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIControl.h>

@class UIScrollView, UISegmentedControl, UIView, NSArray;

@interface SearchScopeControl : UIControl {

	UIScrollView* _scrollView;
	UISegmentedControl* _segments;
	UIView* _separator;
	NSArray* _scopeTitles;

}

@property (nonatomic,copy) NSArray * scopeTitles;                       //@synthesize scopeTitles=_scopeTitles - In the implementation block
@property (assign,nonatomic) long long selectedScopeIndex; 
-(void)setSelectedScopeIndex:(long long)arg1 ;
-(long long)selectedScopeIndex;
-(void)setScopeTitles:(NSArray *)arg1 ;
-(void)_segmentValueChanged:(id)arg1 ;
-(void)_updateMaskIfNecessary;
-(void)setScopeTitles:(id)arg1 animated:(BOOL)arg2 ;
-(void)_updateTitles:(BOOL)arg1 ;
-(NSArray *)scopeTitles;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setEnabled:(BOOL)arg1 ;
-(void)willMoveToSuperview:(id)arg1 ;
-(void)_didScroll;
@end

