/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol StackElementDelegate
@required
-(void)stackElement:(id)arg1 currentStateDidChangeFrom:(int)arg2 to:(int)arg3;
-(id)stackContainerView;
-(long long)maximumStackElementDepth;
-(UIEdgeInsets*)stackContainerViewEdgeInsets;
-(BOOL)stackIsTerminating;
-(id)viewForStackElement:(id)arg1;
-(id)viewBelowStackElement:(id)arg1;
-(void)stackElement:(id)arg1 willRemoveView:(id)arg2;
-(void)stackElement:(id)arg1 targetStateDidChangeFrom:(int)arg2 to:(int)arg3;

@end

