/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SwipeActionPullViewDelegate <NSObject>
@optional
-(id)swipeActionPullView:(id)arg1 iconForAction:(unsigned long long)arg2;

@required
-(double)confirmationDistanceForPrimaryActionInSwipeActionPullView:(id)arg1;
-(id)swipeActionPullView:(id)arg1 titleForAction:(unsigned long long)arg2;
-(void)swipeActionPullView:(id)arg1 tappedAction:(unsigned long long)arg2;

@end

