/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:00 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@protocol SwipeActionPullViewDelegate;
@class NSMutableArray, NSArray, UIView, UIColor;

@interface SwipeActionPullView : UIView {

	NSMutableArray* _buttons;
	NSArray* _actions;
	UIView* _backgroundView;
	BOOL _swipeActionsDidChange;
	double _openThreshold;
	double _confirmationThreshold;
	unsigned long long _cellEdge;
	unsigned long long _state;
	double _currentOffset;
	id<SwipeActionPullViewDelegate> _delegate;

}

@property (assign,nonatomic) id<SwipeActionPullViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) unsigned long long cellEdge;                         //@synthesize cellEdge=_cellEdge - In the implementation block
@property (nonatomic,readonly) unsigned long long primarySwipeAction; 
@property (nonatomic,readonly) double currentOffset;                                //@synthesize currentOffset=_currentOffset - In the implementation block
@property (nonatomic,readonly) double openThreshold; 
@property (nonatomic,readonly) double confirmationThreshold; 
@property (nonatomic,readonly) UIColor * primaryActionColor; 
@property (nonatomic,readonly) BOOL primaryActionIsDestructive; 
@property (nonatomic,readonly) BOOL hasActions; 
@property (assign,nonatomic) unsigned long long state;                              //@synthesize state=_state - In the implementation block
-(unsigned long long)_swipeActionCount;
-(unsigned long long)_actionAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)primarySwipeAction;
-(double)_directionalMultiplier;
-(unsigned long long)cellEdge;
-(double)confirmationThreshold;
-(void)_tappedButton:(id)arg1 ;
-(void)_rebuildButtons;
-(id)_actionColorForSwipeAction:(unsigned long long)arg1 highlighted:(BOOL)arg2 ;
-(unsigned long long)_nextStateForPullView;
-(BOOL)_offsetMeetsConfirmationThreshold:(double)arg1 ;
-(id)initWithCellEdge:(unsigned long long)arg1 ;
-(BOOL)primaryActionIsDestructive;
-(UIColor *)primaryActionColor;
-(double)openThreshold;
-(void)resetView;
-(void)configureWithSwipeActions:(id)arg1 ;
-(void)moveToOffset:(double)arg1 animated:(BOOL)arg2 usingSpringWithStiffness:(double)arg3 initialVelocity:(double)arg4 ;
-(void)setDelegate:(id<SwipeActionPullViewDelegate>)arg1 ;
-(void)dealloc;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(id<SwipeActionPullViewDelegate>)delegate;
-(unsigned long long)state;
-(void)setState:(unsigned long long)arg1 ;
-(double)currentOffset;
-(BOOL)hasActions;
@end

