/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:43:59 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol TransferMailboxPickerDelegate <NSObject>
@optional
-(void)transferMailboxPickerController:(id)arg1 animateMessageToPoint:(CGPoint)arg2 inView:(id)arg3 didFinishDelegate:(id)arg4 selector:(SEL)arg5 context:(id)arg6;
-(void)transferMailboxPickerController:(id)arg1 animateMessageToThumbnailFrame:(CGRect)arg2 inView:(id)arg3 completion:(/*^block*/id)arg4;
-(id)transferMailboxPickerController:(id)arg1 viewForMessage:(id)arg2;

@required
-(void)transferMailboxPickerController:(id)arg1 didSelectMailbox:(id)arg2 withMessages:(id)arg3;
-(void)transferMailboxPickerControllerDidFinish:(id)arg1 animated:(BOOL)arg2;

@end

