/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/_UINavigationControllerPalette.h>

@class NSArray, UILabel, UIImageView, UIView, NSString;

@interface TransferMailboxPickerPalette : _UINavigationControllerPalette {

	NSArray* _senders;
	UILabel* _sendersLabel;
	UILabel* _subjectLabel;
	UIImageView* _messageThumbnailView;
	unsigned long long _messageCount;

}

@property (nonatomic,readonly) UIView * messageThumbnailView;              //@synthesize messageThumbnailView=_messageThumbnailView - In the implementation block
@property (nonatomic,copy) NSString * subject; 
@property (nonatomic,copy) NSArray * senders;                              //@synthesize senders=_senders - In the implementation block
@property (assign,nonatomic) unsigned long long messageCount;              //@synthesize messageCount=_messageCount - In the implementation block
+(double)defaultHeight;
-(void)setMessageThumbnailWithView:(id)arg1 ;
-(UIView *)messageThumbnailView;
-(CGRect)messageThumbnailViewFrame;
-(void)_drawThumbnailInContext:(CGContextRef)arg1 view:(id)arg2 frame:(CGRect)arg3 ;
-(id)_senderStringForWidth:(double)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(unsigned long long)messageCount;
-(NSString *)subject;
-(void)setSubject:(NSString *)arg1 ;
-(void)setMessageCount:(unsigned long long)arg1 ;
-(void)setSenders:(NSArray *)arg1 ;
-(NSArray *)senders;
@end

