/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UINavigationController.h>

@class AccountListController, TransferMailboxPickerController;

@interface TransferNavigationController : UINavigationController {

	AccountListController* _accountListController;
	TransferMailboxPickerController* _mailboxPickerController;
	BOOL _multipleMessages;

}

@property (nonatomic,readonly) TransferMailboxPickerController * mailboxPickerController;              //@synthesize mailboxPickerController=_mailboxPickerController - In the implementation block
-(id)transferMailboxPickerController;
-(TransferMailboxPickerController *)mailboxPickerController;
-(id)initWithMessages:(id)arg1 options:(int)arg2 ;
-(void)setMailboxPickerDelegate:(id)arg1 ;
-(id)initWithMessages:(id)arg1 ;
-(void)finishAnimated:(BOOL)arg1 ;
-(id)_disabledMailAccountForSourceAccounts:(id)arg1 ;
-(void)dealloc;
-(BOOL)shouldAutorotate;
-(void)updatePrompt;
-(void)purgeMemoryForReason:(int)arg1 ;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(BOOL)canDismiss;
@end

