/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:02 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UISplitViewControllerDelegatePrivate
@optional
-(id)_splitViewController:(id)arg1 backgroundViewForViewController:(id)arg2;
-(void)_splitViewController:(id)arg1 toggleVisibilityOfViewController:(id)arg2;
-(void)_splitViewController:(id)arg1 didUnSlideViewController:(id)arg2;
-(void)_splitViewControllerRequestsNavigation:(id)arg1;
-(BOOL)_splitViewController:(id)arg1 showViewController:(id)arg2 sender:(id)arg3;
-(BOOL)_splitViewController:(id)arg1 showDetailViewController:(id)arg2 sender:(id)arg3;
-(BOOL)_splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
-(id)_splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2;
-(id)_primaryViewControllerForCollapsingSplitViewController:(id)arg1;
-(id)_primaryViewControllerForExpandingSplitViewController:(id)arg1;
-(BOOL)_splitViewControllerIsPrimaryVisible:(id)arg1;
-(BOOL)_splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3 forRestorationOfCollapsedWhileSuspendedWithPrimaryVisible:(BOOL)arg4;
-(BOOL)_splitViewControllerShouldRestoreResponderAfterTraitCollectionTransition:(id)arg1;

@end

