/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:01 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSTimer;

@interface UpdateQueue : NSObject {

	NSMutableDictionary* _updatePrioritiesByItem;
	NSMutableDictionary* _itemInfosByPriority;
	NSTimer* _updateTimer;
	BOOL _willScheduleNextUpdate;
	BOOL _willBroadcastTopPriorities;

}
+(id)sharedQueue;
-(id)keyForItem:(id)arg1 ;
-(id)numberForUpdatePriority:(long long)arg1 ;
-(void)performNextUpdate:(id)arg1 ;
-(void)scheduleNextUpdate;
-(void)broadcastTopPriorities;
-(void)item:(id)arg1 needsUpdateAfterDelay:(double)arg2 maximumCoalescingDelay:(double)arg3 ;
-(long long)updatePriorityForItem:(id)arg1 ;
-(void)setUpdatePriority:(long long)arg1 forItem:(id)arg2 ;
-(void)dealloc;
-(id)init;
-(void)removeItem:(id)arg1 ;
-(id)itemForKey:(id)arg1 ;
@end

