/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:10 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray;

@interface COMAPPLEFELDSPARPROTOCOLCLIENTAPIErrorResponse : PBCodable <NSCopying> {

	NSMutableArray* _errors;

}

@property (nonatomic,retain) NSMutableArray * errors;              //@synthesize errors=_errors - In the implementation block
-(void)addErrors:(id)arg1 ;
-(id)errorsAtIndex:(unsigned long long)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)setErrors:(NSMutableArray *)arg1 ;
-(unsigned long long)errorsCount;
-(void)clearErrors;
-(NSMutableArray *)errors;
-(BOOL)readFrom:(id)arg1 ;
@end

