/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:10 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray, NSString;

@interface NTPBFeedItem : PBCodable <NSCopying> {

	unsigned long long _feedHalfLifeMilliseconds;
	unsigned long long _order;
	unsigned long long _publishDateMilliseconds;
	double _userFeedback;
	NSMutableArray* _allowedStorefrontIDs;
	NSString* _articleID;
	NSMutableArray* _blockedStorefrontIDs;
	NSString* _clusterID;
	NSString* _feedID;
	NSString* _sourceChannelID;
	NSString* _sourceSectionID;
	NSString* _sourceTagID;
	NSString* _sourceTopicID;
	BOOL _isExploratory;
	BOOL _isFeatureCandidate;
	BOOL _isFeatured;
	BOOL _isPinned;
	BOOL _isTopStory;
	BOOL _wasFeatured;
	SCD_Struct_NT3 _has;

}

@property (nonatomic,readonly) BOOL hasFeedID; 
@property (nonatomic,retain) NSString * feedID;                                        //@synthesize feedID=_feedID - In the implementation block
@property (nonatomic,readonly) BOOL hasArticleID; 
@property (nonatomic,retain) NSString * articleID;                                     //@synthesize articleID=_articleID - In the implementation block
@property (assign,nonatomic) BOOL hasOrder; 
@property (assign,nonatomic) unsigned long long order;                                 //@synthesize order=_order - In the implementation block
@property (assign,nonatomic) BOOL hasPublishDateMilliseconds; 
@property (assign,nonatomic) unsigned long long publishDateMilliseconds;               //@synthesize publishDateMilliseconds=_publishDateMilliseconds - In the implementation block
@property (assign,nonatomic) BOOL hasFeedHalfLifeMilliseconds; 
@property (assign,nonatomic) unsigned long long feedHalfLifeMilliseconds;              //@synthesize feedHalfLifeMilliseconds=_feedHalfLifeMilliseconds - In the implementation block
@property (assign,nonatomic) BOOL hasUserFeedback; 
@property (assign,nonatomic) double userFeedback;                                      //@synthesize userFeedback=_userFeedback - In the implementation block
@property (assign,nonatomic) BOOL hasIsFeatureCandidate; 
@property (assign,nonatomic) BOOL isFeatureCandidate;                                  //@synthesize isFeatureCandidate=_isFeatureCandidate - In the implementation block
@property (assign,nonatomic) BOOL hasIsFeatured; 
@property (assign,nonatomic) BOOL isFeatured;                                          //@synthesize isFeatured=_isFeatured - In the implementation block
@property (assign,nonatomic) BOOL hasWasFeatured; 
@property (assign,nonatomic) BOOL wasFeatured;                                         //@synthesize wasFeatured=_wasFeatured - In the implementation block
@property (assign,nonatomic) BOOL hasIsExploratory; 
@property (assign,nonatomic) BOOL isExploratory;                                       //@synthesize isExploratory=_isExploratory - In the implementation block
@property (assign,nonatomic) BOOL hasIsPinned; 
@property (assign,nonatomic) BOOL isPinned;                                            //@synthesize isPinned=_isPinned - In the implementation block
@property (nonatomic,readonly) BOOL hasClusterID; 
@property (nonatomic,retain) NSString * clusterID;                                     //@synthesize clusterID=_clusterID - In the implementation block
@property (nonatomic,retain) NSMutableArray * blockedStorefrontIDs;                    //@synthesize blockedStorefrontIDs=_blockedStorefrontIDs - In the implementation block
@property (nonatomic,retain) NSMutableArray * allowedStorefrontIDs;                    //@synthesize allowedStorefrontIDs=_allowedStorefrontIDs - In the implementation block
@property (nonatomic,readonly) BOOL hasSourceTagID; 
@property (nonatomic,retain) NSString * sourceTagID;                                   //@synthesize sourceTagID=_sourceTagID - In the implementation block
@property (nonatomic,readonly) BOOL hasSourceSectionID; 
@property (nonatomic,retain) NSString * sourceSectionID;                               //@synthesize sourceSectionID=_sourceSectionID - In the implementation block
@property (nonatomic,readonly) BOOL hasSourceChannelID; 
@property (nonatomic,retain) NSString * sourceChannelID;                               //@synthesize sourceChannelID=_sourceChannelID - In the implementation block
@property (nonatomic,readonly) BOOL hasSourceTopicID; 
@property (nonatomic,retain) NSString * sourceTopicID;                                 //@synthesize sourceTopicID=_sourceTopicID - In the implementation block
@property (assign,nonatomic) BOOL hasIsTopStory; 
@property (assign,nonatomic) BOOL isTopStory;                                          //@synthesize isTopStory=_isTopStory - In the implementation block
-(void)setFeedID:(NSString *)arg1 ;
-(void)setArticleID:(NSString *)arg1 ;
-(void)setClusterID:(NSString *)arg1 ;
-(void)setBlockedStorefrontIDs:(NSMutableArray *)arg1 ;
-(void)setAllowedStorefrontIDs:(NSMutableArray *)arg1 ;
-(void)setSourceTagID:(NSString *)arg1 ;
-(void)setSourceSectionID:(NSString *)arg1 ;
-(void)setSourceChannelID:(NSString *)arg1 ;
-(void)setSourceTopicID:(NSString *)arg1 ;
-(void)addBlockedStorefrontIDs:(id)arg1 ;
-(void)addAllowedStorefrontIDs:(id)arg1 ;
-(BOOL)hasFeedID;
-(BOOL)hasArticleID;
-(void)setPublishDateMilliseconds:(unsigned long long)arg1 ;
-(void)setHasPublishDateMilliseconds:(BOOL)arg1 ;
-(BOOL)hasPublishDateMilliseconds;
-(void)setFeedHalfLifeMilliseconds:(unsigned long long)arg1 ;
-(void)setHasFeedHalfLifeMilliseconds:(BOOL)arg1 ;
-(BOOL)hasFeedHalfLifeMilliseconds;
-(void)setUserFeedback:(double)arg1 ;
-(void)setHasUserFeedback:(BOOL)arg1 ;
-(BOOL)hasUserFeedback;
-(void)setIsFeatureCandidate:(BOOL)arg1 ;
-(void)setHasIsFeatureCandidate:(BOOL)arg1 ;
-(BOOL)hasIsFeatureCandidate;
-(void)setIsFeatured:(BOOL)arg1 ;
-(void)setHasIsFeatured:(BOOL)arg1 ;
-(BOOL)hasIsFeatured;
-(void)setWasFeatured:(BOOL)arg1 ;
-(void)setHasWasFeatured:(BOOL)arg1 ;
-(BOOL)hasWasFeatured;
-(void)setIsExploratory:(BOOL)arg1 ;
-(void)setHasIsExploratory:(BOOL)arg1 ;
-(BOOL)hasIsExploratory;
-(void)setHasIsPinned:(BOOL)arg1 ;
-(BOOL)hasIsPinned;
-(BOOL)hasClusterID;
-(void)clearBlockedStorefrontIDs;
-(unsigned long long)blockedStorefrontIDsCount;
-(id)blockedStorefrontIDsAtIndex:(unsigned long long)arg1 ;
-(void)clearAllowedStorefrontIDs;
-(unsigned long long)allowedStorefrontIDsCount;
-(id)allowedStorefrontIDsAtIndex:(unsigned long long)arg1 ;
-(BOOL)hasSourceTagID;
-(BOOL)hasSourceSectionID;
-(BOOL)hasSourceChannelID;
-(BOOL)hasSourceTopicID;
-(void)setIsTopStory:(BOOL)arg1 ;
-(void)setHasIsTopStory:(BOOL)arg1 ;
-(BOOL)hasIsTopStory;
-(NSString *)feedID;
-(NSString *)articleID;
-(unsigned long long)publishDateMilliseconds;
-(unsigned long long)feedHalfLifeMilliseconds;
-(double)userFeedback;
-(BOOL)isFeatureCandidate;
-(BOOL)wasFeatured;
-(BOOL)isExploratory;
-(NSString *)clusterID;
-(NSMutableArray *)blockedStorefrontIDs;
-(NSMutableArray *)allowedStorefrontIDs;
-(NSString *)sourceTagID;
-(NSString *)sourceSectionID;
-(NSString *)sourceChannelID;
-(NSString *)sourceTopicID;
-(BOOL)isTopStory;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)isPinned;
-(id)dictionaryRepresentation;
-(void)setOrder:(unsigned long long)arg1 ;
-(unsigned long long)order;
-(void)mergeFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)setIsPinned:(BOOL)arg1 ;
-(BOOL)isFeatured;
-(void)setHasOrder:(BOOL)arg1 ;
-(BOOL)hasOrder;
-(BOOL)readFrom:(id)arg1 ;
@end

