/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:11 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NTPBBinningConfig;

@interface NTPBPersonalizationConfig : PBCodable <NSCopying> {

	NTPBBinningConfig* _binningConfig;

}

@property (nonatomic,readonly) BOOL hasBinningConfig; 
@property (nonatomic,retain) NTPBBinningConfig * binningConfig;              //@synthesize binningConfig=_binningConfig - In the implementation block
-(void)setBinningConfig:(NTPBBinningConfig *)arg1 ;
-(BOOL)hasBinningConfig;
-(NTPBBinningConfig *)binningConfig;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
@end

