/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:10 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSData;

@interface NTPBSession : PBCodable <NSCopying> {

	long long _appBuild;
	long long _lastAppOpenDate;
	long long _userStartDate;
	NSString* _appVersion;
	NSString* _carrier;
	int _cellularRadioAccessTechnology;
	NSString* _countryCode;
	NSString* _deviceModel;
	NSString* _devicePlatform;
	NSString* _languageCode;
	int _osInstallVariant;
	NSString* _osVersion;
	NSString* _previousAppVersion;
	NSString* _previousOsVersion;
	int _reachabilityStatus;
	NSData* _sessionId;
	int _textSize;
	NSString* _userId;
	NSString* _userStorefrontId;
	int _utcOffset;
	BOOL _isNewUser;
	BOOL _runningObsolete;
	BOOL _signedIntoIcloud;
	BOOL _upgradedFromObsolete;
	SCD_Struct_NT11 _has;

}

@property (nonatomic,readonly) BOOL hasDeviceModel; 
@property (nonatomic,retain) NSString * deviceModel;                             //@synthesize deviceModel=_deviceModel - In the implementation block
@property (nonatomic,readonly) BOOL hasDevicePlatform; 
@property (nonatomic,retain) NSString * devicePlatform;                          //@synthesize devicePlatform=_devicePlatform - In the implementation block
@property (nonatomic,readonly) BOOL hasOsVersion; 
@property (nonatomic,retain) NSString * osVersion;                               //@synthesize osVersion=_osVersion - In the implementation block
@property (nonatomic,readonly) BOOL hasAppVersion; 
@property (nonatomic,retain) NSString * appVersion;                              //@synthesize appVersion=_appVersion - In the implementation block
@property (assign,nonatomic) BOOL hasAppBuild; 
@property (assign,nonatomic) long long appBuild;                                 //@synthesize appBuild=_appBuild - In the implementation block
@property (assign,nonatomic) BOOL hasUtcOffset; 
@property (assign,nonatomic) int utcOffset;                                      //@synthesize utcOffset=_utcOffset - In the implementation block
@property (nonatomic,readonly) BOOL hasCountryCode; 
@property (nonatomic,retain) NSString * countryCode;                             //@synthesize countryCode=_countryCode - In the implementation block
@property (nonatomic,readonly) BOOL hasLanguageCode; 
@property (nonatomic,retain) NSString * languageCode;                            //@synthesize languageCode=_languageCode - In the implementation block
@property (nonatomic,readonly) BOOL hasCarrier; 
@property (nonatomic,retain) NSString * carrier;                                 //@synthesize carrier=_carrier - In the implementation block
@property (assign,nonatomic) BOOL hasReachabilityStatus; 
@property (assign,nonatomic) int reachabilityStatus;                             //@synthesize reachabilityStatus=_reachabilityStatus - In the implementation block
@property (assign,nonatomic) BOOL hasCellularRadioAccessTechnology; 
@property (assign,nonatomic) int cellularRadioAccessTechnology;                  //@synthesize cellularRadioAccessTechnology=_cellularRadioAccessTechnology - In the implementation block
@property (assign,nonatomic) BOOL hasTextSize; 
@property (assign,nonatomic) int textSize;                                       //@synthesize textSize=_textSize - In the implementation block
@property (nonatomic,readonly) BOOL hasSessionId; 
@property (nonatomic,retain) NSData * sessionId;                                 //@synthesize sessionId=_sessionId - In the implementation block
@property (nonatomic,readonly) BOOL hasUserId; 
@property (nonatomic,retain) NSString * userId;                                  //@synthesize userId=_userId - In the implementation block
@property (nonatomic,readonly) BOOL hasUserStorefrontId; 
@property (nonatomic,retain) NSString * userStorefrontId;                        //@synthesize userStorefrontId=_userStorefrontId - In the implementation block
@property (assign,nonatomic) BOOL hasIsNewUser; 
@property (assign,nonatomic) BOOL isNewUser;                                     //@synthesize isNewUser=_isNewUser - In the implementation block
@property (assign,nonatomic) BOOL hasUserStartDate; 
@property (assign,nonatomic) long long userStartDate;                            //@synthesize userStartDate=_userStartDate - In the implementation block
@property (assign,nonatomic) BOOL hasLastAppOpenDate; 
@property (assign,nonatomic) long long lastAppOpenDate;                          //@synthesize lastAppOpenDate=_lastAppOpenDate - In the implementation block
@property (assign,nonatomic) BOOL hasRunningObsolete; 
@property (assign,nonatomic) BOOL runningObsolete;                               //@synthesize runningObsolete=_runningObsolete - In the implementation block
@property (assign,nonatomic) BOOL hasUpgradedFromObsolete; 
@property (assign,nonatomic) BOOL upgradedFromObsolete;                          //@synthesize upgradedFromObsolete=_upgradedFromObsolete - In the implementation block
@property (nonatomic,readonly) BOOL hasPreviousAppVersion; 
@property (nonatomic,retain) NSString * previousAppVersion;                      //@synthesize previousAppVersion=_previousAppVersion - In the implementation block
@property (nonatomic,readonly) BOOL hasPreviousOsVersion; 
@property (nonatomic,retain) NSString * previousOsVersion;                       //@synthesize previousOsVersion=_previousOsVersion - In the implementation block
@property (assign,nonatomic) BOOL hasSignedIntoIcloud; 
@property (assign,nonatomic) BOOL signedIntoIcloud;                              //@synthesize signedIntoIcloud=_signedIntoIcloud - In the implementation block
@property (assign,nonatomic) BOOL hasOsInstallVariant; 
@property (assign,nonatomic) int osInstallVariant;                               //@synthesize osInstallVariant=_osInstallVariant - In the implementation block
-(void)setUserStorefrontId:(NSString *)arg1 ;
-(BOOL)hasUserStorefrontId;
-(NSString *)userStorefrontId;
-(void)setDevicePlatform:(NSString *)arg1 ;
-(void)setCarrier:(NSString *)arg1 ;
-(void)setPreviousAppVersion:(NSString *)arg1 ;
-(void)setPreviousOsVersion:(NSString *)arg1 ;
-(BOOL)hasDevicePlatform;
-(BOOL)hasAppVersion;
-(void)setAppBuild:(long long)arg1 ;
-(void)setHasAppBuild:(BOOL)arg1 ;
-(BOOL)hasAppBuild;
-(void)setUtcOffset:(int)arg1 ;
-(void)setHasUtcOffset:(BOOL)arg1 ;
-(BOOL)hasUtcOffset;
-(BOOL)hasCarrier;
-(void)setReachabilityStatus:(int)arg1 ;
-(void)setHasReachabilityStatus:(BOOL)arg1 ;
-(BOOL)hasReachabilityStatus;
-(int)cellularRadioAccessTechnology;
-(void)setCellularRadioAccessTechnology:(int)arg1 ;
-(void)setHasCellularRadioAccessTechnology:(BOOL)arg1 ;
-(BOOL)hasCellularRadioAccessTechnology;
-(void)setTextSize:(int)arg1 ;
-(void)setHasTextSize:(BOOL)arg1 ;
-(BOOL)hasTextSize;
-(void)setIsNewUser:(BOOL)arg1 ;
-(void)setHasIsNewUser:(BOOL)arg1 ;
-(BOOL)hasIsNewUser;
-(void)setUserStartDate:(long long)arg1 ;
-(void)setHasUserStartDate:(BOOL)arg1 ;
-(BOOL)hasUserStartDate;
-(void)setLastAppOpenDate:(long long)arg1 ;
-(void)setHasLastAppOpenDate:(BOOL)arg1 ;
-(BOOL)hasLastAppOpenDate;
-(void)setRunningObsolete:(BOOL)arg1 ;
-(void)setHasRunningObsolete:(BOOL)arg1 ;
-(BOOL)hasRunningObsolete;
-(void)setUpgradedFromObsolete:(BOOL)arg1 ;
-(void)setHasUpgradedFromObsolete:(BOOL)arg1 ;
-(BOOL)hasUpgradedFromObsolete;
-(BOOL)hasPreviousAppVersion;
-(BOOL)hasPreviousOsVersion;
-(void)setSignedIntoIcloud:(BOOL)arg1 ;
-(void)setHasSignedIntoIcloud:(BOOL)arg1 ;
-(BOOL)hasSignedIntoIcloud;
-(int)osInstallVariant;
-(void)setOsInstallVariant:(int)arg1 ;
-(void)setHasOsInstallVariant:(BOOL)arg1 ;
-(BOOL)hasOsInstallVariant;
-(NSString *)devicePlatform;
-(long long)appBuild;
-(int)utcOffset;
-(NSString *)carrier;
-(BOOL)isNewUser;
-(long long)userStartDate;
-(long long)lastAppOpenDate;
-(BOOL)runningObsolete;
-(BOOL)upgradedFromObsolete;
-(NSString *)previousAppVersion;
-(NSString *)previousOsVersion;
-(BOOL)signedIntoIcloud;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(int)textSize;
-(id)dictionaryRepresentation;
-(NSString *)languageCode;
-(void)mergeFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)hasLanguageCode;
-(void)setLanguageCode:(NSString *)arg1 ;
-(void)setSessionId:(NSData *)arg1 ;
-(NSData *)sessionId;
-(BOOL)hasSessionId;
-(void)setCountryCode:(NSString *)arg1 ;
-(NSString *)countryCode;
-(BOOL)hasCountryCode;
-(void)setOsVersion:(NSString *)arg1 ;
-(BOOL)hasOsVersion;
-(NSString *)osVersion;
-(NSString *)appVersion;
-(void)setAppVersion:(NSString *)arg1 ;
-(int)reachabilityStatus;
-(void)setUserId:(NSString *)arg1 ;
-(BOOL)hasUserId;
-(NSString *)userId;
-(NSString *)deviceModel;
-(void)setDeviceModel:(NSString *)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(BOOL)hasDeviceModel;
@end

