/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:11 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface NTPBLayoutAttributes : PBCodable <NSCopying> {

	long long _borderSpecification;
	long long _columnSpan;
	long long _imagePosition;
	long long _indexPathItem;
	long long _indexPathSection;
	long long _rowSpan;
	int _accessoryViewHeight;
	float _accessoryViewWidth;
	float _accessoryViewX;
	float _accessoryViewY;
	float _backgroundColorInsetBottom;
	float _backgroundColorInsetLeft;
	float _backgroundColorInsetRight;
	float _backgroundColorInsetTop;
	NSString* _bylineFontName;
	float _bylineFontSize;
	NSString* _cachedExcerpt;
	int _cellType;
	float _contentInsetBottom;
	float _contentInsetLeft;
	float _contentInsetRight;
	float _contentInsetTop;
	int _contentType;
	NSString* _decorationKind;
	NSString* _excerptFontName;
	float _excerptFontSize;
	float _excerptFrameHeight;
	float _excerptFrameWidth;
	float _excerptFrameX;
	float _excerptFrameY;
	float _excerptLineHeight;
	float _frameHeight;
	float _frameWidth;
	float _frameX;
	float _frameY;
	float _imageViewFrameHeight;
	float _imageViewFrameWidth;
	float _imageViewFrameX;
	float _imageViewFrameY;
	float _layoutType;
	float _logoImageFrameHeight;
	float _logoImageFrameWidth;
	float _logoImageFrameX;
	float _logoImageFrameY;
	NSString* _subtitleFontName;
	float _subtitleFontSize;
	float _subtitleFrameHeight;
	float _subtitleFrameWidth;
	float _subtitleFrameX;
	float _subtitleFrameY;
	float _subtitleLineHeight;
	int _textAlignment;
	NSString* _titleFontName;
	float _titleFontSize;
	float _titleFrameHeight;
	float _titleFrameWidth;
	float _titleFrameX;
	float _titleFrameY;
	float _titleLineHeight;
	float _verticalWhitespace;
	BOOL _hasVideo;
	SCD_Struct_NT15 _has;

}

@property (assign,nonatomic) int contentType;                                 //@synthesize contentType=_contentType - In the implementation block
@property (assign,nonatomic) long long indexPathSection;                      //@synthesize indexPathSection=_indexPathSection - In the implementation block
@property (assign,nonatomic) long long indexPathItem;                         //@synthesize indexPathItem=_indexPathItem - In the implementation block
@property (assign,nonatomic) float frameX;                                    //@synthesize frameX=_frameX - In the implementation block
@property (assign,nonatomic) float frameY;                                    //@synthesize frameY=_frameY - In the implementation block
@property (assign,nonatomic) float frameWidth;                                //@synthesize frameWidth=_frameWidth - In the implementation block
@property (assign,nonatomic) float frameHeight;                               //@synthesize frameHeight=_frameHeight - In the implementation block
@property (assign,nonatomic) BOOL hasColumnSpan; 
@property (assign,nonatomic) long long columnSpan;                            //@synthesize columnSpan=_columnSpan - In the implementation block
@property (assign,nonatomic) BOOL hasImagePosition; 
@property (assign,nonatomic) long long imagePosition;                         //@synthesize imagePosition=_imagePosition - In the implementation block
@property (assign,nonatomic) BOOL hasImageViewFrameX; 
@property (assign,nonatomic) float imageViewFrameX;                           //@synthesize imageViewFrameX=_imageViewFrameX - In the implementation block
@property (assign,nonatomic) BOOL hasImageViewFrameY; 
@property (assign,nonatomic) float imageViewFrameY;                           //@synthesize imageViewFrameY=_imageViewFrameY - In the implementation block
@property (assign,nonatomic) BOOL hasImageViewFrameWidth; 
@property (assign,nonatomic) float imageViewFrameWidth;                       //@synthesize imageViewFrameWidth=_imageViewFrameWidth - In the implementation block
@property (assign,nonatomic) BOOL hasImageViewFrameHeight; 
@property (assign,nonatomic) float imageViewFrameHeight;                      //@synthesize imageViewFrameHeight=_imageViewFrameHeight - In the implementation block
@property (assign,nonatomic) BOOL hasTitleFrameX; 
@property (assign,nonatomic) float titleFrameX;                               //@synthesize titleFrameX=_titleFrameX - In the implementation block
@property (assign,nonatomic) BOOL hasTitleFrameY; 
@property (assign,nonatomic) float titleFrameY;                               //@synthesize titleFrameY=_titleFrameY - In the implementation block
@property (assign,nonatomic) BOOL hasTitleFrameWidth; 
@property (assign,nonatomic) float titleFrameWidth;                           //@synthesize titleFrameWidth=_titleFrameWidth - In the implementation block
@property (assign,nonatomic) BOOL hasTitleFrameHeight; 
@property (assign,nonatomic) float titleFrameHeight;                          //@synthesize titleFrameHeight=_titleFrameHeight - In the implementation block
@property (assign,nonatomic) BOOL hasLogoImageFrameX; 
@property (assign,nonatomic) float logoImageFrameX;                           //@synthesize logoImageFrameX=_logoImageFrameX - In the implementation block
@property (assign,nonatomic) BOOL hasLogoImageFrameY; 
@property (assign,nonatomic) float logoImageFrameY;                           //@synthesize logoImageFrameY=_logoImageFrameY - In the implementation block
@property (assign,nonatomic) BOOL hasLogoImageFrameWidth; 
@property (assign,nonatomic) float logoImageFrameWidth;                       //@synthesize logoImageFrameWidth=_logoImageFrameWidth - In the implementation block
@property (assign,nonatomic) BOOL hasLogoImageFrameHeight; 
@property (assign,nonatomic) float logoImageFrameHeight;                      //@synthesize logoImageFrameHeight=_logoImageFrameHeight - In the implementation block
@property (assign,nonatomic) BOOL hasExcerptFrameX; 
@property (assign,nonatomic) float excerptFrameX;                             //@synthesize excerptFrameX=_excerptFrameX - In the implementation block
@property (assign,nonatomic) BOOL hasExcerptFrameY; 
@property (assign,nonatomic) float excerptFrameY;                             //@synthesize excerptFrameY=_excerptFrameY - In the implementation block
@property (assign,nonatomic) BOOL hasExcerptFrameWidth; 
@property (assign,nonatomic) float excerptFrameWidth;                         //@synthesize excerptFrameWidth=_excerptFrameWidth - In the implementation block
@property (assign,nonatomic) BOOL hasExcerptFrameHeight; 
@property (assign,nonatomic) float excerptFrameHeight;                        //@synthesize excerptFrameHeight=_excerptFrameHeight - In the implementation block
@property (nonatomic,readonly) BOOL hasDecorationKind; 
@property (nonatomic,retain) NSString * decorationKind;                       //@synthesize decorationKind=_decorationKind - In the implementation block
@property (nonatomic,readonly) BOOL hasCachedExcerpt; 
@property (nonatomic,retain) NSString * cachedExcerpt;                        //@synthesize cachedExcerpt=_cachedExcerpt - In the implementation block
@property (assign,nonatomic) BOOL hasTitleFontSize; 
@property (assign,nonatomic) float titleFontSize;                             //@synthesize titleFontSize=_titleFontSize - In the implementation block
@property (nonatomic,readonly) BOOL hasTitleFontName; 
@property (nonatomic,retain) NSString * titleFontName;                        //@synthesize titleFontName=_titleFontName - In the implementation block
@property (assign,nonatomic) BOOL hasTitleLineHeight; 
@property (assign,nonatomic) float titleLineHeight;                           //@synthesize titleLineHeight=_titleLineHeight - In the implementation block
@property (assign,nonatomic) BOOL hasExcerptFontSize; 
@property (assign,nonatomic) float excerptFontSize;                           //@synthesize excerptFontSize=_excerptFontSize - In the implementation block
@property (nonatomic,readonly) BOOL hasExcerptFontName; 
@property (nonatomic,retain) NSString * excerptFontName;                      //@synthesize excerptFontName=_excerptFontName - In the implementation block
@property (assign,nonatomic) BOOL hasExcerptLineHeight; 
@property (assign,nonatomic) float excerptLineHeight;                         //@synthesize excerptLineHeight=_excerptLineHeight - In the implementation block
@property (assign,nonatomic) BOOL hasBylineFontSize; 
@property (assign,nonatomic) float bylineFontSize;                            //@synthesize bylineFontSize=_bylineFontSize - In the implementation block
@property (nonatomic,readonly) BOOL hasBylineFontName; 
@property (nonatomic,retain) NSString * bylineFontName;                       //@synthesize bylineFontName=_bylineFontName - In the implementation block
@property (assign,nonatomic) BOOL hasHasVideo; 
@property (assign,nonatomic) BOOL hasVideo;                                   //@synthesize hasVideo=_hasVideo - In the implementation block
@property (assign,nonatomic) BOOL hasBorderSpecification; 
@property (assign,nonatomic) long long borderSpecification;                   //@synthesize borderSpecification=_borderSpecification - In the implementation block
@property (assign,nonatomic) BOOL hasTextAlignment; 
@property (assign,nonatomic) int textAlignment;                               //@synthesize textAlignment=_textAlignment - In the implementation block
@property (assign,nonatomic) BOOL hasSubtitleFrameX; 
@property (assign,nonatomic) float subtitleFrameX;                            //@synthesize subtitleFrameX=_subtitleFrameX - In the implementation block
@property (assign,nonatomic) BOOL hasSubtitleFrameY; 
@property (assign,nonatomic) float subtitleFrameY;                            //@synthesize subtitleFrameY=_subtitleFrameY - In the implementation block
@property (assign,nonatomic) BOOL hasSubtitleFrameWidth; 
@property (assign,nonatomic) float subtitleFrameWidth;                        //@synthesize subtitleFrameWidth=_subtitleFrameWidth - In the implementation block
@property (assign,nonatomic) BOOL hasSubtitleFrameHeight; 
@property (assign,nonatomic) float subtitleFrameHeight;                       //@synthesize subtitleFrameHeight=_subtitleFrameHeight - In the implementation block
@property (assign,nonatomic) BOOL hasSubtitleLineHeight; 
@property (assign,nonatomic) float subtitleLineHeight;                        //@synthesize subtitleLineHeight=_subtitleLineHeight - In the implementation block
@property (assign,nonatomic) BOOL hasSubtitleFontSize; 
@property (assign,nonatomic) float subtitleFontSize;                          //@synthesize subtitleFontSize=_subtitleFontSize - In the implementation block
@property (nonatomic,readonly) BOOL hasSubtitleFontName; 
@property (nonatomic,retain) NSString * subtitleFontName;                     //@synthesize subtitleFontName=_subtitleFontName - In the implementation block
@property (assign,nonatomic) BOOL hasLayoutType; 
@property (assign,nonatomic) float layoutType;                                //@synthesize layoutType=_layoutType - In the implementation block
@property (assign,nonatomic) BOOL hasContentInsetTop; 
@property (assign,nonatomic) float contentInsetTop;                           //@synthesize contentInsetTop=_contentInsetTop - In the implementation block
@property (assign,nonatomic) BOOL hasContentInsetLeft; 
@property (assign,nonatomic) float contentInsetLeft;                          //@synthesize contentInsetLeft=_contentInsetLeft - In the implementation block
@property (assign,nonatomic) BOOL hasContentInsetBottom; 
@property (assign,nonatomic) float contentInsetBottom;                        //@synthesize contentInsetBottom=_contentInsetBottom - In the implementation block
@property (assign,nonatomic) BOOL hasContentInsetRight; 
@property (assign,nonatomic) float contentInsetRight;                         //@synthesize contentInsetRight=_contentInsetRight - In the implementation block
@property (assign,nonatomic) BOOL hasVerticalWhitespace; 
@property (assign,nonatomic) float verticalWhitespace;                        //@synthesize verticalWhitespace=_verticalWhitespace - In the implementation block
@property (assign,nonatomic) BOOL hasRowSpan; 
@property (assign,nonatomic) long long rowSpan;                               //@synthesize rowSpan=_rowSpan - In the implementation block
@property (assign,nonatomic) BOOL hasAccessoryViewX; 
@property (assign,nonatomic) float accessoryViewX;                            //@synthesize accessoryViewX=_accessoryViewX - In the implementation block
@property (assign,nonatomic) BOOL hasAccessoryViewWidth; 
@property (assign,nonatomic) float accessoryViewWidth;                        //@synthesize accessoryViewWidth=_accessoryViewWidth - In the implementation block
@property (assign,nonatomic) BOOL hasAccessoryViewY; 
@property (assign,nonatomic) float accessoryViewY;                            //@synthesize accessoryViewY=_accessoryViewY - In the implementation block
@property (assign,nonatomic) BOOL hasAccessoryViewHeight; 
@property (assign,nonatomic) int accessoryViewHeight;                         //@synthesize accessoryViewHeight=_accessoryViewHeight - In the implementation block
@property (assign,nonatomic) BOOL hasBackgroundColorInsetTop; 
@property (assign,nonatomic) float backgroundColorInsetTop;                   //@synthesize backgroundColorInsetTop=_backgroundColorInsetTop - In the implementation block
@property (assign,nonatomic) BOOL hasBackgroundColorInsetLeft; 
@property (assign,nonatomic) float backgroundColorInsetLeft;                  //@synthesize backgroundColorInsetLeft=_backgroundColorInsetLeft - In the implementation block
@property (assign,nonatomic) BOOL hasBackgroundColorInsetBottom; 
@property (assign,nonatomic) float backgroundColorInsetBottom;                //@synthesize backgroundColorInsetBottom=_backgroundColorInsetBottom - In the implementation block
@property (assign,nonatomic) BOOL hasBackgroundColorInsetRight; 
@property (assign,nonatomic) float backgroundColorInsetRight;                 //@synthesize backgroundColorInsetRight=_backgroundColorInsetRight - In the implementation block
@property (assign,nonatomic) BOOL hasCellType; 
@property (assign,nonatomic) int cellType;                                    //@synthesize cellType=_cellType - In the implementation block
-(void)setDecorationKind:(NSString *)arg1 ;
-(void)setCachedExcerpt:(NSString *)arg1 ;
-(void)setTitleFontName:(NSString *)arg1 ;
-(void)setExcerptFontName:(NSString *)arg1 ;
-(void)setBylineFontName:(NSString *)arg1 ;
-(void)setSubtitleFontName:(NSString *)arg1 ;
-(void)setHasColumnSpan:(BOOL)arg1 ;
-(BOOL)hasColumnSpan;
-(void)setImagePosition:(long long)arg1 ;
-(void)setHasImagePosition:(BOOL)arg1 ;
-(BOOL)hasImagePosition;
-(void)setImageViewFrameX:(float)arg1 ;
-(void)setHasImageViewFrameX:(BOOL)arg1 ;
-(BOOL)hasImageViewFrameX;
-(void)setImageViewFrameY:(float)arg1 ;
-(void)setHasImageViewFrameY:(BOOL)arg1 ;
-(BOOL)hasImageViewFrameY;
-(void)setImageViewFrameWidth:(float)arg1 ;
-(void)setHasImageViewFrameWidth:(BOOL)arg1 ;
-(BOOL)hasImageViewFrameWidth;
-(void)setImageViewFrameHeight:(float)arg1 ;
-(void)setHasImageViewFrameHeight:(BOOL)arg1 ;
-(BOOL)hasImageViewFrameHeight;
-(void)setTitleFrameX:(float)arg1 ;
-(void)setHasTitleFrameX:(BOOL)arg1 ;
-(BOOL)hasTitleFrameX;
-(void)setTitleFrameY:(float)arg1 ;
-(void)setHasTitleFrameY:(BOOL)arg1 ;
-(BOOL)hasTitleFrameY;
-(void)setTitleFrameWidth:(float)arg1 ;
-(void)setHasTitleFrameWidth:(BOOL)arg1 ;
-(BOOL)hasTitleFrameWidth;
-(void)setTitleFrameHeight:(float)arg1 ;
-(void)setHasTitleFrameHeight:(BOOL)arg1 ;
-(BOOL)hasTitleFrameHeight;
-(void)setLogoImageFrameX:(float)arg1 ;
-(void)setHasLogoImageFrameX:(BOOL)arg1 ;
-(BOOL)hasLogoImageFrameX;
-(void)setLogoImageFrameY:(float)arg1 ;
-(void)setHasLogoImageFrameY:(BOOL)arg1 ;
-(BOOL)hasLogoImageFrameY;
-(void)setLogoImageFrameWidth:(float)arg1 ;
-(void)setHasLogoImageFrameWidth:(BOOL)arg1 ;
-(BOOL)hasLogoImageFrameWidth;
-(void)setLogoImageFrameHeight:(float)arg1 ;
-(void)setHasLogoImageFrameHeight:(BOOL)arg1 ;
-(BOOL)hasLogoImageFrameHeight;
-(void)setExcerptFrameX:(float)arg1 ;
-(void)setHasExcerptFrameX:(BOOL)arg1 ;
-(BOOL)hasExcerptFrameX;
-(void)setExcerptFrameY:(float)arg1 ;
-(void)setHasExcerptFrameY:(BOOL)arg1 ;
-(BOOL)hasExcerptFrameY;
-(void)setExcerptFrameWidth:(float)arg1 ;
-(void)setHasExcerptFrameWidth:(BOOL)arg1 ;
-(BOOL)hasExcerptFrameWidth;
-(void)setExcerptFrameHeight:(float)arg1 ;
-(void)setHasExcerptFrameHeight:(BOOL)arg1 ;
-(BOOL)hasExcerptFrameHeight;
-(BOOL)hasDecorationKind;
-(BOOL)hasCachedExcerpt;
-(void)setTitleFontSize:(float)arg1 ;
-(void)setHasTitleFontSize:(BOOL)arg1 ;
-(BOOL)hasTitleFontSize;
-(BOOL)hasTitleFontName;
-(void)setHasTitleLineHeight:(BOOL)arg1 ;
-(BOOL)hasTitleLineHeight;
-(void)setExcerptFontSize:(float)arg1 ;
-(void)setHasExcerptFontSize:(BOOL)arg1 ;
-(BOOL)hasExcerptFontSize;
-(BOOL)hasExcerptFontName;
-(void)setExcerptLineHeight:(float)arg1 ;
-(void)setHasExcerptLineHeight:(BOOL)arg1 ;
-(BOOL)hasExcerptLineHeight;
-(void)setBylineFontSize:(float)arg1 ;
-(void)setHasBylineFontSize:(BOOL)arg1 ;
-(BOOL)hasBylineFontSize;
-(BOOL)hasBylineFontName;
-(void)setBorderSpecification:(long long)arg1 ;
-(void)setHasBorderSpecification:(BOOL)arg1 ;
-(BOOL)hasBorderSpecification;
-(void)setHasTextAlignment:(BOOL)arg1 ;
-(BOOL)hasTextAlignment;
-(void)setSubtitleFrameX:(float)arg1 ;
-(void)setHasSubtitleFrameX:(BOOL)arg1 ;
-(BOOL)hasSubtitleFrameX;
-(void)setSubtitleFrameY:(float)arg1 ;
-(void)setHasSubtitleFrameY:(BOOL)arg1 ;
-(BOOL)hasSubtitleFrameY;
-(void)setSubtitleFrameWidth:(float)arg1 ;
-(void)setHasSubtitleFrameWidth:(BOOL)arg1 ;
-(BOOL)hasSubtitleFrameWidth;
-(void)setSubtitleFrameHeight:(float)arg1 ;
-(void)setHasSubtitleFrameHeight:(BOOL)arg1 ;
-(BOOL)hasSubtitleFrameHeight;
-(void)setHasSubtitleLineHeight:(BOOL)arg1 ;
-(BOOL)hasSubtitleLineHeight;
-(void)setSubtitleFontSize:(float)arg1 ;
-(void)setHasSubtitleFontSize:(BOOL)arg1 ;
-(BOOL)hasSubtitleFontSize;
-(BOOL)hasSubtitleFontName;
-(void)setHasLayoutType:(BOOL)arg1 ;
-(BOOL)hasLayoutType;
-(void)setContentInsetTop:(float)arg1 ;
-(void)setHasContentInsetTop:(BOOL)arg1 ;
-(BOOL)hasContentInsetTop;
-(void)setContentInsetLeft:(float)arg1 ;
-(void)setHasContentInsetLeft:(BOOL)arg1 ;
-(BOOL)hasContentInsetLeft;
-(void)setContentInsetBottom:(float)arg1 ;
-(void)setHasContentInsetBottom:(BOOL)arg1 ;
-(BOOL)hasContentInsetBottom;
-(void)setContentInsetRight:(float)arg1 ;
-(void)setHasContentInsetRight:(BOOL)arg1 ;
-(BOOL)hasContentInsetRight;
-(void)setVerticalWhitespace:(float)arg1 ;
-(void)setHasVerticalWhitespace:(BOOL)arg1 ;
-(BOOL)hasVerticalWhitespace;
-(void)setHasRowSpan:(BOOL)arg1 ;
-(BOOL)hasRowSpan;
-(void)setAccessoryViewX:(float)arg1 ;
-(void)setHasAccessoryViewX:(BOOL)arg1 ;
-(BOOL)hasAccessoryViewX;
-(void)setAccessoryViewWidth:(float)arg1 ;
-(void)setHasAccessoryViewWidth:(BOOL)arg1 ;
-(BOOL)hasAccessoryViewWidth;
-(void)setAccessoryViewY:(float)arg1 ;
-(void)setHasAccessoryViewY:(BOOL)arg1 ;
-(BOOL)hasAccessoryViewY;
-(void)setAccessoryViewHeight:(int)arg1 ;
-(void)setHasAccessoryViewHeight:(BOOL)arg1 ;
-(BOOL)hasAccessoryViewHeight;
-(void)setBackgroundColorInsetTop:(float)arg1 ;
-(void)setHasBackgroundColorInsetTop:(BOOL)arg1 ;
-(BOOL)hasBackgroundColorInsetTop;
-(void)setBackgroundColorInsetLeft:(float)arg1 ;
-(void)setHasBackgroundColorInsetLeft:(BOOL)arg1 ;
-(BOOL)hasBackgroundColorInsetLeft;
-(void)setBackgroundColorInsetBottom:(float)arg1 ;
-(void)setHasBackgroundColorInsetBottom:(BOOL)arg1 ;
-(BOOL)hasBackgroundColorInsetBottom;
-(void)setBackgroundColorInsetRight:(float)arg1 ;
-(void)setHasBackgroundColorInsetRight:(BOOL)arg1 ;
-(BOOL)hasBackgroundColorInsetRight;
-(void)setHasCellType:(BOOL)arg1 ;
-(BOOL)hasCellType;
-(long long)indexPathSection;
-(void)setIndexPathSection:(long long)arg1 ;
-(long long)indexPathItem;
-(void)setIndexPathItem:(long long)arg1 ;
-(float)frameX;
-(float)frameY;
-(float)frameHeight;
-(float)imageViewFrameX;
-(float)imageViewFrameY;
-(float)imageViewFrameWidth;
-(float)imageViewFrameHeight;
-(float)titleFrameX;
-(float)titleFrameY;
-(float)titleFrameWidth;
-(float)titleFrameHeight;
-(float)logoImageFrameX;
-(float)logoImageFrameY;
-(float)logoImageFrameWidth;
-(float)logoImageFrameHeight;
-(float)excerptFrameX;
-(float)excerptFrameY;
-(float)excerptFrameWidth;
-(float)excerptFrameHeight;
-(NSString *)decorationKind;
-(NSString *)cachedExcerpt;
-(NSString *)titleFontName;
-(float)excerptFontSize;
-(NSString *)excerptFontName;
-(float)excerptLineHeight;
-(float)bylineFontSize;
-(NSString *)bylineFontName;
-(long long)borderSpecification;
-(float)subtitleFrameX;
-(float)subtitleFrameY;
-(float)subtitleFrameWidth;
-(float)subtitleFrameHeight;
-(float)subtitleFontSize;
-(NSString *)subtitleFontName;
-(float)contentInsetTop;
-(float)contentInsetLeft;
-(float)contentInsetBottom;
-(float)contentInsetRight;
-(float)verticalWhitespace;
-(float)accessoryViewX;
-(float)accessoryViewWidth;
-(float)accessoryViewY;
-(float)backgroundColorInsetTop;
-(float)backgroundColorInsetLeft;
-(float)backgroundColorInsetBottom;
-(float)backgroundColorInsetRight;
-(void)setContentType:(int)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)setTextAlignment:(int)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(int)contentType;
-(int)textAlignment;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)setColumnSpan:(long long)arg1 ;
-(int)cellType;
-(void)setCellType:(int)arg1 ;
-(void)setHasVideo:(BOOL)arg1 ;
-(void)setHasHasVideo:(BOOL)arg1 ;
-(BOOL)hasHasVideo;
-(BOOL)hasVideo;
-(void)setFrameX:(float)arg1 ;
-(void)setFrameY:(float)arg1 ;
-(void)setFrameWidth:(float)arg1 ;
-(void)setFrameHeight:(float)arg1 ;
-(float)layoutType;
-(void)setLayoutType:(float)arg1 ;
-(long long)imagePosition;
-(float)titleFontSize;
-(float)titleLineHeight;
-(float)subtitleLineHeight;
-(void)setSubtitleLineHeight:(float)arg1 ;
-(void)setTitleLineHeight:(float)arg1 ;
-(int)accessoryViewHeight;
-(float)frameWidth;
-(long long)columnSpan;
-(long long)rowSpan;
-(void)setRowSpan:(long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
@end

