/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:12 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSData;

@interface NTPBArticleScroll : PBCodable <NSCopying> {

	NSString* _articleId;
	NSData* _articleSessionId;
	NSData* _articleViewingSessionId;
	NSData* _feedViewExposureId;
	NSString* _referencedArticleId;
	int _scrollHostViewType;
	NSString* _scrollVelocity;
	NSString* _sectionHeadlineId;
	NSString* _sourceChannelId;
	NSString* _verticalScrollPositionEnd;
	NSString* _verticalScrollPositionStart;
	BOOL _adSupportedChannel;
	SCD_Struct_NT10 _has;

}

@property (nonatomic,readonly) BOOL hasArticleId; 
@property (nonatomic,retain) NSString * articleId;                                //@synthesize articleId=_articleId - In the implementation block
@property (nonatomic,readonly) BOOL hasReferencedArticleId; 
@property (nonatomic,retain) NSString * referencedArticleId;                      //@synthesize referencedArticleId=_referencedArticleId - In the implementation block
@property (nonatomic,readonly) BOOL hasArticleSessionId; 
@property (nonatomic,retain) NSData * articleSessionId;                           //@synthesize articleSessionId=_articleSessionId - In the implementation block
@property (nonatomic,readonly) BOOL hasArticleViewingSessionId; 
@property (nonatomic,retain) NSData * articleViewingSessionId;                    //@synthesize articleViewingSessionId=_articleViewingSessionId - In the implementation block
@property (nonatomic,readonly) BOOL hasSourceChannelId; 
@property (nonatomic,retain) NSString * sourceChannelId;                          //@synthesize sourceChannelId=_sourceChannelId - In the implementation block
@property (assign,nonatomic) BOOL hasScrollHostViewType; 
@property (assign,nonatomic) int scrollHostViewType;                              //@synthesize scrollHostViewType=_scrollHostViewType - In the implementation block
@property (nonatomic,readonly) BOOL hasVerticalScrollPositionStart; 
@property (nonatomic,retain) NSString * verticalScrollPositionStart;              //@synthesize verticalScrollPositionStart=_verticalScrollPositionStart - In the implementation block
@property (nonatomic,readonly) BOOL hasVerticalScrollPositionEnd; 
@property (nonatomic,retain) NSString * verticalScrollPositionEnd;                //@synthesize verticalScrollPositionEnd=_verticalScrollPositionEnd - In the implementation block
@property (nonatomic,readonly) BOOL hasScrollVelocity; 
@property (nonatomic,retain) NSString * scrollVelocity;                           //@synthesize scrollVelocity=_scrollVelocity - In the implementation block
@property (nonatomic,readonly) BOOL hasFeedViewExposureId; 
@property (nonatomic,retain) NSData * feedViewExposureId;                         //@synthesize feedViewExposureId=_feedViewExposureId - In the implementation block
@property (assign,nonatomic) BOOL hasAdSupportedChannel; 
@property (assign,nonatomic) BOOL adSupportedChannel;                             //@synthesize adSupportedChannel=_adSupportedChannel - In the implementation block
@property (nonatomic,readonly) BOOL hasSectionHeadlineId; 
@property (nonatomic,retain) NSString * sectionHeadlineId;                        //@synthesize sectionHeadlineId=_sectionHeadlineId - In the implementation block
-(void)setArticleId:(NSString *)arg1 ;
-(void)setReferencedArticleId:(NSString *)arg1 ;
-(void)setArticleSessionId:(NSData *)arg1 ;
-(void)setArticleViewingSessionId:(NSData *)arg1 ;
-(void)setSourceChannelId:(NSString *)arg1 ;
-(void)setFeedViewExposureId:(NSData *)arg1 ;
-(void)setSectionHeadlineId:(NSString *)arg1 ;
-(BOOL)hasArticleId;
-(BOOL)hasReferencedArticleId;
-(BOOL)hasArticleSessionId;
-(BOOL)hasArticleViewingSessionId;
-(BOOL)hasSourceChannelId;
-(BOOL)hasFeedViewExposureId;
-(void)setAdSupportedChannel:(BOOL)arg1 ;
-(void)setHasAdSupportedChannel:(BOOL)arg1 ;
-(BOOL)hasAdSupportedChannel;
-(BOOL)hasSectionHeadlineId;
-(NSString *)articleId;
-(NSString *)referencedArticleId;
-(NSData *)articleSessionId;
-(NSData *)articleViewingSessionId;
-(NSString *)sourceChannelId;
-(NSData *)feedViewExposureId;
-(BOOL)adSupportedChannel;
-(NSString *)sectionHeadlineId;
-(void)setVerticalScrollPositionStart:(NSString *)arg1 ;
-(void)setVerticalScrollPositionEnd:(NSString *)arg1 ;
-(void)setScrollVelocity:(NSString *)arg1 ;
-(int)scrollHostViewType;
-(void)setScrollHostViewType:(int)arg1 ;
-(void)setHasScrollHostViewType:(BOOL)arg1 ;
-(BOOL)hasScrollHostViewType;
-(BOOL)hasVerticalScrollPositionStart;
-(BOOL)hasVerticalScrollPositionEnd;
-(BOOL)hasScrollVelocity;
-(NSString *)verticalScrollPositionStart;
-(NSString *)verticalScrollPositionEnd;
-(NSString *)scrollVelocity;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
@end

