/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:43:51 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol Swift._NSSetCoreType <Swift._NSCopyingType,Swift._NSFastEnumerationType>
@property (readonly,nonatomic) long long count; 
@required
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3;
-(long long)count;
-(id)objectEnumerator;
-(id)copyWithZone:(void*)arg1;
-(id)initWithObjects:(const id*)arg1 count:(long long)arg2;
-(id)member:(id)arg1;

@end

