/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:43:52 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Swift._CocoaDictionaryGenerator : _UKNOWN_SUPERCLASS_ {

	 _fastEnumerationState;
	 _fastEnumerationStackBuf;
	 cocoaDictionary;
	 itemIndex;
	 itemCount;

}
@end

