/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:15 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXComponentView.h>
#import <Silex/SXMediaPlaybackControllerDelegate.h>

@protocol SXVideoOverlayButton;
@class AVPlayerViewController, SXAVPlayer, SXAudioComponentOverlayView, SXMediaExposureEvent, UIView, NSString;

@interface SXAudioComponentView : SXComponentView <SXMediaPlaybackControllerDelegate> {

	BOOL _audioHasPlayed;
	AVPlayerViewController* _playerViewController;
	SXAVPlayer* _player;
	SXAudioComponentOverlayView* _overlayView;
	SXMediaExposureEvent* _activeExposureEvent;
	UIView*<SXVideoOverlayButton> _playButton;
	SCD_Struct_SX12 _playbackStartTime;
	SCD_Struct_SX12 _timePlayed;

}

@property (nonatomic,retain) AVPlayerViewController * playerViewController;              //@synthesize playerViewController=_playerViewController - In the implementation block
@property (nonatomic,retain) SXAVPlayer * player;                                        //@synthesize player=_player - In the implementation block
@property (nonatomic,retain) SXAudioComponentOverlayView * overlayView;                  //@synthesize overlayView=_overlayView - In the implementation block
@property (assign,nonatomic) BOOL audioHasPlayed;                                        //@synthesize audioHasPlayed=_audioHasPlayed - In the implementation block
@property (nonatomic,retain) SXMediaExposureEvent * activeExposureEvent;                 //@synthesize activeExposureEvent=_activeExposureEvent - In the implementation block
@property (nonatomic,retain) UIView*<SXVideoOverlayButton> playButton;                   //@synthesize playButton=_playButton - In the implementation block
@property (assign,nonatomic) SCD_Struct_SX12 playbackStartTime;                          //@synthesize playbackStartTime=_playbackStartTime - In the implementation block
@property (assign,nonatomic) SCD_Struct_SX12 timePlayed;                                 //@synthesize timePlayed=_timePlayed - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithComponent:(id)arg1 componentLayout:(id)arg2 context:(id)arg3 ;
-(void)presentComponent;
-(void)finishMediaExposureEvent;
-(void)createMediaExposureEventIfLoadedAndVisible;
-(void)visibilityStateDidChangeFromState:(long long)arg1 ;
-(SXMediaExposureEvent *)activeExposureEvent;
-(void)setActiveExposureEvent:(SXMediaExposureEvent *)arg1 ;
-(void)playButtonTapped:(id)arg1 ;
-(void)loadAudio;
-(void)setupPlayerViewControllerWithPlayer:(id)arg1 ;
-(void)setPlaybackStartTime:(SCD_Struct_SX12)arg1 ;
-(void)submitMediaEngageCompleteEvent;
-(SCD_Struct_SX12)playbackStartTime;
-(void)submitMediaEngageEventForUserAction:(unsigned long long)arg1 ;
-(void)setAudioHasPlayed:(BOOL)arg1 ;
-(void)hidePlaybackControls;
-(void)showPlaybackControls;
-(void)mediaPlaybackController:(id)arg1 playerDidStartPlayback:(id)arg2 ;
-(void)mediaPlaybackController:(id)arg1 playerDidPausePlayback:(id)arg2 ;
-(void)mediaPlaybackController:(id)arg1 playerDidResumePlayback:(id)arg2 ;
-(void)mediaPlaybackController:(id)arg1 playerDidFinishPlayback:(id)arg2 ;
-(BOOL)audioHasPlayed;
-(void)dealloc;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)willMoveToWindow:(id)arg1 ;
-(void)loadImage;
-(SCD_Struct_SX12)timePlayed;
-(void)setTimePlayed:(SCD_Struct_SX12)arg1 ;
-(void)setPlayerViewController:(AVPlayerViewController *)arg1 ;
-(AVPlayerViewController *)playerViewController;
-(void)setOverlayView:(SXAudioComponentOverlayView *)arg1 ;
-(UIView*<SXVideoOverlayButton>)playButton;
-(SXAudioComponentOverlayView *)overlayView;
-(void)setPlayer:(SXAVPlayer *)arg1 ;
-(SXAVPlayer *)player;
-(void)setPlayButton:(UIView*<SXVideoOverlayButton>)arg1 ;
@end

