/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:16 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <UIKit/UIImageView.h>

@class UIImage;

@interface SXAudioComponentOverlayView : UIImageView {

	UIImage* _audioIndicatorImage;

}

@property (nonatomic,readonly) UIImage * audioIndicatorImage;              //@synthesize audioIndicatorImage=_audioIndicatorImage - In the implementation block
-(UIImage *)audioIndicatorImage;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setImage:(id)arg1 ;
-(id)image;
@end

