/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:12 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXComponentBehaviorHandler.h>

@class UIView;

@interface SXBackgroundParallaxImageComponentBehaviorHandler : SXComponentBehaviorHandler {

	BOOL _windowedScrollSuperViewWasClipped;
	UIView* _windowedScrollContentView;
	double _originalYCenter;
	CGRect _windowedScrollContentViewOriginalFrame;

}

@property (nonatomic,retain) UIView * windowedScrollContentView;                         //@synthesize windowedScrollContentView=_windowedScrollContentView - In the implementation block
@property (assign,nonatomic) CGRect windowedScrollContentViewOriginalFrame;              //@synthesize windowedScrollContentViewOriginalFrame=_windowedScrollContentViewOriginalFrame - In the implementation block
@property (assign,nonatomic) double originalYCenter;                                     //@synthesize originalYCenter=_originalYCenter - In the implementation block
@property (assign,nonatomic) BOOL windowedScrollSuperViewWasClipped;                     //@synthesize windowedScrollSuperViewWasClipped=_windowedScrollSuperViewWasClipped - In the implementation block
-(id)initWithComponentView:(id)arg1 withBehavior:(id)arg2 ;
-(void)setupWindowedScroll;
-(UIView *)windowedScrollContentView;
-(double)originalYCenter;
-(void)setWindowedScrollContentView:(UIView *)arg1 ;
-(void)setWindowedScrollContentViewOriginalFrame:(CGRect)arg1 ;
-(void)setWindowedScrollSuperViewWasClipped:(BOOL)arg1 ;
-(CGRect)windowedScrollContentViewOriginalFrame;
-(void)setOriginalYCenter:(double)arg1 ;
-(BOOL)windowedScrollSuperViewWasClipped;
-(void)destroyWindowedScroll;
-(void)updateWithBehaviorController:(id)arg1 ;
-(void)destroyWithBehaviorController:(id)arg1 ;
-(void)hostingViewWillChangeSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
@end

