/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:13 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SXEventCenterDelegate;
@class NSMutableArray;

@interface SXEventCenter : NSObject {

	id<SXEventCenterDelegate> _delegate;
	NSMutableArray* _enterBackgroundObservers;

}

@property (nonatomic,__weak,readonly) id<SXEventCenterDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSMutableArray * enterBackgroundObservers;              //@synthesize enterBackgroundObservers=_enterBackgroundObservers - In the implementation block
-(void)submitEvent:(id)arg1 ;
-(NSMutableArray *)enterBackgroundObservers;
-(void)addApplicationDidEnterBackgroundObserverBlock:(/*^block*/id)arg1 ;
-(id<SXEventCenterDelegate>)delegate;
-(id)initWithDelegate:(id)arg1 ;
-(void)applicationDidEnterBackground;
@end

