/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:13 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <UIKit/UIView.h>

@class SXFill, UIView;

@interface SXFillView : UIView {

	SXFill* _fill;
	UIView* _clippingView;
	CGRect _absoluteFillFrame;

}

@property (nonatomic,readonly) SXFill * fill;                           //@synthesize fill=_fill - In the implementation block
@property (assign,nonatomic,__weak) UIView * clippingView;              //@synthesize clippingView=_clippingView - In the implementation block
@property (nonatomic,readonly) CGRect absoluteFillFrame;                //@synthesize absoluteFillFrame=_absoluteFillFrame - In the implementation block
-(id)initWithFill:(id)arg1 ;
-(CGRect)absoluteFillFrame;
-(UIView *)clippingView;
-(void)setClippingView:(UIView *)arg1 ;
-(SXFill *)fill;
@end

