/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:13 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, SXComponentTextStyle;

@interface SXFullScreenCaption : NSObject {

	NSString* _text;
	SXComponentTextStyle* _textStyle;

}

@property (nonatomic,readonly) NSString * text;                               //@synthesize text=_text - In the implementation block
@property (nonatomic,readonly) SXComponentTextStyle * textStyle;              //@synthesize textStyle=_textStyle - In the implementation block
-(id)initWithText:(id)arg1 andTextStyle:(id)arg2 ;
-(NSString *)text;
-(SXComponentTextStyle *)textStyle;
@end

