/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:13 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXFillView.h>

@class SXImageFill, SXImageResource, SXContext, SXImageView, UIImage, SXAnimatedImage;

@interface SXImageFillView : SXFillView {

	SXImageFill* _imageFill;
	SXImageResource* _imageResource;
	SXContext* _context;
	SXImageView* _imageView;

}

@property (nonatomic,readonly) SXImageFill * imageFill;                      //@synthesize imageFill=_imageFill - In the implementation block
@property (nonatomic,readonly) SXImageResource * imageResource;              //@synthesize imageResource=_imageResource - In the implementation block
@property (nonatomic,readonly) SXContext * context;                          //@synthesize context=_context - In the implementation block
@property (nonatomic,readonly) UIImage * image; 
@property (nonatomic,readonly) SXAnimatedImage * animatedImage; 
@property (nonatomic,readonly) SXImageView * imageView;                      //@synthesize imageView=_imageView - In the implementation block
-(CGRect)absoluteFillFrame;
-(id)initWithImageFill:(id)arg1 imageResource:(id)arg2 context:(id)arg3 ;
-(void)dealloc;
-(void)layoutSubviews;
-(UIImage *)image;
-(SXContext *)context;
-(SXImageView *)imageView;
-(void)pause;
-(SXImageResource *)imageResource;
-(void)play;
-(SXAnimatedImage *)animatedImage;
-(SXImageFill *)imageFill;
@end

