/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:12 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXOEmbedComponentSizer.h>

@interface SXInstagramOEmbedComponentSizer : SXOEmbedComponentSizer
+(double)supportedMinimumWidth;
+(double)supportedMaximumWidth;
-(double)calculateHeightForWidth:(double)arg1 ;
@end

