/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:15 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXAddition.h>

@class NSURL;

@interface SXLinkAddition : SXAddition

@property (nonatomic,readonly) NSURL * URL; 
+(id)typeString;
-(NSURL *)URL;
-(id)URLWithValue:(id)arg1 withType:(int)arg2 ;
@end

