/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:16 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, NSPointerArray, SXAVPlayer;

@interface SXMediaPlaybackController : NSObject {

	NSMutableArray* _players;
	NSPointerArray* _componentViews;
	SXAVPlayer* _activePlayer;

}

@property (nonatomic,readonly) NSMutableArray * players;                     //@synthesize players=_players - In the implementation block
@property (nonatomic,readonly) NSPointerArray * componentViews;              //@synthesize componentViews=_componentViews - In the implementation block
@property (nonatomic,retain) SXAVPlayer * activePlayer;                      //@synthesize activePlayer=_activePlayer - In the implementation block
-(NSPointerArray *)componentViews;
-(void)pauseActivePlayer;
-(void)unregisterPlayer:(id)arg1 componentView:(id)arg2 ;
-(void)registerPlayer:(id)arg1 componentView:(id)arg2 ;
-(void)unregisterAllPlayers;
-(void)registerObserversForPlayer:(id)arg1 ;
-(void)unregisterObserversForPlayer:(id)arg1 ;
-(void)addRateObserverForPlayer:(id)arg1 ;
-(void)addPlayedToEndObserverForPlayer:(id)arg1 ;
-(void)removeRateObserverForPlayer:(id)arg1 ;
-(void)removePlayedToEndObserverForPlayer:(id)arg1 ;
-(void)playerItemPlayedToEnd:(id)arg1 ;
-(id)playerForItem:(id)arg1 ;
-(void)resignActivePlayer:(id)arg1 ;
-(void)playerFinishedPlayback:(id)arg1 ;
-(void)pausePlayer:(id)arg1 ;
-(void)seekPlayerToStart:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)assignActivePlayer:(id)arg1 ;
-(void)playerStartedPlayback:(id)arg1 ;
-(void)playerResumedPlayback:(id)arg1 ;
-(void)playerPausedPlayback:(id)arg1 ;
-(void)setActivePlayer:(SXAVPlayer *)arg1 ;
-(id)componentViewForPlayer:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)applicationDidEnterBackground:(id)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(SXAVPlayer *)activePlayer;
-(NSMutableArray *)players;
@end

