/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:17 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXOEmbedResponse.h>

@class NSString;

@interface SXOEmbedRichResponse : SXOEmbedResponse

@property (nonatomic,readonly) NSString * HTML; 
@property (nonatomic,readonly) CGSize size; 
@property (nonatomic,readonly) double width; 
@property (nonatomic,readonly) double height; 
+(id)jsonPropertyNameForObjCPropertyName:(id)arg1 ;
-(double)height;
-(double)width;
-(NSString *)HTML;
-(CGSize)size;
@end

