/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:16 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXComponentBehaviorHandler.h>

@interface SXParallaxComponentBehaviorHandler : SXComponentBehaviorHandler {

	BOOL _isRotating;
	BOOL _shouldSetup;
	BOOL _inFirstViewport;
	BOOL _inLastViewport;

}

@property (nonatomic,readonly) BOOL isRotating;                 //@synthesize isRotating=_isRotating - In the implementation block
@property (assign,nonatomic) BOOL shouldSetup;                  //@synthesize shouldSetup=_shouldSetup - In the implementation block
@property (assign,nonatomic) BOOL inFirstViewport;              //@synthesize inFirstViewport=_inFirstViewport - In the implementation block
@property (assign,nonatomic) BOOL inLastViewport;               //@synthesize inLastViewport=_inLastViewport - In the implementation block
-(id)initWithComponentView:(id)arg1 withBehavior:(id)arg2 ;
-(void)updateWithBehaviorController:(id)arg1 ;
-(void)destroyWithBehaviorController:(id)arg1 ;
-(void)hostingViewWillChangeSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(BOOL)shouldSetup;
-(void)setInFirstViewport:(BOOL)arg1 ;
-(void)setInLastViewport:(BOOL)arg1 ;
-(void)setShouldSetup:(BOOL)arg1 ;
-(BOOL)inFirstViewport;
-(BOOL)inLastViewport;
-(BOOL)isRotating;
@end

