/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:17 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSLocale, NSString;

@interface SXTextSource : NSObject {

	NSLocale* _myLocale;

}

@property (nonatomic,readonly) NSString * string; 
@property (nonatomic,readonly) NSLocale * locale; 
@property (nonatomic,readonly) NSLocale * myLocale;              //@synthesize myLocale=_myLocale - In the implementation block
-(void)applyStylingOnTextTangierStorage:(id)arg1 ;
-(void)applyAdditionsOnTextTangierStorage:(id)arg1 ;
-(void)applyListStylingOnTextTangierStorage:(id)arg1 ;
-(id)determineLocaleForString:(id)arg1 ;
-(NSLocale *)myLocale;
-(id)description;
-(NSString *)string;
-(NSLocale *)locale;
@end

