/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 1:44:16 AM Japan Standard Time
* Operating System: Version 9.2.1 (Build 13D15)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXComponentView.h>
#import <libobjc.A.dylib/ADPrerollViewDelegate.h>
#import <Silex/SXMediaPlaybackControllerDelegate.h>

@protocol SXVideoOverlayButton;
@class UIView, UIActivityIndicatorView, SXImageView, AVPlayerViewController, SXAVPlayer, SXMediaExposureEvent, ADPrerollView, SXPrerollAdResponse, NSString;

@interface SXVideoComponentView : SXComponentView <ADPrerollViewDelegate, SXMediaPlaybackControllerDelegate> {

	BOOL _videoHasPlayed;
	BOOL _isPlaying;
	BOOL _playVideoWhenReadyForDisplay;
	BOOL _prerollHasPlayed;
	BOOL _isLoadingPrerollAd;
	BOOL _playAdWhenReadyForDisplay;
	UIView*<SXVideoOverlayButton> _playButton;
	UIActivityIndicatorView* _activityIndicator;
	SXImageView* _overlayView;
	AVPlayerViewController* _playerViewController;
	SXAVPlayer* _player;
	SXMediaExposureEvent* _activeExposureEvent;
	id _adTimeObserver;
	ADPrerollView* _prerollView;
	SXAVPlayer* _adPlayer;
	SXPrerollAdResponse* _prerollAdResponse;
	/*^block*/id _cancelHandler;
	SCD_Struct_SX12 _playbackStartTime;
	SCD_Struct_SX12 _timePlayed;

}

@property (nonatomic,retain) UIView*<SXVideoOverlayButton> playButton;                   //@synthesize playButton=_playButton - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView * activityIndicator;                //@synthesize activityIndicator=_activityIndicator - In the implementation block
@property (nonatomic,retain) SXImageView * overlayView;                                  //@synthesize overlayView=_overlayView - In the implementation block
@property (nonatomic,retain) AVPlayerViewController * playerViewController;              //@synthesize playerViewController=_playerViewController - In the implementation block
@property (nonatomic,retain) SXAVPlayer * player;                                        //@synthesize player=_player - In the implementation block
@property (assign,nonatomic) BOOL videoHasPlayed;                                        //@synthesize videoHasPlayed=_videoHasPlayed - In the implementation block
@property (assign,nonatomic) BOOL isPlaying;                                             //@synthesize isPlaying=_isPlaying - In the implementation block
@property (assign,nonatomic) BOOL playVideoWhenReadyForDisplay;                          //@synthesize playVideoWhenReadyForDisplay=_playVideoWhenReadyForDisplay - In the implementation block
@property (nonatomic,retain) SXMediaExposureEvent * activeExposureEvent;                 //@synthesize activeExposureEvent=_activeExposureEvent - In the implementation block
@property (assign,nonatomic) SCD_Struct_SX12 playbackStartTime;                          //@synthesize playbackStartTime=_playbackStartTime - In the implementation block
@property (assign,nonatomic) SCD_Struct_SX12 timePlayed;                                 //@synthesize timePlayed=_timePlayed - In the implementation block
@property (nonatomic,retain) id adTimeObserver;                                          //@synthesize adTimeObserver=_adTimeObserver - In the implementation block
@property (nonatomic,retain) ADPrerollView * prerollView;                                //@synthesize prerollView=_prerollView - In the implementation block
@property (nonatomic,retain) SXAVPlayer * adPlayer;                                      //@synthesize adPlayer=_adPlayer - In the implementation block
@property (assign,nonatomic) BOOL prerollHasPlayed;                                      //@synthesize prerollHasPlayed=_prerollHasPlayed - In the implementation block
@property (nonatomic,retain) SXPrerollAdResponse * prerollAdResponse;                    //@synthesize prerollAdResponse=_prerollAdResponse - In the implementation block
@property (assign,nonatomic) BOOL isLoadingPrerollAd;                                    //@synthesize isLoadingPrerollAd=_isLoadingPrerollAd - In the implementation block
@property (nonatomic,copy) id cancelHandler;                                             //@synthesize cancelHandler=_cancelHandler - In the implementation block
@property (assign,nonatomic) BOOL playAdWhenReadyForDisplay;                             //@synthesize playAdWhenReadyForDisplay=_playAdWhenReadyForDisplay - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(CGRect)targetContentFrame;
-(void)renderContents;
-(id)initWithComponent:(id)arg1 componentLayout:(id)arg2 context:(id)arg3 ;
-(void)presentComponent;
-(void)finishMediaExposureEvent;
-(void)createMediaExposureEventIfLoadedAndVisible;
-(void)visibilityStateDidChangeFromState:(long long)arg1 ;
-(SXMediaExposureEvent *)activeExposureEvent;
-(void)setActiveExposureEvent:(SXMediaExposureEvent *)arg1 ;
-(void)cancelAdRequest;
-(void)playButtonTapped:(id)arg1 ;
-(void)setupPlayerViewControllerWithPlayer:(id)arg1 ;
-(void)setPlaybackStartTime:(SCD_Struct_SX12)arg1 ;
-(void)submitMediaEngageCompleteEvent;
-(SCD_Struct_SX12)playbackStartTime;
-(void)submitMediaEngageEventForUserAction:(unsigned long long)arg1 ;
-(void)mediaPlaybackController:(id)arg1 playerDidStartPlayback:(id)arg2 ;
-(void)mediaPlaybackController:(id)arg1 playerDidPausePlayback:(id)arg2 ;
-(void)mediaPlaybackController:(id)arg1 playerDidResumePlayback:(id)arg2 ;
-(void)mediaPlaybackController:(id)arg1 playerDidFinishPlayback:(id)arg2 ;
-(void)cleanupPrerollView;
-(ADPrerollView *)prerollView;
-(void)setPlayAdWhenReadyForDisplay:(BOOL)arg1 ;
-(void)loadAd;
-(void)setPlayVideoWhenReadyForDisplay:(BOOL)arg1 ;
-(void)loadVideo;
-(SXPrerollAdResponse *)prerollAdResponse;
-(BOOL)isLoadingPrerollAd;
-(void)setIsLoadingPrerollAd:(BOOL)arg1 ;
-(void)setPrerollAdResponse:(SXPrerollAdResponse *)arg1 ;
-(void)setupPrerollViewWithPlayer:(id)arg1 ;
-(void)setPrerollView:(ADPrerollView *)arg1 ;
-(BOOL)prerollHasPlayed;
-(void)setAdTimeObserver:(id)arg1 ;
-(void)setPrerollHasPlayed:(BOOL)arg1 ;
-(id)adTimeObserver;
-(void)setIsPlaying:(BOOL)arg1 ;
-(void)adPlaybackFinished;
-(void)adPlaybackPaused;
-(void)adPlaybackResumed;
-(void)adPlaybackStarted;
-(void)setVideoHasPlayed:(BOOL)arg1 ;
-(BOOL)playVideoWhenReadyForDisplay;
-(BOOL)playAdWhenReadyForDisplay;
-(BOOL)videoHasPlayed;
-(void)setCancelHandler:(id)arg1 ;
-(void)dealloc;
-(void)willMoveToWindow:(id)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(CGRect)visibleFrame;
-(UIActivityIndicatorView *)activityIndicator;
-(void)setActivityIndicator:(UIActivityIndicatorView *)arg1 ;
-(id)cancelHandler;
-(SCD_Struct_SX12)timePlayed;
-(void)setTimePlayed:(SCD_Struct_SX12)arg1 ;
-(void)doneButtonPressed;
-(void)setPlayerViewController:(AVPlayerViewController *)arg1 ;
-(AVPlayerViewController *)playerViewController;
-(void)setOverlayView:(SXImageView *)arg1 ;
-(UIView*<SXVideoOverlayButton>)playButton;
-(SXImageView *)overlayView;
-(void)setPlayer:(SXAVPlayer *)arg1 ;
-(BOOL)isPlaying;
-(SXAVPlayer *)player;
-(void)actionButtonPressed;
-(SXAVPlayer *)adPlayer;
-(void)setAdPlayer:(SXAVPlayer *)arg1 ;
-(BOOL)prerollViewRequestsEmbeddedStatus;
-(void)playButtonPressed;
-(void)pauseButtonPressed;
-(void)skipButtonPressed;
-(void)discardContents;
-(void)setPlayButton:(UIView*<SXVideoOverlayButton>)arg1 ;
@end

